package Enums;

public enum ExceptionType {
wrongTimeFormat,
wrongIndexFormat,
wrongSortFormat,
wrongTaskType,
wrongFormat,
wrongPriority,
wrongDateFormat,
negativeTimeAmount,
emptyList,
emptyUser,
outOfBounds,
emptySubTask,
leaveDone,
subTaskError,
duplicateSubtask,
emptyDescription,
emptyDate,
emptyTaskType,
logError,
writeError,
loadError,
invalidInputString,
invalidDateRange,
invalidCommand,
emptyIndex,
noSubtask,
invalidDateError,
assigneeSetToEveyone
}
