package leduc.exception;


/**
 * Abstract class which represent a exception generated by the execution of the leduc.Duke program.
 * Extends to Exception.
 */
public abstract class DukeException extends Exception{

    /**
     * Constructor of leduc.exception.DukeException
     */
    public DukeException(){
        super();
    }
    /**
     * Display a message which explain the Exception which is catch.
     * @return the error message
     */
    public abstract String print();
}
