@startuml
participant "Parser Logic"
participant ArgCommand
participant ArgSpec

"Parser Logic" -> ArgCommand : Construct
activate ArgCommand

"Parser Logic" -> ArgCommand : Request Specification
ArgCommand -> ArgSpec : Get Specification
ArgCommand <-- ArgSpec : Return Specification
"Parser Logic" <-- ArgCommand : Return Specification

activate "Parser Logic"
"Parser Logic" -> "Parser Logic" : Parse
"Parser Logic" -> ArgCommand : Load Parameters
"Parser Logic" -> ArgCommand : execute()
deactivate "Parser Logic"

ArgCommand -> ArgSpec : executeWithCmd()
note right
  This provides the ArgCommand as
  a reference to ArgSpec, to allow 
  it to access switch and argument 
  values
end note
activate ArgSpec
ArgSpec ->] : execute()
deactivate ArgSpec
deactivate ArgCommand
@enduml
