package javacake.commands;

import javacake.Logic;
import javacake.exceptions.DukeException;
import javacake.storage.Profile;
import javacake.storage.Storage;
import javacake.storage.StorageManager;
import javacake.ui.Ui;

import java.io.File;
import java.io.IOException;

public class CreateNoteCommand extends Command {

    private String defaultFileName = "Notes";
    private static String userGivenFileName = "Notes";
    private static int defaultFileNameCounter = 1;
    private String defaultDirectoryPath = "data/notes/";

    private static final char[] ILLEGAL_CHARACTERS = { '/', '\n', '\r', '\t',
        '\0', '\f', '`', '?', '*', '\\', '<', '>', '|', '\"', ':', '.', ','};

    /**
     * Constructor for CreateNoteCommand.
     * @param inputCommand Input Command from the user to create note.
     * @throws DukeException If the input command is invalid.
     */
    public CreateNoteCommand(String inputCommand) throws DukeException {
        type = CmdType.CREATENOTE;
        //File file = new File(defaultDirectoryPath + defaultFileName);
        Storage.generateFolder(new File("data/notes/"));
        processCreateNoteCommand(inputCommand);
    }

    /**
     * If inputCommand has no parameter, command will create a file based on auto-generated file name.
     * Auto-generation is done by checking if file containing the defaultFileName exists.
     * If it exists, number starting from '1' will be concatenated to the defaultFileName.
     * If inputCommand has a parameter, command checks if specified file name is valid.
     * Creates file if specified file name is valid.
     * @param inputCommand Input Command from the user to create note.
     * @throws DukeException If the input command is invalid.
     */
    private void processCreateNoteCommand(String inputCommand) throws DukeException {
        String[] wordsInInputCommand = inputCommand.split("\\s+");

        if (createNoteCommandHasSpecifiedFileName(inputCommand)) {
            if (!containsIllegals(wordsInInputCommand[1])) {
                userGivenFileName = wordsInInputCommand[1];
            } else {
                throw new DukeException("Invalid file name: Illegal character in file name detected!");
            }
        } else if (validCommandWithNoSpecifiedFileName(inputCommand)) {
            while (checkNotesFileExist(defaultDirectoryPath + userGivenFileName + ".txt")) {
                generateNewDefaultFileName();
            }
        } else {
            throw new DukeException("Invalid command: To write notes, "
                    + "type 'createnote' followed by desired (optional) filename.");
        }
    }

    /**
     * Checks if CreateNoteCommand has a specified file name.
     * @param inputCommand Input Command from the user to create note.
     * @return True if CreateNoteCommand has a specified file name.
     */
    private boolean createNoteCommandHasSpecifiedFileName(String inputCommand) {
        String[] wordsInInputCommand = inputCommand.split("\\s+");
        if (wordsInInputCommand.length == 2 && wordsInInputCommand[0].equals("createnote")) {
            return true;
        }
        return false;
    }

    /**
     * Checks if CreateNoteCommand with no parameter is valid.
     * @param inputCommand Input Command from the user to create note.
     * @return True if CreateNoteCommand with no parameter is valid.
     */
    private boolean validCommandWithNoSpecifiedFileName(String inputCommand) {
        String[] wordsInInputCommand = inputCommand.split("\\s+");
        if (wordsInInputCommand.length == 1 && wordsInInputCommand[0].equals("createnote")) {
            return true;
        }
        return false;
    }

    /**
     * Checks if the input file name contains any illegal characters.
     * @param inputFileName Specified file name by user.
     * @return True if file name does not contains illegal characters.
     */
    public static boolean containsIllegals(String inputFileName) {
        for (char illegalChar : ILLEGAL_CHARACTERS) {
            if (inputFileName.indexOf(illegalChar) >= 0) {
                return true;
            }
        }
        return false;
    }

    /**
     * Generates file name for user.
     * Generated by concatenating number to defaultFileName.
     */
    private void generateNewDefaultFileName() {
        userGivenFileName = defaultFileName + defaultFileNameCounter;
        defaultFileNameCounter++;
    }

    /**
     * Checks if file name already exists.
     * If file name does not exist, create note for user.
     * @param logic TaskList containing current tasks
     * @param ui the Ui responsible for outputting messages
     * @param storageManager storage container
     * @return Message when note is created successfully.
     * @throws DukeException If file does not exists.
     */
    @Override
    public String execute(Logic logic, Ui ui, StorageManager storageManager) throws DukeException {
        try {
            StringBuilder sb = new StringBuilder();
            sb.append(userGivenFileName).append(".txt");
            String formattedFileName = sb.toString();
            sb.insert(0, defaultDirectoryPath);
            String newFilePath = sb.toString();
            //System.out.println(newFilePath);
            if (checkNotesFileExist(newFilePath)) {
                throw new DukeException("File already exists, please type 'editnote "
                        + formattedFileName + "' to edit the file instead");
            } else  {
                File file = new File(newFilePath);
                if (!file.createNewFile()) {
                    throw new DukeException("File '" + formattedFileName + "' was not created! Pls try again!");
                }
                return "File '" + formattedFileName + "'has been created successfully!\n";
            }
        } catch (IOException e) {
            throw new DukeException(e.getMessage());
        }

    }

    /**
     * Checks if file specified in file path exists.
     * @param filePath Path to the file to be created.
     * @return True if file already exists.
     */
    private boolean checkNotesFileExist(String filePath) {
        File tempFile = new File(filePath);
        return tempFile.exists();
    }
}
