package Commands;

import Commons.LookupTable;
import Commons.Storage;
import Commons.Ui;
import Tasks.TaskList;

import java.util.ArrayList;

public class RetrieveFreeTimesCommand extends Command {
    private Integer option;
    private static String selectedOption;

    public RetrieveFreeTimesCommand(Integer option) {
        this.option = option;
    }

    private boolean checkIsEmpty (ArrayList<String> retrievedFreeTimes){
        return (retrievedFreeTimes.size() == 0) ? true : false;
    }

    private boolean checkIfInvalidOption (){
        return (option < 1 || option > 5) ? true : false;
    }

    /**
     * Executes the retriever of earliest available block period generated by FindFreeTimesCommand.
     * @param events The TaskList object for events
     * @param deadlines The TaskList object for deadlines
     * @param ui The Ui object to display the done task message
     * @param storage The Storage object to access file to load or save the tasks
     * @return This returns the method in the Ui object which returns the string to display freeTimes message
     */
    @Override
    public String execute(LookupTable LT, TaskList events, TaskList deadlines, Ui ui, Storage storage) {
        ArrayList<String> retrievedFreeTimes = FindFreeTimesCommand.getCompiledFreeTimesList();
        if (checkIsEmpty(retrievedFreeTimes))return "Please find free times";
        else if(checkIfInvalidOption()) return "Please select options between 1 - 5";
        selectedOption = retrievedFreeTimes.get(option-1);
        return "Selected option " + option + "\n" + selectedOption;
    }

    public static String getSelectedOption() {
        return selectedOption;
    }
}
