/**
 * Abstract class which represent a exception generated by the execution of the Duke program.
 * Extends to Exception.
 */
public abstract class DukeException extends Exception{
    protected Ui ui;

    /**
     * Constructor of DukeException
     * @param ui Ui which deals with the interactions with the user.
     */
    public DukeException(Ui ui){
        this.ui = ui;
    }

    /**
     * Display a message which explain the Exception which is catch.
     */
    public abstract void print();
}
