@startuml

skinparam arrowThickness 1.1
skinparam arrowColor #A09143
skinparam classBackgroundColor #A09143
skinparam Class {
    FontColor #FFFFFF
    BorderThickness 1
    BorderColor #FFFFFF
}

hide footbox
hide circle

skinparam MinClassWidth 50
skinparam ParticipantPadding 10
skinparam Shadowing false
skinparam DefaultTextAlignment center
skinparam packageStyle Rectangle

Package BudgetCommand {
    Class "{abstract}\nCommand" as Command
    Class SetBudgetCommand
    Class EditBudgetCommand
    Class ListBudgetCommand
    Class SavingsBudgetCommand

}
Package Budget {
Class Budget
}

Package Storage {
    Class Storage
}

class SetBudgetCommand {
  -categories: HashMap<String, Double>
  -budgets: HashMap<String, Double>
  -df: DecimalFormat
  +execute(budget: Budget, categoryList: CategoryList, \nstorage: Storage, calendar: ScheduleList)
}

class EditBudgetCommand {
  -categories: HashMap<String, Double>
  -budgets: HashMap<String, Double>
  -df: DecimalFormat
  +execute(budget: Budget, categoryList: CategoryList, \nstorage: Storage, calendar: ScheduleList)
}

class SavingsBudgetCommand {
  -categories: ArrayList<String>
  -startDate: LocalDate
  -endDate: LocalDate
  -df: DecimalFormat
  +execute(budget: Budget, categoryList: CategoryList, storage: Storage, \ncalendar: ScheduleList)
  -viewSingleMonthSavings(budget: Budget, iteratorCategory: String, \ncurrentCategory: Category, outputVal: String)
  -viewMultiMonthSaving(budget: Budget, iteratorCategory: String, \ncurrentCategory: Category, outputVal: String)
}

class ListBudgetCommand {
  -categories: ArrayList<String>
  -df: DecimalFormat
  +execute(budget: Budget, categoryList: CategoryList, \nstorage: Storage, calendar: ScheduleList)
}

class Storage {
  -budgetFilePath: String
  -scheduleFilePath: String
  +loadBudget(catList: ArrayList<Category>) : HashMap<String, Double>
  +saveBudgetToFile(budget: Budget)
}

class Budget {
    -categoryBudget: HashMap<String, Double>
    +addNewBudget(category: String, budget: double)
    +getBudget() : HashMap<String, Double>
    +getBudgetFromCategory(category: String) : double
    +toString() : String
}

SetBudgetCommand -up-|> Command
EditBudgetCommand -up-|> Command
ListBudgetCommand -up-|> Command
SavingsBudgetCommand -up-|> Command

Class HiddenOutside #FFFFFF
HiddenOutside ..> Command

SetBudgetCommand --> Storage
EditBudgetCommand --> Storage

SetBudgetCommand -down-|> Budget
EditBudgetCommand -down-|> Budget
ListBudgetCommand -down-|> Budget
SavingsBudgetCommand -down-|> Budget



@enduml