@startuml
skinparam arrowThickness 1.1
skinparam arrowColor #A09143
skinparam classBackgroundColor #A09143

hide footbox
hide members
hide circle

skinparam MinClassWidth 50
skinparam ParticipantPadding 10
skinparam Shadowing false
skinparam DefaultTextAlignment center
skinparam packageStyle Rectangle


package Parser {
Class Parser
Class "{abstract}\nCommand" as Command
Class parse
class parseGraph
}


UI ..> parse
parse ..> parseGraph
parse ..> parseList
parse ..> parseDelete
parse ..> parseView
parse ..> parseAdd
parse ..> removeSuffix
parse ..> parseInput
parse ..> parseBudget
parse ..> setBudget
parse ..> editBudget
parse ..> parseList

parseGraph ..> Command : creates


@enduml