package Simulations;

public enum Simulation {
    BUYSEED, BUYCHICKEN, BUYCOW,
    PLANTSEED, FEEDCHICKEN, FEEDCOW,
    HARVESTWHEAT, COLLECTEGG, MILKCOW,
    SELLWHEAT, SELLEGG, SELLMILK,
}
