@startuml

SongList *-right- Song
Song o-- Bar
Song o-right- Group
Bar *-- Chord
Bar -left-* Group
Chord *-right- Note
Pitch .. Note

enum Pitch {
    UPPER_C,
    UPPER_B,
    UPPER_A,
    UPPER_G,
    UPPER_F,
    UPPER_E,
    UPPER_D,
    MIDDLE_C,
    LOWER_B,
    LOWER_A,
    LOWER_G,
    LOWER_F,
    LOWER_E,
    LOWER_D,
    LOWER_C
}

@enduml