@startuml
!include style.puml
box Logic STORAGE_COLOR_T1
participant ":Dolla" as Dolla STORAGE_COLOR
participant "dollaData:DollaData" as DollaData STORAGE_COLOR
participant ":StorageRead" as StorageRead STORAGE_COLOR
participant ":StorageWrite" as StorageWrite STORAGE_COLOR
participant ":Storage" as Storage STORAGE_COLOR
participant ":DebtList" as DebtList STORAGE_COLOR
end box

activate Dolla
Dolla -> Dolla : Dolla()
activate Dolla
Dolla -> StorageRead : load()
deactivate Dolla

activate StorageRead
StorageRead -> Storage : addToList()
activate Storage

create DollaData
Dolla -> DollaData : new DollaData()
activate DollaData
DollaData -> Storage : getDebtsFromSave()
Storage --> DollaData
deactivate Storage

Dolla -> DollaData : execute()
DollaData -> DollaData : addToRecordList()
activate DollaData
DollaData -> DebtList : add()
deactivate DollaData
activate DebtList

DebtList -> StorageWrite : setDebts()
activate StorageWrite
StorageWrite -> StorageWrite : save()
activate StorageWrite
deactivate StorageWrite

deactivate Dolla
deactivate DollaData
deactivate StorageRead
deactivate StorageWrite
deactivate DebtList

@enduml