= DukeGeek - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Coach Manager

---

== Overview

This portfolio serves to document my contributions in a Software Engineering project for CS2113T.
The team consist of 4 members and we were tasked to develop a working application within 8 weeks.
Throughout the project, we were challenged to incorporate a Software Engineering project into a product of our own.
We decided to morph the existing application to a task manager called Coach Manager.

Our team have decided to come up with Coach Manager.
Coach Manager is an application that is used for trainers to manage their classes and students for better organization.
Trainers are able create classes, manage their students and also create training plans. This helps coaches to ease
their administrative matters for their classes.

My role was to design a feature that Manages student `details` and `progress` which allow trainers to better organise
their students and keep track of their training progress.

== Summary of contributions

* *Feature*: Added Manage Student Feature.
** What it does: It allows the trainer to manage any relevant information that involves the students.
** Justification: This feature allows the trainer to add a new student and their details, add their training progress and additional notes to a particular student and they are also able to search any keywords in the section.
The commands for this feature can be view from the User Guide {Insert User Guid Link}.

* *Feature*: Added a Menu-based feature.
** What it does: This feature allows the trainer to navigate through respective sections of the app easily.
This feature is implemented through the ParserCommand class.

* *Code contributed*:
 ** [https://github.com/AY1920S1-CS2113T-W13-1/main/blob/master/src/main/java/duke/parser/ParserCommand.java[ParserCommand code]] [https://github.com[Test Code]]
 ** [https://github.com/AY1920S1-CS2113T-W13-1/main/blob/master/src/main/java/duke/parser/ParserManageStudents.java[ParserManageStudents]] [https://github.com[Test Code]]

** Project management:
*** Managed releases `v1.1` - `v1.3` on GitHub.
*** Refactoring of main code.
** Enhancements to existing features:
*** {To be added}
** Documentation:
*** Eg: Did cosmetic tweaks to existing contents of the User Guide: https://github.com[#14]
** Community:
*** Eg: PRs reviewed (with non-trivial review comments): https://github.com[#12], https://github.com[#32], https://github.com[#19], https://github.com[#42]
*** Eg: Contributed to forum discussions (examples:  https://github.com[1], https://github.com[2], https://github.com[3], https://github.com[4])
*** Eg: Reported bugs and suggestions for other teams in the class (examples:  https://github.com[1], https://github.com[2], https://github.com[3])
*** Eg: Some parts of the history feature I added was adopted by several other class mates (https://github.com[1], https://github.com[2])
** Tools:
*** Installed Travis.


== Contributions to the User Guide


_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._

*1. View all students:* `list`  +
Shows a list of all the students in the coach manager.

** *Format*: `list`
** *Examples*:
|===
|`list` +

Here are your list of students: +
1. Danish +
2. Eddie +
3. Scott +
4. Jing Sen +
5. Edmund
|===
*2. Locating a student by name:* `find`  +
Find a student whose names contain any of the given keywords.

** *Format:* `find [KEYWORDS]`

* Short-form will still be matched.  e.g Dan will match Danish
* The search is case insensitive. e.g danish will match Danish
* Only the name is searched

** *Examples*:
|===
|`find Dan` +

Returns Danish and Danial
|===

*3. Adding a student:* `add` +
Add a new student to the list of students.

** *Format:* `add [STUDENT NAME], [AGE], [ADDRESS]`

** *Example:*

|===
|add Danish, 22, Woodlands +

Student have been added: +
Name: danish eddie +
Age: 22 +
Address: woodlands +
Now you have 1 students in your list.
|===

*2.3.4. Deleting a student:* delete *(v1.2)* +
Deleting a specific student from the list of students using the index.

*Format:* delete [INDEX]

* Deletes student at the specific INDEX
* The index refers to the index number shown in the displayed student list
* Index must be a positive integer 1, 2, 3,...

Examples:

* student-list
* delete 3
Deletes the 3rd student on the list

*2.3.5. View student particulars:* particulars *(v2.0)* +
To view the details of specific students.

*Format:* particulars [INDEX]

* All the particulars of the student will be listed. e.g Name, Age, Address

Example:

* list
* Particulars 2
Particulars of the student  at index 2 will be displayed. +
Danish Eddie Particulars: +
Age: 22 +
Home Address: Blk 555 Woodlands Dr 5

*2.3.6. Edit student particulars:* edit *(v2.0)* +
Editing the particulars for a student.

*Format: *edit [INDEX] [ADDRESS]

* Needs to select the student index on the list and the details intended to edit.

Example:

* list
* edit 2 address
* New Address: Clementi Ave 6
Danish Address has been updated: +
Address: Clementi Ave 6


*2.3.7 Add progress to a student: *add progress *(2.0)* +
To add the training progress of a particular student

*Format*: add progress [INDEX] /n [PROGRESS DETAILS]

Example:

* add progress 2
* Able to swim breastroke proficiently
* Progress added for Danish

*2.3.8 View a student progress: *view progress *(2.0)* +
Able to view all the progress of the student

*Format*: view progress [INDEX]

Example:

* view progress 2
* Progress for Danish:
. Able to swim breastroke proficiently.

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=undoredo]

include::../DeveloperGuide.adoc[tag=dataencryption]


== PROJECT: PowerPointLabs

---

_{Optionally, you may include other projects in your portfolio.}_
