:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

=== Lee Wei Hern Jason - Project Portfolio
==== PROJECT: Gazeeebo

==== Overview

|===
This portfolio serves to document my contributions in a Software Engineering project for CS2113T.
The team consist of 5 members and we were tasked to develop a working application within 12 weeks.
Throughout the project, we were challenged to incorporate a Software Engineering project into a product of our own.

Our team have decided to come up with Gazeeebo.
Gazeeebo is an application that is used for NUS Computer Engineering Students to help them get through their school life in NUS.

In Gazeeebo, students interact via the CLI.
It is written in Java, and has about 10kLoC.
|===

=== Summary of contributions

* *Major enhancement : added CAP feature*
** What it does: Allows the user to add module's code, module's credit, module's grade and the semester when the module is taken.
Additionally, it is able to list out all the modules or modules in a particular sem, 
find modules base on the semester or module's code and 
delete modules. When the user list out his modules, the CAP will be shown at the bottom of the list.

** Justification:
This feature improves the product significantly because a user
can now keep track of his grades and see which semester he is falling behind by viewing his CAP.
Additionally, students especially Year 1 students can know which modules to S/U by marking so that they can make
an informed decision on which modules to S/U to acheive a better CAP.
** Highlights:
It requires an in-depth analysis of design alternatives.
The implementation too was challenging as it required changes to existing commands.

** Credits: http://www.nus.edu.sg/registrar/education-at-nus/modular-system.html[NUS Grading System]

* *Minor enhancement:*
** Password login system: User needs to type in the correct password to enter Gazeeebo and the User is able to change the password.
** Added contact feature: User is able to add/list/delete/find contact(s). There are also two inbuilt categories NUS and CEG specially catered for CEG students.
** Added recurring feature: When a tasks has keyword weekly/monthly/yearly, when the task is being marked as done, the tasks will be replaced by another with the updated date of the next event.
** Added edit feature: User is able to edit the task's decription or time or both of them. This saves user the hassle of deleting and create another task because he made a mistake when creating the task.

* *Code contributed:*
[https://nuscs2113-ay1920s1.github.io/dashboard/#search=JasonLeeWeiHern&sort=groupTitle&sortWithin=title&since=2019-09-21&timeframe=commit&mergegroup=false&groupSelect=groupByRepos&breakdown=false&until=2019-10-30&tabOpen=false[Reposense]] +

* *Other contributions:*

**Project management:*
*** Managed merge and release of `v1.4` on GitHub. +

** Enhancements to existing features:
***

**Documentation:*
***

**Community:*
***


*** Added labels for organising and prioritising issues, pull request, merging.
This makes project management more efficient and effective. +
*** PRs reviewed and merged (with non-trivial review comments):
https://github.com/AY1920S1-CS2113T-F10-4/main/pull/159[#159],
https://github.com/AY1920S1-CS2113T-F10-4/main/pull/149[#149],
https://github.com/AY1920S1-CS2113T-F10-4/main/pull/146[#146],
https://github.com/AY1920S1-CS2113T-F10-4/main/pull/123[#123],
https://github.com/AY1920S1-CS2113T-F10-4/main/pull/120[#120],
https://github.com/AY1920S1-CS2113T-F10-4/main/pull/115[#115],
https://github.com/AY1920S1-CS2113T-F10-4/main/pull/101[#101],
https://github.com/AY1920S1-CS2113T-F10-4/main/pull/99[#99],
https://github.com/AY1920S1-CS2113T-F10-4/main/pull/85[#85],
https://github.com/AY1920S1-CS2113T-F10-4/main/pull/74[#74],
https://github.com/AY1920S1-CS2113T-F10-4/main/pull/73[#73],
https://github.com/AY1920S1-CS2113T-F10-4/main/pull/71[#71],
https://github.com/AY1920S1-CS2113T-F10-4/main/pull/60[#60],
https://github.com/AY1920S1-CS2113T-F10-4/main/pull/58[#58],
https://github.com/AY1920S1-CS2113T-F10-4/main/pull/57[#57],
https://github.com/AY1920S1-CS2113T-F10-4/main/pull/56[#56],
https://github.com/AY1920S1-CS2113T-F10-4/main/pull/55[#55],
https://github.com/AY1920S1-CS2113T-F10-4/main/pull/49[#49],
https://github.com/AY1920S1-CS2113T-F10-4/main/pull/48[#48]

*Enhancements to existing features:* +
Wrote additional tests for existing features to increase coverage of 4.2%.
(Pull requests
https://github.com/CS2113-AY1819S2-M11-2/main/pull/160[#160],
https://github.com/CS2113-AY1819S2-M11-2/main/pull/170[#170])

*Documentation:* +
1. Updated User Guide:
https://github.com/CS2113-AY1819S2-M11-2/main/pull/77[#77],
https://github.com/CS2113-AY1819S2-M11-2/main/pull/78[#78],
https://github.com/CS2113-AY1819S2-M11-2/main/pull/160[#160] +
2. Updated Developer Guide:
https://github.com/CS2113-AY1819S2-M11-2/main/pull/87[#87],
https://github.com/CS2113-AY1819S2-M11-2/main/pull/103[#103],
https://github.com/CS2113-AY1819S2-M11-2/main/pull/107[#107],
https://github.com/CS2113-AY1819S2-M11-2/main/pull/170[#170] +
3. Did About Us Documentation:
https://github.com/CS2113-AY1819S2-M11-2/main/blob/master/docs/AboutUs.adoc[AboutUs]


=== PROJECTS:

https://github.com/JasonLeeWeiHern/STOPTHEBUS[CP2106]
