= Vivian Lee - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Duke Email Manager

== About the Project

My team consists of 4 software engineering students, who were tasked with enhancing a basic command line
interface of a personal task manager (Duke) for our Software Engineering Project. We chose to morph the
task manager to an email manager called Duke Email Manager, catered exclusively to students in School Of
Computing to help them better manage their emails. The various features of Duke Email Manager includes a task
manager and email manager that are switchable between each other. Duke Email Manager uses Graphical User
Interface (GUI) for students to use its functionalities by typing in commands.

This is what our project looks like:


My role was to write codes to enhance the task manager in our project. These includes codes for more
natural date format feature and priority feature. The following sections illustrate these
implementations in more detail, as well as relevant documentation I have added to the user and developer
guides in relation to these implementations.

Note the following symbols and formatting used in this document:
|===
|💡|This is a tip. Follow these tips to aid your development of Email Manager.

|===

|===
|ℹ️|This is a note. Read these for additional information.

|===

|===
|⚠️|This is a warning. Heed these warnings to avoid making mistakes that will hamper your development efforts.

|===
== Summary of contributions

This section summarizes the contribution I made towards the project. They mainly include, but not
limited to coding, documentation, and other helpful contributions to the team project.

=== *Enhancement Added*

==== Natural Date Format feature
* *What it does:* Students can define the date (where needed) in International Organization for
Standardization (ISO) date format, or define the date in terms of a day of the week. The natural date
format assumes that the student wants to input the date of the next nearest day of the week.

** For example, if the date today is Thursday, 31/10/2019, and the input date is "Wed", the date will be
saved as 06/11/2019, which is the date of the coming Wednesday.
+
This feature also include the time. If no time is inputted after a day of the week, the time will be
indicated as 0000.

** For example, "Thu" will give a date and time of '31/10/2019 0000', while "Thu 1200" will give
'31/10/2019 1200'.

* *Justification:* This feature significantly reduces the time and effort needed to input the date and
time, especially if students are not exactly sure of the time. It gives more flexibility to students when
inputting dates.

* *Highlights:* This feature also works well with other commands like `update`, where students can update
the date and time of the task using natural date format as well.

* *Code contributed:* Please click the links below to examine code contributed to the creation and
maintenance of this feature:

** Initial implementation of natural date format
+
https://github.com/AY1920S1-CS2113T-F11-3/main/pull/91
** Renamed variable and fix bug which causes error in Todo task
+
https://github.com/AY1920S1-CS2113T-F11-3/main/pull/92
** Fix code to allow update command to take in natural date format
+
https://github.com/AY1920S1-CS2113T-F11-3/main/pull/93
** Refactor all methods related to natural date into the same class
+
https://github.com/AY1920S1-CS2113T-F11-3/main/pull/99
** Refactor natural date class to allow easier testing
+
https://github.com/AY1920S1-CS2113T-F11-3/main/pull/117

==== Priority feature
* *What it does:* Students can set priorities for tasks according to its urgency or severity. (Future
implementation: Tasks will be sorted and displayed in the GUI according to the priorities.)

* *Justification:* With so many tasks in hand, students need a way to indicate which tasks are of higher
priority so that they can complete those tasks first before proceeding to the lower priorities ones.

* *Code contributed:* Please click the links below to examine code contributed to the creation and
maintenance of this feature:

** Initial implementation of priority feature
+
https://github.com/AY1920S1-CS2113T-F11-3/main/pull/79
**


* *Other contributions:*

** Project management:
*** Managed releases `v1.3` - `v1.5rc` (3 releases) on GitHub
** Enhancements to existing features:
*** Updated the GUI color scheme (Pull requests https://github.com[#33], https://github.com[#34])
*** Wrote additional tests for existing features to increase coverage from 88% to 92% (Pull requests https://github.com[#36], https://github.com[#38])
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com[#14]
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com[#12], https://github.com[#32], https://github.com[#19], https://github.com[#42]
*** Contributed to forum discussions (examples:  https://github.com[1], https://github.com[2], https://github.com[3], https://github.com[4])
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com[1], https://github.com[2], https://github.com[3])
*** Some parts of the history feature I added was adopted by several other class mates (https://github.com[1], https://github.com[2])
** Tools:
*** Integrated a third party library (Natty) to the project (https://github.com[#42])
*** Integrated a new Github plugin (CircleCI) to the team repo

_{you can add/remove categories in the list above}_

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=delete]

include::../UserGuide.adoc[tag=dataencryption]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=undoredo]

include::../DeveloperGuide.adoc[tag=dataencryption]


== PROJECT: PowerPointLabs

---

_{Optionally, you may include other projects in your portfolio.}_