= Nicholas Novakovic - Project Portfolio
:site-section: AboutUs
:imagesDir: images
:stylesDir: ../stylesheets

== PROJECT: El Duque

== Overview

El Duque is a task manager application targeting computer science students. The user interacts with it using a CLI. It is written in Java, and has about 6 kLoC.

== Summary of contributions

* *Enhancement*: added *the ability to undo previous commands*
** What it does: allows the user to undo all previous commands one at a time.
** Justification: This feature improves the product significantly because a user can make mistakes in commands and the app should provide a convenient way to rectify them.
** Highlights: This enhancement affects existing commands and commands to be added in future. It required an in-depth analysis of design alternatives. The implementation too was challenging as it required changes to existing commands.

* *Enhancement*: added *the ability to filter tasks*
** What it does: allows the user to organise tasks based on user-defined categories.
** Justification: This feature improves the product significantly because a user can now choose to view tasks from specific categories. This is especially helpful considering our target user audience is computer science students who will have many tasks of varying categories to do. This will help them better organise their tasks. 
** Highlights: This enhancement affects existing tasks, commands, and commands to be added in future. It required an in-depth analysis of design alternatives. The implementation too was challenging as it required changes to existing commands.

* *Enhancement*: improved *the user interface*
** What it does: shows the user their current task list with significantly better clarity and detail.
** Justification: This feature improves the product significantly because a user can now view their tasks more comfortably. This allows them to extract important information from their task list more efficiently than before. This is especially helpful considering our target user audience is computer science students who will have many tasks causing the task list to encapsulate a lot of information. This will help them better organise and understand their tasks.
** Highlights: This enhancement affects existing tasks, commands, and the task list implementation. It required an in-depth analysis of design alternatives. The implementation too was challenging as it required changes to existing commands.

* *Other contributions*:

** Project management:
*** Managed all JAR releases on GitHub
** Enhancements to existing features:
*** Optimised the user interface to improve user interaction, including the format of user input, and the format of the output task list to be shown to the user.
*** Extended tasks to be able to record the duration needed to complete them
** Code contribution:
*** All of my code contributions to the project can be found https://nuscs2113-ay1920s1.github.io/dashboard/#=undefined&search=nicholasnovakovic[here].
** Documentation:
*** Converted the entire DeveloperGuide from a Google Doc to an AsciiDoc to improve the formatting
*** Converted the entire UserGuide from a Google Doc to an AsciiDoc to improve the formatting
** Tools:
*** Integrated a third party library (Gson) to the project

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::UserGuide.adoc[tag=nova]


== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::DeveloperGuide.adoc[tag=logic]

include::DeveloperGuide.adoc[tag=nova]

include::DeveloperGuide.adoc[tag=nova2]