:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets
:repoURL: https://github.com/AY1920S1-CS2113T-W17-3/main
:prURL: {repoURL}/pull
:forumURL: https://github.com/nusCS2113-AY1920S1/forum/issues
:mooMoneyURL: https://github.com/AY1920S1-CS2113T-F14-1/main
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:warning-caption: :warning:
endif::[]

== Shamus Neo Zhi Kai - Project Portfolio for OwlMoney

Hello there, I am __Shamus__.
I am currently pursuing a degree in Information Security at the National University of Singapore (NUS). +
I enjoy server and network administration as well as building and breaking applications. +
This portfolio serves to document my extensive involvement and contribution in a team-based project CS2113T (Software
Engineering & Object-Oriented Programming) module by NUS.
This project spans over a period of about eight weeks, and was completed together with a team of five members
(consisting of <<mong-nus#,Mong Zheng Wei>>, <<briantkm#,Brian Tan Kian Ming>>, <<terencetanwt#,Terence Tan Wee Theng>>,
<<valerietyj#,Valerie Tan Yi Jia>> and myself).

=== About the project

My team and I were tasked with enhancing a basic Command Line Interface (CLI) based personal assistant, named Duke
for our Software Engineering Project. We chose to morph it into a financial tracker and investment management
application called *OwlMoney*. This enhanced application targets undergraduates and fresh graduates and aims to help
them track and manage their finances. +
Some features of *OwlMoney* include tracking of both expenses and expenditures as well as tracking
credit cards and investments such as investment bonds. +
My role as a team leader was to perform project management as well as to write the baseline code for the team to get
started. On top of that, I was also in charge of writing codes for the `investment`, `bonds`, `storage` and
some parts of the `commands` section. +
Lastly, I played a major role while collaborating with my team to implement a *custom string parser*, which was
instrumental in enabling users to be able to enter the parameters of complex commands in any order.
The following sections illustrates these enhancements in more details,
illustrates the relevant sections I have contributed to the project as a whole, as well as the relevant sections I
have added to the user and developer guides in relation to these enhancements.

=== Understanding this Project Portfolio

The following symbols are used through this project portfolio:

include::../UserGuide.adoc[tag=user_guide_common_logo]

=== Summary of Contributions
This section shows a summary of my coding, documentation, and other helpful contributions to the team project.

*Enhancement added:* I added the ability to add `investment` accounts and `bonds`.

* *What it does:* The `investment` account allows the user to create an account specially dedicated for `investment`
purposes.

* *Justification:* As we are targeting undergraduates and fresh graduates who usually do not have good financial
literacy, I believe that *OwlMoney* can play a role in educating them on separating spending from `investment`.
Therefore, no spending transactions can be made on the `investment` account and no investments can be bought in a
savings account.

* *Highlights:* This enhancement automatically credits interest for `bonds` added into the `investment` account every
*6* months from the date of purchase, eliminating the need for the user to manually calculate and enter the interest
in every half-yearly. This prevents errors caused by users forgetting to enter the interest since the interest only
credits twice a year.

* *Credits:* A portion of recording `transactions` and similar features across all bank accounts were inherited from
a common parent class `bank` which was coded by both <<briantkm#,Brian Tan Kian Ming>> and I.

*Code contributed:*

* [link:{repoURL}/commits?author=shamussy[Commits]] [link:{repoURL}/pulls?q=is%3Apr+is%3Aclosed+author%3Ashamussy[Pull
Requests]] [https://nuscs2113-ay1920s1.github.io/dashboard/#search=shamussy[RepoSense Code Contribution Dashboard]]

*Other contributions:*

* *Project Management:*

** There were a total of 5 releases, from version 1.0 to version 1.4. I managed the team's repository and was
responsible for producing all of the releases on Github.

* *Enhancements to existing features:*

** Updated the persistent storage to use `OpenCSV` instead of writing into a conventional `.txt` file. This provides
better clarity and organisation of stored data in secondary storage.

* *Documentation:*

** Responsible for maintaining *over 70%* of content on both the *User Guide* and *Developer Guide* as well as making
it presentable in the `.adoc` format which can be rendered and converted to various other formats since it is
platform independent.

* *Community:*
** Contributed to *forum discussions* (examples: PRs link:{forumURL}/86[#86], link:{forumURL}/61[#61],
link:{forumURL}/60[#60],
link:{forumURL}/57[#57], link:{forumURL}/26[#26], link:{forumURL}/8[#8])

** Reported *substantial amount bugs* in another team's project, link:{mooMoneyURL}[MooMooMoney]
(examples: {mooMoneyURL}/issues/156)[#156], {mooMoneyURL}/issues/157)[#157], {mooMoneyURL}/issues/158)[#158],
{mooMoneyURL}/issues/159)[#159], {mooMoneyURL}/issues/160)[#160], {mooMoneyURL}/issues/161)[#161],
{mooMoneyURL}/issues/162)[#162], {mooMoneyURL}/issues/163)[#163], {mooMoneyURL}/issues/164)[#164],
{mooMoneyURL}/issues/156)[#165])

** Reported bugs in module's teaching materials (examples: PRs link:{forumURL}/11[#11])

* *Tools:*

** Integrated a third party library http://opencsv.sourceforge.net/[OpenCSV] to the project for persistent `storage`.
** Integrated https://travis-ci.org/AY1920S1-CS2113T-W17-3/main[Travis]
& https://ci.appveyor.com/project/shamussy/main[AppVeyor] *Continuous Integration (CI)* tools.
(examples: PRs {prURL}/119[#119])
** Integrated https://coveralls.io/github/AY1920S1-CS2113T-W17-3/main[Coveralls]
& https://codecov.io/gh/AY1920S1-CS2113T-W17-3/main[Codecov] *Code coverage* tools. (examples: PRs {prURL}/133[#133])
** Integrated https://app.codacy.com/manual/OwlMoney/main/dashboard[Codacy] *Code analytics* tool.
** Integrated https://app.netlify.com/sites/ay1920s1-cs2113t-w17-3/deploys[Netlify]
& https://github.com/shamussy/main/deployments[GitHub Deployment] *Deployment preview* tools to the
team's repository (examples: PRs {prURL}/119[#119], {prURL}/101[#101], {prURL}/103[#103])
** Updated *Gradle build configuration* to automate and simplify the build process
(examples: PRs link:{prURL}/101[#101])
** Added a new *Github plugin* (https://github.com/apps/project-bot[project-bot]) to automate triaging of issues in
the team's link:{repoURL}/projects/[Project Board]

=== Contributions to User Guide

|===
|_The following sections illustrate my ability in writing documentation targeting end-users to guide them in using the various features of the application._
|===

include::../UserGuide.adoc[tag=investment_management]

=== Contributions to Developer Guide

|===
|_The following sections illustrate my ability in writing documentation to provide developers insights on the design
of the application. It also showcase the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=bonds_class_diagram]

include::../DeveloperGuide.adoc[tag=editing_bonds]
