= Tan Wee Theng Terence - OwlMoney Project Portfolio
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets
:xrefstyle: full
:repoURL: https://github.com/AY1920S1-CS2113T-W17-3/main
:prURL: {repoURL}/pull
:forumURL: https://github.com/AY1920S1-CS2113T-W17-3/forum/issues
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:warning-caption: :warning:
:sectnums:
endif::[]

== Introduction

I am Terence, currently pursuing a degree in Information Security at the National University of
Singapore (NUS). This portfolio documents my contributions towards *OwlMoney* for the module CS2113T Software
Engineering & Object-Oriented Programming. It aims to demonstrate the theoretical and practical knowledge I have
gained in this module over the semester.

== About the Project

My team (
link:https://github.com/AY1920S1-CS2113T-W17-3/main/blob/master/docs/team/briantkm.adoc[Tan Kian Ming Brian],
link:https://github.com/AY1920S1-CS2113T-W17-3/main/blob/master/docs/team/mong-nus.adoc[Mong Zheng Wei],
link:https://github.com/AY1920S1-CS2113T-W17-3/main/blob/master/docs/team/shamussy.adoc[Shamus Neo Zhi Kai],
link:https://github.com/AY1920S1-CS2113T-W17-3/main/blob/master/docs/team/valerietyj.adoc[Valerie Tan Yi Jia]
) and I were tasked with enhancing the basic command line interface (CLI) personal assistant,
Duke, for our software engineering project. We choose to morph it into a command line financial tracker called
*OwlMoney*. This enhanced application is designed to assist undergraduates and fresh graduates to track and manage
their finances. *OwlMoney* provides a simple and minimalistic CLI that presents information in an organized manner.
It is intuitive so that users who are unfamiliar with CLI can use it with ease.

My role was to design and write codes for the `card` feature, which allows users to track and manage
their credit cards. The following sections illustrate the enhancements in detail, and also the relevant
information that I have added to the user and developer guide with reference to the enhancements.

Note the following symbols and formatting used.
include::../UserGuide.adoc[tag=user_guide_common_logo]

== Summary of Contributions
This section shows a summary of my contributions to the project in terms of features enhancement, project management,
documentation, and other helpful contributions.

=== Features Enhancement

==== Features Implemented: Ability to Manage Credit Cards

* *What it does*: The `card` feature has `add`, `delete`, `edit`, and `list` commands which help users manage
their credit cards.
* *Justification*: Due to the popularity of credit cards, many people including students have one.
Because different cards provide different benefits, some people own several cards.
This feature gives users the ability to manage their credit cards.
* *Highlights*: In line with real credit cards, users will be able to set their monthly spending limits
and rebates.
* *Credits*: Collaborated with <<mong-nus#,Mong Zheng Wei>> to implement the /edit function.

==== Features Implemented: Ability to Manage Credit Card Expenditures

* *What it does*: Each `card` is able to `add`, `delete`, `edit`, and `list` card expenditures which
helps users manage their credit card spending.
* *Justification*: Many people enjoys the convenience of credit cards that allows them to purchase things
on credit and making payment at the end of the month.
In addition, most credit cards also have benefits such as reward points or rebates.
This feature will allow users to track and manage their credit card expenditures on each of their cards.
* *Highlights*: In line with real credit cards, users will have to abide by their monthly card limit
when adding expenditures. When a particular card has reached its monthly limit, the user will no longer be able to
add any expenditures to the card for that particular month.
* *Credits*: Collaborated with <<mong-nus#,Mong Zheng Wei>> to implement the `add` and `list`
card expenditures function.

==== Features Implemented: Ability to Manage Credit Card Bills

* *What it does*: Each `card` is able to `add` and `delete` credit card bill payment to their savings account,
so that users can keep track of their monthly credit card bill in their savings account expenditures.
* *Justification*: At the end of every month, users are expected to pay their credit card bills.
Thus, this feature will allow users to keep track of their monthly credit card bills and
rebates in their savings account.
* *Highlights*: When making a credit card bill payment, the credit card rebates will automatically
be deposited back to the user's savings account to reflect the rebates earned for the particular month.
* *Credits*: Collaborated with <<briantkm#,Tan Kian Ming Brian>> to move the credit card transactions
into `bankexpenditure` and `deposit`. I had to edit, write additional, and use some of his methods
in order to integrate my credit card bill expenditures with his bank expenditures.

=== Code Contributions
[https://nuscs2113-ay1920s1.github.io/dashboard/#=undefined&search=TerenceTanWT[RepoSense]],
[link:{repoURL}/commits?author=TerenceTanWT[Commits]],
 [link:{repoURL}/pulls?q=author%3ATerenceTanWT[Pull Requests]]

=== Other Contributions

==== Project Management

* Managed the team's issue tracker to ensure that issues are closed within deadlines.
* Helped schedule, review, and merge various Pull Requests (PRs) to minimize merge conflicts and regressions.
* Organised and coordinated team meetings.

==== Additional Codes

* Design and wrote the initial Parser class (ParseCommand, ParseType, ParseRawData) with contributions from
everyone (
link:https://github.com/AY1920S1-CS2113T-W17-3/main/blob/master/docs/team/briantkm.adoc[Tan Kian Ming Brian],
link:https://github.com/AY1920S1-CS2113T-W17-3/main/blob/master/docs/team/mong-nus.adoc[Mong Zheng Wei],
link:https://github.com/AY1920S1-CS2113T-W17-3/main/blob/master/docs/team/shamussy.adoc[Shamus Neo Zhi Kai], and
link:https://github.com/AY1920S1-CS2113T-W17-3/main/blob/master/docs/team/valerietyj.adoc[Valerie Tan Yi Jia]
). These Parser classes are used by all commands to help parse keywords and parameters from a user command,
regardless of the position of the parameters. (link:{repoURL}/pull/60[#66])

==== Team Contributions

* Designed and implemented the abstract class `bank`, `parser`, `command`, and `transaction` which serve as the code
base of the project with everyone (
link:https://github.com/AY1920S1-CS2113T-W17-3/main/blob/master/docs/team/briantkm.adoc[Tan Kian Ming Brian],
link:https://github.com/AY1920S1-CS2113T-W17-3/main/blob/master/docs/team/mong-nus.adoc[Mong Zheng Wei],
link:https://github.com/AY1920S1-CS2113T-W17-3/main/blob/master/docs/team/shamussy.adoc[Shamus Neo Zhi Kai], and
link:https://github.com/AY1920S1-CS2113T-W17-3/main/blob/master/docs/team/valerietyj.adoc[Valerie Tan Yi Jia]
).

* Implemented logging for *OwlMoney* while collaborating with everyone (
link:https://github.com/AY1920S1-CS2113T-W17-3/main/blob/master/docs/team/briantkm.adoc[Tan Kian Ming Brian],
link:https://github.com/AY1920S1-CS2113T-W17-3/main/blob/master/docs/team/mong-nus.adoc[Mong Zheng Wei],
link:https://github.com/AY1920S1-CS2113T-W17-3/main/blob/master/docs/team/shamussy.adoc[Shamus Neo Zhi Kai], and
link:https://github.com/AY1920S1-CS2113T-W17-3/main/blob/master/docs/team/valerietyj.adoc[Valerie Tan Yi Jia]
).

* Contributed and wrote the sections for all parts of
link:https://github.com/AY1920S1-CS2113T-W17-3/main/blob/master/docs/UserGuide.adoc#Features[Features] and
link:https://github.com/AY1920S1-CS2113T-W17-3/main/blob/master/docs/UserGuide.adoc#command-summary[Command Summary]
in the User Guide (UG) while collaborating with everyone (
link:https://github.com/AY1920S1-CS2113T-W17-3/main/blob/master/docs/team/briantkm.adoc[Tan Kian Ming Brian],
link:https://github.com/AY1920S1-CS2113T-W17-3/main/blob/master/docs/team/mong-nus.adoc[Mong Zheng Wei],
link:https://github.com/AY1920S1-CS2113T-W17-3/main/blob/master/docs/team/shamussy.adoc[Shamus Neo Zhi Kai], and
link:https://github.com/AY1920S1-CS2113T-W17-3/main/blob/master/docs/team/valerietyj.adoc[Valerie Tan Yi Jia]
).

* Contributed and wrote the sections for all part of
link:++https://github.com/AY1920S1-CS2113T-W17-3/main/blob/master/docs/DeveloperGuide.adoc#design++[Design],
link:++https://github.com/AY1920S1-CS2113T-W17-3/main/blob/master/docs/DeveloperGuide
.adoc#implementation++[Implementation],
link:++https://github.com/AY1920S1-CS2113T-W17-3/main/blob/master/docs/DeveloperGuide.adoc#product-scope++[Product
Scope],
link:++https://github.com/AY1920S1-CS2113T-W17-3/main/blob/master/docs/DeveloperGuide.adoc#user-stories++[User Stories],
link:++https://github.com/AY1920S1-CS2113T-W17-3/main/blob/master/docs/DeveloperGuide.adoc#use-cases++[Use Cases], and
link:++https://github.com/AY1920S1-CS2113T-W17-3/main/blob/master/docs/DeveloperGuide.adoc#instructions-
for-manual-testing++[Instructions for
Manual Testing] in the Developer Guide (DG) while collaborating with everyone (
link:https://github.com/AY1920S1-CS2113T-W17-3/main/blob/master/docs/team/briantkm.adoc[Tan Kian Ming Brian],
link:https://github.com/AY1920S1-CS2113T-W17-3/main/blob/master/docs/team/mong-nus.adoc[Mong Zheng Wei],
link:https://github.com/AY1920S1-CS2113T-W17-3/main/blob/master/docs/team/shamussy.adoc[Shamus Neo Zhi Kai], and
link:https://github.com/AY1920S1-CS2113T-W17-3/main/blob/master/docs/team/valerietyj.adoc[Valerie Tan Yi Jia]
).

* Helped team members debug issues related to parser class and also performed regression testing of their codes.

==== Documentation
* Wrote the initial set of User Stories and Use Cases for the Developer Guide.
* Vetted and resolved User Guide and Developer Guide errors.

==== Community
* Helped another team to resolve issues with their program on the forum
(link:https://github.com/nusCS2113-AY1920S1/forum/issues/95[#95]).
* Reported bugs in another team's project, link:https://github.com/AY1920S1-CS2113T-W13-3/main[SGTravel] (
 link:https://github.com/AY1920S1-CS2113T-W13-3/main/issues/176[#176],
 link:https://github.com/AY1920S1-CS2113T-W13-3/main/issues/177[#177],
 link:https://github.com/AY1920S1-CS2113T-W13-3/main/issues/178[#178],
 link:https://github.com/AY1920S1-CS2113T-W13-3/main/issues/179[#179],
 link:https://github.com/AY1920S1-CS2113T-W13-3/main/issues/180[#180],
 link:https://github.com/AY1920S1-CS2113T-W13-3/main/issues/181[#181]
).
* Reviewed, reported bugs, and provided constructive feedback to another team's
(link:https://github.com/AY1920S1-CS2113T-W17-4/main[OOF]) User Guide and Developer Guide.


== Contributions to the User Guide

I wrote various sections of the user guide, including sections related to the `card` function. The following contains
an excerpt from our *OwlMoney*
link:https://github.com/AY1920S1-CS2113T-W17-3/main/blob/master/docs/UserGuide.adoc[User Guide],
showing additions that I have made for the `card` function.

=== Credit Card Management
In this section, you'll be introduced to commands and parameters that help you to manage your credit cards and
expenditures associated with it in *OwlMoney*.

Below is a list of command parameters that you can expect to use for the commands in this section.
[cols="18%,37%,45%"]
|======
|*Parameter*| *Description* | *Acceptable Range of Values*
| `CARD_NAME`
| Indicates the name of the credit card.

(e.g. POBB Everyday Card)

| `CARD_NAME` should contain alphabetic characters, numeric characters, and spaces only.

`CARD_NAME` is case-sensitive.

Take note that there is a maximum of *30* character limit.

| `ACCOUNT_NAME`
| Indicates the name of the savings bank account.

(e.g. JunBank Savings Account)

| `ACCOUNT_NAME` should contain alphabetic characters, numeric characters, and spaces only.

`ACCOUNT_NAME` is case-sensitive.

Take note that there is a maximum of *30* character limit.

| `YEARMONTH`
| Indicates the month and year the expenditure was made.

(e.g. 10/2019)

| `YEARMONTH` should be in *MM/YYYY* format and cannot be ahead of the current month.
|======

==== Credit Card Bill Management Commands: `/cardbill`

===== 4.1.1.1. Adding Credit Card Bill to Savings Account `/add /cardbill`

include::../UserGuide.adoc[tag=AddCreditCardBill_Command]

===== 4.1.1.2. Deleting Credit Card Bill from Savings Account `/delete /cardbill`

include::../UserGuide.adoc[tag=DeleteCreditCardBill_Command]

== Contributions to the Developer Guide

I wrote various sections of the developer guide, including sections related to the `card` function. The following
contains an excerpt from our *OwlMoney*
link:https://github.com/AY1920S1-CS2113T-W17-3/main/blob/master/docs/DeveloperGuide.adoc[Developer Guide]
    , showing additions that I have made for the `card` function.

=== Card Command Class Diagram

include::../DeveloperGuide.adoc[tag=CardCommand_ClassDiagram]

=== Delete Card Command Sequence Diagram

include::../DeveloperGuide.adoc[tag=DeleteCreditCard_SequenceDiagram]
