:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets
:repoURL: https://github.com/AY1920S1-CS2113T-W17-3/main
:ArchDukeURL: https://github.com/AY1920S1-CS2113-T13-1/main
:pedURL: https://github.com/valerietyj/ped/issues
:experimental:

== *Valerie Tan* - Project Portfolio for OwlMoney

Hello I am Valerie, a Year 2 Undergraduate pursuing Information Security in the National University of Singapore (NUS).

This portfolio aims to provide a detailed outline of my contributions during the development of our group's
application, *OwlMoney*.


We are a team of five, led by<<shamussy#,Shamus Neo Zhi Kai>> and comprises of <<briantkm#,Brian Tan Kian Ming>>,
<<mong-nus#,Mong Zheng Wei>>, <<terencetan#, Terence Tan Wee Theng>> and <<valerietyj#,myself>>.

=== About the project
[.underline]*OwlMoney* is a finance tracker and investment management application, specially created and developed
for our Software Engineering and Object-Oriented Project, focused on designing and
implementing a command-line based personal assistant.

We decided to name it [.underline]*OwlMoney* as it equipped with the mission to help Undergraduates / Fresh Graduates
*_manage and track their finances efficiently, effectively, and more conveniently._*

My main responsibility when developing this application was to implement and
design the code for `goals` feature. The following sections will go in-depth on `goals` feature and
showcase my team contribution as one of *OwlMoney's* Developer for the past 8-weeks.

=== Summary of Contributions
Here are the links as a reference to my implementation for `goals` Features:

* {repoURL}/commits?author=valeriety[Commits]

* {repoURL}/pulls?q=is%3Apr+is%3Aclosed+author%3Avalerietyj[Pull Requests]

* https://nuscs2113-ay1920s1.github.io/dashboard/#search=valerietyj[RepoSense
Code Contribution Dashboard]

==== Enhancement added
`goals` features functionality for users to `add`, `delete`, `edit` and `list` financial goals.
OwlMoney users have a choice of linking their saving accounts to the goals added to better facilitate tracking of
their goals progress.

What `add goals` does::
The `add` goals command allows user to enter a new goal. The user may choose to link their savings account by specifying
`/from` parameter with a valid savings account. User also has the option to specify their goals deadline using `in`
(days) or `from` (date) parameter.

What `edit goals` does::
The `edit` goals command enables users to change any valid input parameter if there are any changes to the goals they
have added. In addition, if user has not linked any savings account, they can also do it here by
specifying `/from` parameter.

What `delete goals` does::
In the event when a goal is no longer relevant, the `delete` goals command deletes the specified goals.

What `list goals` does::
Listing of all financial goals user has set.

Justification of features added::
Our target users for OwlMoney are Fresh Graduates / Undergraduates, these features stated above were necessary to
model real-life setting of having goals and target, providing users the flexibility whilst achieving their target goals.

Highlights::
`goals` works well with future implementations and enhancement for OwlMoney such as linking to other accounts or
unlocking new achievements. `goals` are meant to motivate users to save and properly manage their finances for any
financial goals that they wish to achieve. Each goals have a deadline set and users goals will be marked automatically
when their savings account reach their target amount.

Credits::
Collaborated with <<briantkm#, Brian Tan Kian Ming>> on the linking of user's goal to savings account.

==== Other contributions

* Project Management:
** Assist in coordinating team meetings and documenting meeting notes.
* Documentation:
** As a team, we worked together on the User Guide and Developer Guide,
ensuring they are bug-free and reader-friendliness.
** As a team, we worked closely together in the initial stage of OwlMoney's development to
identify suitable target users, user stories and use cases.
* Team contribution:
** Reviewed Pull Requests
** Fixed bugs and errors on Developer Guide, User Guide as per Tutor's advice
** Fixed code bugs and implemented ability to edit profile.
* Community:
** Reported critical and helpful bugs in another team's project, link:{ArchDukeURL}[ArchDuke] +
(Full issues reported can be found {pedURL}[here] and some examples are: {ArchDukeURL}/issues/296[#296], {ArchDukeURL}/issues/297[#297],
{ArchDukeURL}/issues/298[#296], {ArchDukeURL}/issues/306[#306], {ArchDukeURL}/issues/307[#307],
{ArchDukeURL}/issues/308[#308])



=== Contributions to User Guide
|===
|_The following areas some helpful information specific to guide end-users with `goals` feature on
OwlMoney's application._
|===

include::../UserGuide.adoc[tag=goals]

=== Contributions to Developer Guide
|===
|_Listed below are some elaborations on the implementation of `goals` features, which aims
to provide experienced end-users a walk-through on the design implementation and frameworks of OwlMoney._
|===

==== Goals Package Class Diagram
include::../DeveloperGuide.adoc[tag=goals_class]

include::../DeveloperGuide.adoc[tags=goals_sequence]

==== Use Cases for implementation of goals
include::../DeveloperGuide.adoc[tag=goals_usecase]
