= Lee Zhen Yu - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Degrees Mod

---

== Overview

Degrees mod is a desktop application used for managing degrees, modules and course events. The user interacts with it using a CLI, and it has a GUI created with JavaFX. This program was based on the Duke task manager before it was expanded to include degree, modules and course management.

== Summary of contributions

* *Major enhancement*: added *the ability to undo/redo previous commands*
** What it does: allows the user to undo all previous commands one at a time. Preceding undo commands can be reversed by using the redo command. Also allows for redoing the undone the command.
** Justification: This feature improves the product significantly because a user can make mistakes in commands and the app should provide a convenient way to rectify them.
** Highlights: This enhancement affects existing commands and commands to be added in future. It required an in-depth analysis of design alternatives. The implementation too was challenging as it required changes to existing commands.
** Credits: Kane Quah (Memento-Command pattern requires the command classes to be implemented first, of which he is in charge of)

* *Minor enhancement*: Added an autosuggest feature (using a third-party library Controlsfx) that can learn user inputs (me).

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
*** Managed releases `v1.1` - `v1.3` (3 releases) on GitHub
** Enhancements to existing features:
*** Wrote tests for the original Duke task manager, before duke was expanded.
*** Undo/redo command usage
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com[#14]
** Community:
*** PRs reviewed:
*** Reported bugs and suggestions for other teams in the class:
** Tools:
*** Integrated a third party library (ControlsFX) to the project 
*** Integrated Gradle into the project
*** Integrated JavaFX into the project

_{you can add/remove categories in the list above}_

_{Below has not been changed yet}_

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=delete]

include::../UserGuide.adoc[tag=dataencryption]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=undoredo]

include::../DeveloperGuide.adoc[tag=dataencryption]

_{Optionally, you may include other projects in your portfolio.}_
