@startuml
!include style.puml

Package " "<<Rectangle>>{
    Class UI UI_COLOR
    Class Profile LOGIC_COLOR
    Class Storage STORAGE_COLOR
    Class Model MODEL_COLOR
    Class Main MODEL_COLOR_T1
    Class Commons LOGIC_COLOR_T2
    Class Logs UI_COLOR_T2

}
Class User MODEL_COLOR_T2
Class File UI_COLOR_T1

User --> UI
Storage -> File

@enduml