= MisterMusik - Developer Guide
:site-section: UserGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/AY1920S1-CS2113T-F11-4/main

By: `Team CS2113T-F11-4`      Since: `Aug 2019`      Licence: `MIT`



== Target User Profile
<NAME_OF_PROJECT> is a scheduler program created for serious music students pursuing a professional music career as a western classical music performer.
The program is designed to automate and streamline most of the process in scheduling and organisation of materials, allowing the students to focus more on the important aspects of their education.

== User Stories
. As a busy music student with multiple classes, I want to be able to track my practice sessions so that I won’t miss any trainings.
. As a music student with a heavy workload, I want to be able to track my upcoming recitals and their details so I can prioritize which pieces/what techniques to practice and focus on.
. As a music student with a tendency to procrastinate in things I need to do, I want to be constantly reminded of my examination dates so i do not wait till the last minute to prepare for them.
. As a student who wants to maximize my efficiency in practice sessions (performer), I want to be able to rate and comment on the efficiency of my practice sessions and be able to review them to make sure that I learn and improve faster.
. As a student who wants to categorize what I learn in classes, I want to be able to take notes and organize them into different categories, so that I can easily review it anytime.
. As a student who wishes to be aware of his upcoming events, I wish to be able to view my schedule within a selected number of weeks so that I can plan for it.

== Use cases

=== Entering a practice schedule into the system
. User enters a command to add a practice followed by a date, and the details of the intended practice. 
. System prompts user about whether or not he wishes to make this a recurring practice (e.g every Tuesday).
. User responds to the prompt accordingly.
. System adds practice session to a stored list and saves it to a file on the user’s hard drive.

=== Entering the details of a recital into the system
. User choose to enter a recital.
. System requires details of the recital.
. User enters date, time, venue, the pieces to be performed, and a description if needed.
. System adds recital to a stored list and saves it to a file on the user’s hard drive.

Extension 3.1: System detects there is a clash with a concert/practice session at step 3.
3.1.1.  System generates warnings and ask user to delete the corresponding entry and forgo that event.
3.1.2.  User responds to the warning, deleting or rescheduling one of the events in a clash if necessary.
3.1.3. System updates the stored list and saves it to the file on the user’s hard disk.

Extension 3.2: System detects a clash with another recital or an examination at step 3.
3.2.1.  System generates warnings and ask user to reschedule and re-enter one of the events that clash.
3.2.2.  User responds to the warning, rescheduling and re-entering one of the events in a clash.
3.2.3. System updates the stored list and saves it to the file on the user’s hard disk.
Use case ends

=== Making notes    
. User chooses to enter a command to start a note-taking/viewing session
. System shows the user a list of categories (directories) of notes that have been made previously and prompts the user to enter one or create a new file.
. User makes a choice to enter a category directory or create a new one.
. System shows the user a list of files containing notes, each file is named with the corresponding date, and a description of the file decided by the user. System also prompts the user if he wants to create a new file or enter an existing one.
. User selects a file to enter or chooses to create a new file.
. System opens the file for viewing and editing. The user can choose to make changes to the notes using commands: delete, add and move to delete, add or move notes around the file accordingly.

Extension 3.1: System detects there is no category file that user commands to edit on
3.1.1. System generates warnings and ask the user whether or not he wishes to add a new category and take notes in
3.1.2. User responds to the warning, and choose to add a new category
3.1.3. System adds and opens a new category file with the name given by user

=== Viewing upcoming events
. User enters command `list` followed by an integer N representing the number of weeks in advance he would like to view his schedule.
. System responds by showing the user a list of events in the next N weeks.
. User may enter a command to remove specific tasks from the list, to have a cleaner viewing experience.

Extension 3.1: System can remove types of events from list at user’s command
3.1.1. User can enter commands `remove examinations` for example, to remove the examinations from the display.
3.1.2. System responds accordingly, removing the type of event from the list and altering the list of events displayed.

Extension: 3.2. System can allow the user to only view a specific type of event.
3.2.1. User can also enter commands `show examinations` for example, to only show examinations in the list of events.
3.2.2. System will respond accordingly, displaying only type of event that the user specified.

=== Entering the examination details
. User enters command `examination`, together with a description of the examination, along with the date, time, venue and any other notes in a given format.
. The system adds the examination to the list of events.

Extension 1.1: System detects a clash with the examination date entered and another event.
1.1.1. System will prompt the user to reschedule the event of lower priority. (examinations and recitals are of highest priority, followed by concerts and then practices). If the clash is with an event of the same priority, the user is prompted to choose which one to reschedule(simple y/n response).
1.1.2. User reschedules the specified event by entering a date and time. The user is also able to delete an event with the delete command to free up the schedule if he wishes to do so.
1.1.3. System once again checks for clashes and repeats the process of rescheduling if necessary.

=== Rate and comment on the efficiency of practice sessions 
. User enters a command to rate a practice session
. System brings up a list of practice sessions that the user has already completed
. User selects a practice session
. System displays the details of the selected practice session and prompts the user to select an efficiency rating along with any additional notes
. User rates the efficiency of the practice session and takes down any notes or feedback from their instructor
. System saves the entry onto the hard disk

=== Edit descriptions of any existing event
. User enters a command to edit the description of an event
. System edits corresponding description and prompts user of success

Extension 1: System detects a clash of incorrect format entered by the user.
1.1. System will prompt the user that the entered format was incorrect.

Extensions 4.1: Selected practice session has already been rated.
4.1.1. If the selected practice session has already been rated, the system notifies the user and allows them to edit.
4.1.2. The user edits the rating and notes of the practice session accordingly
4.1.3. System saves the changes onto the hard disk

Extensions 5.1: User inputs an invalid rating.
5.1.1. System displays an error message to inform the user of the correct rating format until a valid input is detected.

== Non-functional requirements
. System should work on windows and linux.
. System response within 1 second.
. Usable by non tech-savvy individuals.
. Clear user prompts 
. Visually pleasing display

== Design

=== Overall Architecture

There are three main components in the overall architecture of the application.

`Duke` class: contains the `main()` class of the application.
* Upon startup: a Welcome Message is printed (see section under Ui) data is loaded from the memory storage to the system.
* Upon exit (when the user enters 'bye'): a Goodbye Message is printed (see section under Ui). 

`Events` Package: contains classes pertaining to the events.

`UserElements` Package: contains classes pertaining to I/O and the interaction between user and system.

== Instructions for Manual Testing

=== Launch and Shutdown
. Initial Launch
.. Open Duke.java in src.
.. Run the file +
   Expected: The Welcome Message is printed in stdout and the system requests for an input.
   
. Shutdown
.. Key in `bye` as input. +
   Expected: The Goodbye Message ('Bye. Hope to see you again soon!') is printed in stdout and the process exits.

=== Obtain the list of items currently in stored in the system
. Key in `list` as input +
  Expected: A list of items is printed in stdout.


=== Add a Task
. Add Todo +
   Key in `todo tdtask /01-01-2011 0100` +
   Expected: Output should be +
   Got it. I've added this task: +
   [x][T] tdtask  BY: Sat, 01 Jan 2011, 01:00 +
   Now you have <previous number of items + 1> items in the list. 

. Add Exam +
   Key in `exam Music Rudiments /08-08-2018 0800 0900` +
   Expected: Output should be +
   Got it. I've added this task: +
   [x][E] Music Rudiments  START: Wed, 08 Aug 2018, 08:00 END: Wed, 08 Aug 2018, 09:00 +
   Now you have <previous number of items + 1> tasks in the list.
   
. Add Practice session +
   Key in `practice morningprac /07-08-2018 0800 0900` +
   Expected: Output should be +
   Got it. I've added this event: +
   [x][P] morningprac  START: Tue, 07 Aug 2018, 08:00 END: Tue, 07 Aug 2018, 09:00 +
   Now you have <previous number of items + 1> tasks in the list.
   
. Add Concert +
   Key in `concert Noon Concert /06-06-2016 1200 1400` +
   Expected: Output should be +
   Got it. I've added this task: +
   [x][C] Noon Concert  START: Mon, 06 Jun 2016, 12:00 END: Mon, 06 Jun 2016, 14:00 +
   Now you have <previous number of items + 1> tasks in the list.

. Add Recital +
   Key in `recital Evening Recital /07-07-2017 1900 2100` +
   Expected: Output should be +
   Got it. I've added this task: +
   [x][R] Evening Recital  START: Fri, 07 Jul 2017, 19:00 END: Fri, 07 Jul 2017, 21:00 +
   Now you have <previous number of items + 1> tasks in the list.

. Add Lesson +
   Key in `lesson Class /09-09-2019 0900 0100` +
   Expected: Output should be +
   Got it. I’ve added this task: +
   [x][L] Class  START: Mon, 09 Sep 2019, 09:00 END: Mon, 09 Sep 2019, 01:00 +
   Now you have <previous number of items + 1> tasks in the list.

=== Set a Task as done
Key in `done 1` +
Expected: Prints a message that the first task on the list has been marked as done.

=== Find tasks that contains a certain keyword or key phrase
Key in `find <key>`, where `<key>` is the keyword or key phrase +
Expected: Prints a list of tasks that contains the `<key>`.

=== Get reminder
Key in `reminder` +
Expected: Prints a list of tasks to be completed in the next three days.

=== View all tasks in a certain day
Key in view `<date>`, where `<date>` has the format dd/MM/yyyy. +
Expected: Prints a list of tasks that occurs on the given `<date>`.

=== Edit description of an event
Key in `<edit> <event index>/<new description>`.+
Expected: Prints the success of editing event of index `<event index>`.
  
