= Ducats  - Developer Guide
:site-section: DeveloperGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:warning-caption: :warning:
endif::[]
:repoURL: https://github.com/AY1920S1-CS2113T-F09-4/main

By: `AY1920S1-CS2113T-F09-4` Since: `Aug 2019`

== Introduction

Amateur musicians find it difficult to start with music theory as they are unable to see their work being shown in a
practical method and quit. Our application allows amateur musicians to learn music theory and apply their learning by
creating songs.

This application allows you to learn what you have learnt through:

* Ease of adding, deleting components to the songs

** The user is able to add, delete, edit and view components such as bars, notes, groups to the song so that they learn
the  basics of creating a song.

* Displaying the musical notes as sheets so that they can practice it in their favorite instrument.

** In the end once the user uses the application, they will be able to take away a pdf of their musical notes and also
print it in command line.

This document describes the coding style and the architecture of the Ducats project built by Team CS2113T F09-4.
This document is intended for our major release v1.3.

The documentation will allow any developer to start to work on the project by first learning about the system
architecture, then the implementation and lastly on how to document the code that is written.


== Setting up

To set up the program successfully, at minimum, JDK 11 is needed. IntelliJ Ultimate is the preferred IDE due to its ease in building the project. The steps to set up the project in your computer are as follows:

1. Fork the link:https://github.com/AY1920S1-CS2113T-F09-4/main[Github repository] and clone the fork to your computer.
2. Open Intellij (If you are not on the welcome screen, close the current project by navigating to *File* > *Close Project*.
3. Setup the correct JDK version:
.. Click *Configure* > *Structure* for new projects.
.. Under *Project Settings* click on *Project*.
.. Under *Project SDK* click *New* and point it to JDK 11 path.
.. Click *OK* to save the configuration.
4. Run the Project by editing the run configuration to point to
Ducats.java as the main class.

== Design

This section describes the design of Ducats, starting with the overall architecture, and then proceeding to the a more detailed view of the major components.

=== Overall Architecture

Ducats is based on the n-tier architecture design, with higher level tiers depending on the resources provided by the lower level tiers. The diagram below showcases the high-level architecture of Ducats:

<insert high level archi diagram here>


=== UI

This layer consists of the `UI` Class which is in charge of printing the output to the command line in a specific format. This was chosen instead of printing the output from every individual class as we opted to do abstraction to make it simpler when adding new features. This class also receives messages from users and pass it to parser layer, which decides which class to be called.

=== Parser and Commands

=== SongList

=== Storage and StorageParser

The Storage layer, implemented by the `Storage` class, is responsible for Ducats' interaction with persistent storage of the SongList, which is in the form of a directory called *data* containing `.txt` files that each contain the full data for one Song.

The StorageParser layer's purpose is to parse the data found within the persistent storage, as well as to convert the data found within the SongList to a human-readable, storage-friendly form. This layer is implemented by the `StorageParser` class.

== Implementation

This section describes in detail the implementation of the various features, as well as how the different components interact with each other.

=== Command Parsing and Execution

Since Ducats is a CLI app, it works by reading user input and carrying out the command the user wants it to execute. In line with this objective, the different components of Ducats have been designed to interact in the sequence as depicted by Figure X.

<insert Sequence Diagram of Ducats here>

It can be seen that, for all commands, the `Parser` class is used to determine what type of command the user intends for the program to execute. In accordance with this, a new `Command` object is created and then the `execute()` method of the Command is called, modifying the `SongList` and `Storage`, and returning a String to be displayed on the console through the `UI` class.

A slightly different schedule is used for the Metronome functionality, which will be discussed in further detail in Section 4.5.

=== Basic CRUD

CRUD stands for "Create, Read, Update, Delete", and this framework serves as the most essential part of any data-driven software. In Ducats, basic CRUD functionality is implemented, alongside more sophisticated features such as the ability to Undo and Redo.

==== Creating a Song and Navigation

The creation of a new song is straightforward. In the `new` command, the following attributes of the song to be created will be specified:

* name
* key _[implementation coming in v2.0]_
* time signature _[implementation coming in v2.0]_

While the above data is stored with every song, data adjustments based on, and specific methods that utilize the key and time signature are yet to be implemented.

The created Song object will then be inserted into the SongList object, which contains all the song data of Ducats. Following this, persistent storage will be updated.

In order to enable the modification of certain songs when there are multiple songs without the forced provision of additional parameters by the user, a system of navigation has been implemented, where a song can be "opened" in order for it to be edited, with the first song in the SongList being "opened" by default. "Opening" a song is carried out by the execution of the `OpenCommand`, which changes a variable in the `SongList` object known as the `activeIndex`.

`activeIndex` corresponds to the index of the song that can be edited by the other CRUD functions, and only by modifying this attribute to the appropriate value can songs other than the first one be editable. The overall sequence for the parsing and execution of `OpenCommand` is shown below in Figure X.

<insert sequence diagram specific to OpenCommand>

==== Modifying a Song

=== Advanced CRUD

==== Undo/Redo

==== Overlay

==== Group and Copy

=== Display

=== Metronome

=== Autosuggest

=== Storage

=== Logging

== Adding a New Function

== Testing

[appendix]
== Product Scope

[appendix]
== User Stories

[appendix]
== Use Cases

[appendix]
== Non-Functional Requirements