= Duke 2.0 - Developer Guide
:site-section: DeveloperGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/se-edu/addressbook-level3

By: `Team F10-2`      Since: `August 2019`      Licence: `MIT`

== Setting Up
=== Prerequisites
While Duke 2.0 may work using diffferent versions of Java and with other IDEs, the following are recommended because they have been used for testing:

* Java Development Kit '11'
* Intellij IDE

=== Setup on local Computer


*Manual Import:*

. `Fork` this Repository and `Clone` your remote repository locally to your computer
. Open *Intellij IDE* and set up JDK `11`
.. Click `Configure` > `Project Defaults` > `Project Structure`
.. Click `New...` > `JDK` and select the path of the installed JDK `11`
.. Click `OK`
. Click `Import Project`
. Locate project directory of the cloned repository
. Click `Next`
. Ensure that the `src folder` is checked ✅, and Click `Next` until the `Finish` button appears
. Click the `Finish` button


*Automatic Import using Intellij Check Out:*

. `Fork` this Repository
. Open *Intellij IDE* and set up JDK `11`
.. Click `Configure` > `Project Defaults` > `Project Structure`
.. Click `New...` > `JDK` and select the path of the installed JDK `11`
.. Click `OK`
. Click `Check out from Version Control` > `Git`
. Enter URL of your remote repository > Click `Clone`
. Wait for Intellij to Set Up the project


=== Verifying Setup
. Ensure that Gradle has been imported by running `src/java/javafx/Launcher.java`
. Test out basic Duke 2.0 commands by referring to the User Guide 


== Design


== Implementation

== Testing

== Documentation


== Appendix A: User Stories

User Stories | Priority
-----------------|--------------------
As a student entering NUS, I can view all the details of the course and their modules in one place rather than going through multiple websites so that I can avoid confusion | `High`
As a student applying to NUS, I wish to be able to save a list of possible personal degrees so that I can have a neat way of accessing my list of possible degrees that I have brainstormed to apply for| `High`
As a novice user, I can type a “help” command and receive all the possible commands that DukeJr provides so that I can use the software to its fullest potential | `Medium`
As a student applying to NUS and having specific interests, I want to see if the core modules have any overlap with my interests so that I am better able to decide which engineering disciplines suits me the most  | `Medium`



 




== Appendix B: Use Cases


== Appendix C: Non-Functional Requirements
