= OPTIX - Developer Guide


== Appendix A: Product Scope

*Target user profile*:

* Stakeholders like SISTIC theatre managers who need to track a large number of theatre bookings as well as seat bookings for each show.
* Prefers CLI to mouse input.

*Product*:

* New shows by performers can be added to the list.
* Seats requested by customers for a show can be booked by the theatre manager.
* Program is desgined to price the seats according to the different tiers.
* Revenue earned from a show can be calculated based on the seats booked.

*Value proposition*: manage seats and finances faster than an average GUI-based app.

== Appendix B: User stories

// tag::base-alt[]
[width="90"]
|===
|Priority |As a ... |I want to ... |So that I can ...
|Must-have |new user |see the command summary |refer to them when I forgot how to use the system.

|Must-have |user |book seats for customers and process the transaction |track my sales and avoid double-selling the same seat.

|Must-have |user |add new shows to my current list |record the booking of the venue on a particular date.

|Must-have |user |view all the seats of a particular show |inform my customers on the availability of seats.

|Must-have |user |view the finances from each show |calculate my profit from my business.

|Must-have |user |set the prices of the seats |vary seat prices depending on the popularity of the show.

|Must-have |user |assign seats to customers |check where the customers are sitting.

|Must-have |user |remove a particular show from my listing |free up the cancelled slot to other performers.

|Must-have |freqeunt user |remove shows that have passed from my listing |reduce the quantity of shows in the listing to make it more tidy.

|Must-have |user |set the tiers of the seats |set different prices depending on the popularity of the seats.

|Must-have |user |postpone shows as performers might have encountered unforseen circumstances. | |

Nice-to-have |user |add seats from different shows to a customer's purchase |manage bookings across multiple shows in one transaction. |

Nice-to-have |user |refund seats before a certain date |resell the seats to other customers to increase profit. |

Nice-to-have |user |keep track of payments |track the expenditure by each customer and find out the specific amount for a refund(if applicable). |

Nice-to-have |user |reassign seats booked by customers |fulfill customers'requests to change seats. |

Nice-to-have |user |blacklist customers who break the rules |serve as a deterrent for potential troublemakers and avoid further losses. |

Nice-to-have |user |know the number of available seats in each tier for a particular show |get a rough idea of the number of seats left to sell from each tier. |

Nice-to-have |user |modify the prices of the seats relative to the date of the show |sell off the seats and maximise my profits. |

Nice-to-have |user |keep track of the number of tickets each customer can buy |limit the number of tickets a customer can buy to avoid ticket scalping. |

Nice-to-have |user |customer rewards system |encourage customers to visit more often and thank loyal customers for their patronage. |

Nice-to-have |user |view monthly revenue |compare earnings and make new policies to improve my business. |

Unlikely-to-have |user |put seats on hold |give customers more time to decide if they want to purchase the seats. |

Unlikely-to-have |user |reserve seats for VIPs |allow VIPs to enjoy benefits as a reward for their support. |

|===
// end::base-alt[]


== Appendix C: Use cases

=== Use case: UC01 - Add new shows to list of shows

*Actor*: Theatre manager

*MSS*

----
1. User enters the add command, followed by the name of the show, the date, the cost of the show and the base selling price of the seats.
2. Optix responds by displaying the show that the user has added to the list.
         Use case ends.
----

*Extensions*

----
      1a. Optix detects an error in the details entered.
      1a1. Optix displays an error message that shows the part of the command that was entered  
              incorrectly.
      1a2. Optix requests command from user again.
      1a3. User re-enters details. 
      Steps 1a2-1a3 are repeated until details entered are correct.
      Use case resumes from step 2.
          Use case ends.
----
 

=== Use case: UC02 - Sell seats to buyer

*Actor*: Theatre manager

*MSS*

----
1. User enters the sell command, followed by the name of the show, the date, the name of the buyer and lastly the seats requested by the buyer.
2. Optix responds by displaying the seats bought and the cost of the transaction.
         Use case ends.
----

*Extensions*

----
      1a. Optix detects an error in the details of the show entered.
      1a1. Optix displays an error message that shows the part of the command that was entered  
              incorrectly.
      1a2. Optix requests command from user again.
      1a3. User re-enters details. 
      Steps 1a2-1a3 are repeated until details entered are correct.
      Use case resumes from step 1.

      1b. Optix detects that the seats entered are unavailable. 
      1b1. Optix requests command from user again.
      1b2. User re-enters details.
      Steps 1b1-1b2 are repeated until details entered are correct.
      Use case resumes from step 2.
          Use case ends.
----


=== Use case: UC03 - Delete a single show scheduled on a particular date

*Actor*: Theatre manager

*MSS*

----
1. User enters the delete command followed by the date of the show, and the show name. 
2. Optix responds by displaying the show/shows that have been removed from the list.
         Use case ends.
----

*Extensions*

----
      1a. Optix cannot find the show using the details entered.
      1a1. Optix requests command from user again.
      1a2. User re-enters command. 
      Steps 1a1-1a2 are repeated until shows entered are correct.
      Use case resumes from step 2.
          Use case ends.
----


=== Use case: UC04 - Delete multiple shows by show name

*Actor*: Theatre manager

*MSS*

----
1. User enters the delete command followed by the names of the shows to delete.
2. Optix searches through the list of shows for all shows with the specified name, and deletes them.
3. Optix replies by displaying the show/shows that have been removed from the list.
         Use case ends.
----

*Extensions*

----
      1a. Optix cannot find intended show(s) using the show name(s) specified.
      1a1. Optix replies by listing all the shows the could not be found.
      1a2. User re-enters command. 
      Steps 1a1-1a2 are repeated until shows entered are correct.
      Use case resumes from step 2.
          Use case ends.
----


=== Use case: UC05 - View the entire list of shows

*Actor*: Theatre manager

*MSS*

----
1. User enters the list command.
2. Optix responds by displaying the list of shows available for booking.
         Use case ends.
----


=== Use case: UC06- View available seats of a show

*Actor*: Theatre Manager

*MSS*

----
1. User enters the view command, followed by the show name and date of the show.
2. Optix responds by displaying the available seats of the theatre for the show, by marking reserved seats with a cross, and available seats with a tick.
          Use case ends.
----

*Extensions*

----
      1a. Optix detects that there is no such show on that date. 
      1a1. Optix replies that there is no such show on the date.
      1a2. Optix requests command from user again.
      1a3. User re-enters command. 
      Steps 1a1-1a3 are repeated until the command entered is correct.
      Use case resumes from step 2.
          Use case ends.
----


=== Use Case: UC07 - Refund ticket for seat

*Actor*: Theatre manager

*MSS*

----
1. User enters the refund command, followed by show name, show date, and seat number.
2. Optix responds by querying if the ticket for the seat was purchased. If it is, then the seat is marked as available again.
3. Optix updates the finances from the refund. 
4. Optix replies with a success confirmation.
          Use case ends.
----

*Extensions*

----
      1a. Optix detects that the show does not exist
      1a1. Optix replies that there is no such show.
      1a2. Optix requests command from user again.
      1a3. User re-enters command, with the correct show name.
      Steps 1a1-1a3 is repeated until the command entered is valid.
      Use case resumes from step 3.
          Use case ends.

      2a. Optix detects that the seat was not purchased.
      2a1. Optix replies that the request to refund this seat is invalid.
      2a2. Optix requests command from user again.
      2a3. User re-enters command, with a correct seat number.
      Steps 2a1-2a3 is repeated until the command entered is valid.
      Use case resumes from step 3.
          Use case ends.
----


=== Use case: UC08- Tutorial/ Help Command

*Actor*: Theatre Manager

*MSS*

----
1. User enters the help command.
2. Optix responds by displaying all available commands and their usage.
----



=== Use case: UC09 - Postpone shows to a later date

*Actor*: Theatre manager

*MSS*:

----
1. User enters the postpone command, followed by the name of the show, the current-date of the show to postpone and the new-date.
2. Optix responds by displaying the new-date for the show.
         Use case ends.
----

*Extensions*:

----
      1a. Optix detects an error in the details entered.      
      1a1. Optix informs the user that the show has passed.      
      1a2. Optix requests command from user again.
      1a3. User re-enters command. 
      Steps 1a1-1a3 are repeated until the command entered is correct.
      Use case resumes from step 2.
          Use case ends.

      1b. Optix detects that  there is no show of the given input in the list.
      1b1. Optix informs the user that the show does not exist.
      1b2. Optix requests command from user again.
      1b3. User re-enters command. 
      Steps 1b1-1b3 are repeated until the command entered is correct.
      Use case resumes from step 2.
          Use case ends.
----


== Appendix D: Functional Requirements

* Command to add shows
* Command to Sell Tickets to audience.
* Command to delete a particular show. 
* Command to delete multiple shows (by showName).
* Command to list all shows before date of showing. (Query for booking and check seat availability)
* Command to list specific show to get date of showing (To check when the show is happening and check seat availability)
* Command to refund ticket for the show.
* Tutorial/ Help function
* Command to postpone particular show to an empty slot


== Appendix E: Non-functional Requirements

* Should work on any OS as long as it has Java 11 or above installed.
* The list should be able to hold at least 100 shows without reduction in performance.
* The system should be usable by a novice who has never booked theatres/ theatre seats before. I.e. the commands should be intuitive for any user.
* Parser to parse user input
* Command class to execute add/ delete/ list tasks
* UI class to format output 
