= JavaCake - Developer Guide
:site-section: DeveloperGuide
:toc:
:toc-title:
:toclevels: 2
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:warning-caption: :warning:
endif::[]
:repoURL: https://github.com/AY1920S1-CS2113T-W13-2/main

== Introduction

Purpose

This document specifies architecture and software design decisions for the educational app, JavaCake. The intended audience of this document is the developers, designers, and software testers of JavaCake. 

Design Goals

*Target user profile*:

* Has a need to gain a basic grasp of Java
* Prefers desktop apps over mobile
* Can type quickly
* Prefers typing over mouse input
* Is reasonably comfortable using Command Line Interface (CLI) apps
* Is goal-driven (likes setting goals for themselves)

Value proposition:
Managing the learning of Java and managing the learning progress through a desktop app which is CLI-based.
Developing JavaCake poses a unique software development situation. The developers work closely to ensure both technical and non-technical requirements are met in the 34development process. The design of JavaCake takes into consideration various factors such as user-friendliness and relevance.


== Setting up

Refer to the guide <<UserGuide#, here>>.

== Design


== Implementation

== Documentation

Refer to the guide <<Documentation#, here>>.

== Testing

Refer to the guide <<Testing#, here>>.

== Dev Ops

Refer to the guide <<DevOps#, here>>.

[appendix]
== Product Scope

*Target user profile*:

* has a need to manage a significant number of contacts
* prefer desktop apps over other types
* can type fast
* prefers typing over mouse input
* is reasonably comfortable using CLI apps

*Value proposition*: manage contacts faster than a typical mouse/GUI driven app

[appendix]
== User Stories

Priorities: High (must have) - `* * \*`, Medium (nice to have) - `* \*`, Low (unlikely to have) - `*`

[width="59%",cols="22%,<23%,<25%,<30%",options="header",]
|=======================================================================
|Priority |As a ... |I want to ... |So that I can...
|`* * *` |new user |see usage instructions |refer to instructions when I forget how to use the App

|`* * *` |user |add a new person |

|`* * *` |user |delete a person |remove entries that I no longer need

|`* * *` |user |find a person by name |locate details of persons without having to go through the entire list

|`* *` |user |hide <<private-contact-detail,private contact details>> by default |minimize chance of someone else seeing them by accident

|`*` |user with many persons in the address book |sort persons by name |locate a person easily
|=======================================================================

_{More to be added}_

[appendix]
== Use Cases

(For all use cases below, the *System* is the `Cake` and the *Actor* is the `user`, unless specified otherwise)

[discrete]
=== Use case: Find topics

*MSS*

1. User requests to list topics
2. Cake shows topics (in format 1. X\n 2. Y\n...)
3. User types the topic number e.g. `1`
4. Cake shows sub-topics within that topic (in format 1. X\n 2. Y\n...)
5. User types the sub-topic number e.g. `1`
6. Cake shows the content in the sub-topic
+
Use case ends.

*Extensions*

[none]
* 3a. If user types in `1.1`, user can immediately jump to sub-topic content
+
[none]
** 3a1. If no sub-topic present, Cake shows error message
+
Use case resumes at step 5.

[discrete]
=== Use case: Check progress

*MSS*

1. _User finishes topic/quiz_
2. Cake shows progress bar ( [# # # # _ _ _ _] )
+
Use case ends.

*Extensions*

[none]
* 2a. User types in command to check progress again
+
Use case ends.

[discrete]
=== Use case: Do quiz from sub-topic

*MSS*

1. _User requests for sub-topic list_
2. User selects quiz by typing `quiz` or types in the index of the quiz in the list e.g. `7`
3. Cake launches quiz
4. User answers the questions
+
Use case ends.

*Extensions*

[none]
* 4a. User types invalid input
+
[none]
** 4a1. Cake shows error message
+
Use case resumes at step 2.

[none]
* 4b. User types wrong answer
+
[none]
** 4b1. Cake shows "Wrong Answer" and proceeds to next question.
+
Use case ends

[discrete]
=== Use case: Set deadline for topics/sub-topics to read

*MSS*

1. User requests to list topics
2. Cake shows topics
3. User sets deadline for a topic `deadline 1 /by <DATE/>`
4. Cake shows confirmation message (adds to appended topic header list)
+
Use case ends.

*Extensions*

[none]
* 4a. If user decides to list topics again, deadline is appended to topic header
+
Use case ends.
* 4b. If user launches program again, the deadlines for each topic are shown in most recent deadline order.
+
** 4b1. If user finishes the quiz for that topic, the deadline will be removed from Cake
+
Use case ends.

_{More to be added}_

[appendix]
== Non Functional Requirements

.  Should work on any <<mainstream-os,mainstream OS>> as long as it has Java `11` or above installed.
.  Should be able to hold up to 1000 persons without a noticeable sluggishness in performance for typical usage.
.  A user with above average typing speed for regular English text (i.e. not code, not system admin commands) should be able to accomplish most of the tasks faster using commands than using the mouse.

_{More to be added}_

[appendix]
== Glossary

[[mainstream-os]] Mainstream OS::
Windows, Linux, Unix, OS-X

[[private-contact-detail]] Private contact detail::
A contact detail that is not meant to be shared with others

[appendix]
== Product Survey

*Product Name*

Author: ...

Pros:

* ...
* ...

Cons:

* ...
* ...

[appendix]
== Instructions for Manual Testing

Given below are instructions to test the app manually.

[NOTE]
These instructions only provide a starting point for testers to work on; testers are expected to do more _exploratory_ testing.

=== Launch and Shutdown

. Initial launch

.. Download the jar file and copy into an empty folder
.. Double-click the jar file +
   Expected: Shows the GUI with a set of sample contacts. The window size may not be optimum.

. Saving window preferences

.. Resize the window to an optimum size. Move the window to a different location. Close the window.
.. Re-launch the app by double-clicking the jar file. +
   Expected: The most recent window size and location is retained.

_{ more test cases ... }_

=== Deleting a person

. Deleting a person while all persons are listed

.. Prerequisites: List all persons using the `list` command. Multiple persons in the list.
.. Test case: `delete 1` +
   Expected: First contact is deleted from the list. Details of the deleted contact shown in the status message. Timestamp in the status bar is updated.
.. Test case: `delete 0` +
   Expected: No person is deleted. Error details shown in the status message. Status bar remains the same.
.. Other incorrect delete commands to try: `delete`, `delete x` (where x is larger than the list size) _{give more}_ +
   Expected: Similar to previous.

_{ more test cases ... }_

=== Saving data

. Dealing with missing/corrupted data files

.. _{explain how to simulate a missing/corrupted file and the expected behavior}_

_{ more test cases ... }_
