= Lim Jia Wei - Project Portfolio for ChefDuke
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: ChefDuke - V 1.3

---

== Overview

My team consisting of 4 computer engineering students including myself was tasked with enhancing a basic task manager Duke. We decided to go in the direction of morphing Duke into an application which aims to help private home chefs manage their business. ChefDuke, our enhanced application, keeps track of three main components which are the customer bookings, recipes and inventories of the user. Other than basic storage of components, our application allows the user to deconflict booking schedules, and also update their inventory automatically when a recipe is used so that the inventory list is always up to date. The application has a GUI created with JavaFX and the user interacts with it using a CLI.

== Summary of contributions

* *Major enhancement 1*: added *the ability to add/delete/list ingredients to/from the inventory*

** What it does: Allows the user to add an ingredient into his inventory list, delete an ingredient from his inventory list and list all current ingredients in his inventory. Important details such as the quantity of the ingredients is keep tracked of.
** Justification: This feature allows the user to always have an up to date inventory list which can let them know how much of each ingredient they currently have. Additional information like the expiry date can also be keep tracked of.

** Highlights: This enhancement does the basic storage of inventory components but is a feature which is necessary as a baseline for other existing/future commands and features. The implementation of the Ingredients required some pre-planning on what details are essential as the same ingredient object will also be used in the recipes. 

* *Major enhancement 2*: added *the ability to update the inventory based on recipes/orders used*

** What it does: Allows the user to add an ingredient into his inventory list, delete an ingredient from his inventory list and list all current ingredients in his inventory. Important details such as the quantity of the ingredients is keep tracked of.
** Justification: This feature allows the user to always have an up to date inventory list which can let them know how much of each ingredient they currently have. Additional information like the expiry date can also be keep tracked of.

** Highlights: This enhancement does the basic storage of inventory components but is a feature which is necessary as a baseline for other existing/future commands and features. The implementation of the Ingredients required some pre-planning on what details are essential as the same ingredient object will also be used in the recipes. 

** Credits: _{mention here if you reused any code/ideas from elsewhere or if a third-party library is heavily used in the feature so that a reader can make a more accurate judgement of how much effort went into the feature}_

* *Minor enhancement*: added a history command that allows the user to navigate to previous commands using up/down keys.

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
*** Managed releases `v1.3` - `v1.5rc` (3 releases) on GitHub
** Enhancements to existing features:
*** Updated the GUI color scheme (Pull requests https://github.com[#33], https://github.com[#34])
*** Wrote additional tests for existing features to increase coverage from 88% to 92% (Pull requests https://github.com[#36], https://github.com[#38])
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com[#14]
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com[#12], https://github.com[#32], https://github.com[#19], https://github.com[#42]
*** Contributed to forum discussions (examples:  https://github.com[1], https://github.com[2], https://github.com[3], https://github.com[4])
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com[1], https://github.com[2], https://github.com[3])
*** Some parts of the history feature I added was adopted by several other class mates (https://github.com[1], https://github.com[2])
** Tools:
*** Integrated a third party library (Natty) to the project (https://github.com[#42])
*** Integrated a new Github plugin (CircleCI) to the team repo

_{you can add/remove categories in the list above}_

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=delete]

include::../UserGuide.adoc[tag=dataencryption]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=undoredo]

include::../DeveloperGuide.adoc[tag=dataencryption]


== PROJECT: PowerPointLabs

---

_{Optionally, you may include other projects in your portfolio.}_
