= Khairul Iman - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: ModPlanner

== Overview

ModPlanner is a command line interface application written in Java. It aims to help Computer Engineering students plan their modules throughout their entire university tenure.

This was done in apart to learn the basic concepts of software engineering in a non-trivial project, consisting of about 4KSoC. We chose to morph the existing Duke personal assistant into our ModPlanner application.

== Summary of contributions

* *Feature Enhancement*:
    ** Managed feature support for persistent data storage
    ** Added integration for NUSMODS API Requests, for obtaining NUS module data information
    ** Added integration for Google's GSON library, for efficient JSON data parsing
        *** Implemented framework for processing JSON data returned by NUSMODS API

* *Code contributed*:
    ** {Link to Logger and WebCrawler package}

* *Other contributions*:
    ** Added support for Gradle build automation, to ensure ease of project builds
    ** Added support for TravisCI, for continuous integration
    ** Added support for Coveralls, for efficient tracking of code coverage

* Project management:
    ** Managed releases `mid-v1.1`, `v1.1` and `v1.2.1`
    ** Handled team issue tracking regarding:
        *** Improvements to implemented features
        *** General bug reporting
        *** Patch releases to fix to discovered bugs
* Documentation:
    *** Added UML Diagrams for overall product design in Developer Guide

* Community:
    ** Requested permission to utilize NUSMODS API in the course forum
* Tools:
*** Integrated a third party library (Natty) to the project, for improved date parsing
*** Integrated Github plugins (TravisCI and Coveralls) to the team repository

== Contributions to the User Guide

|===

|===

add image

== Contributions to the Developer Guide

|===

|===

add image


