= RIMS User Guide
:site-section: UserGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images/UserGuide
:stylesDir:
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/AY1920S1-CS2113T-W12-1/main

By: `Team W12-1`      Since: `Aug 2019`      Licence: `MIT`

== Introduction

RIMS (Resource and Inventory Management System) is a *command-line* logistic management system designed to manage an organisation’s facilities and inventory. It takes in user commands to *track the booking and loaning out of an organisation’s resources*. It is designed for logistics managers and executives aspiring to streamline and digitise the accounting  of their inventory. Interested? Jump to the <<Quick Start>> to get started. Enjoy!


== Quick Start

.  Ensure you have Java `11` or above installed in your Computer.
.  Download the latest `rims.jar` link:{repoURL/releases}[here].
.  Copy the file to the folder you want to use as the home folder for your local version of RIMS.
. In your home folder for RIMS, create a directory called `data`, and in the `data` folder, create two text files:
`resources.txt` and `reserves.txt`.
.  Double-click the file to start the app. The user interface should appear in a few seconds.
.  Type the command in the command box and press kbd:[Enter] to execute it. +
e.g. typing *`list`* and pressing kbd:[Enter] will show you a list of all the rooms and items with their status (booked/reserved/available).
.  Some example commands you can try:

* *`list`* : lists all items/rooms and their status (booked/reserved/available)
* **`add`**`/item football /qty 2` : adds 2 footballs to RIMS.
* *`bye`* : exits the app

.  Refer to <<Features, Features>> for details of each command.

[[Features]]
== Features

====
*Command Format*

* The first word of each input string is the *command* or *action* requested by the user.
+
e.g. the word `*return*` in `*return* /room seminar room 1`
* Words in `UPPER_CASE` are the *arguments* to be supplied by the user.
+
e.g. in `return /room *ROOM*`, `*ROOM*` is a parameter which can be used as `return /room *seminar room 1*`.
* Arguments always follow a *parameter*, which is denoted by a phrase starting with a forward slash `/`.
+
e.g. in `deadline */date* _DATE_`, `*/date*` denotes that `_DATE_` is a parameter denoting a date and time, as in `deadline */date* _23/01/2020_`.
* Different commands features different parameters.
* Parameters can be in any order.
+
e.g. if the command specifies `add */item ITEM* _/qty QUANTITY_`, `add _/qty QUANTITY_ */item ITEM*` is also acceptable.

====

=== Adding or Removing Resources

==== Add resource: `add`
Add new item(s)/room available for loan/booking in RIMS.

.*Format*:
. `add /item ITEM_NAME /qty QUANTITY`
. `add /room ROOM_NAME`
* If the resource already exists in RIMS, then its quantity will be updated accordingly.
* Quantity must be a positive integer.

.*Examples*:
* `add /item book /qty 5`
* `add /room multi purpose sports hall`

==== Delete resources: `delete`
Delete item(s)/room available for loan/booking in RIMS.

.*Format*:
. `delete /item ITEM_NAME /qty QUANTITY`
. `delete /room ROOM_NAME`
* If the item or room does not exist in RIMS, then the UI will send a message to inform the user.
* Quantity must be a positive integer.
* Quantity must be less than the total number of items available in RIMS, else it will be reduced to zero.

.*Examples*:
* `delete /item book /qty 5`
* `delete /room multi purpose sports hall`

=== Resource Status

==== Loan out resources: `loan`
Registers an item / room as having been lent out, and is unavailable for further loaning until it is returned.

.*Format*:
. `loan /item ITEM_NAME /qty QUANTITY /by DEADLINE`
. `loan /room ROOM_NAME /by DEADLINE`
* If the item or room does not exist in RIMS, then the UI will send a message to inform the user.
* Quantity must be a positive integer.
* Quantity must be less than the total number of items available in RIMS, else it will be reduced to zero.

.*Examples*:
* `delete /item book /qty 5`
* `delete /room multi purpose sports hall`

==== Return resources: `return`
Registers an item / room as having been returned, and is thus available to be loaned again.

.*Format*:
. `return /item ITEM /qty QUANTITY`
. `return /room ROOM`
* Quantity must be a positive integer.
* Rooms are unique and thus do not require quantities.
* If the user attempts to return a room / a quantity of items that have not been borrowed, the UI will send an error message to the user.


.*Examples*:
* `return /item frisbee /qty 3`
* `return /room seminar room 1`

==== Reserve resources: `reserve`
Registers an item/room as having been reserved (loaned in advance) from a future date to another future date.

.*Format*:
. `reserve /item ITEM /qty QUANTITY /from DATE /to DEADLINE`
. `reserve /room ROOM /from DATE /to DEADLINE`
* While loans take effect from the current date to a specified deadline, reservations specify a future time-frame for an item to be loaned out.
* Quantity must be a positive integer.
* If the user requests a quantity that is greater than the existing amount of that item in the inventory, the UI will send an error message to the user.
* If the item or room does not exist in the inventory, the UI will send an error message to the user.
* Rooms are unique and thus do not require quantities.
* Deadline must be formatted dd/mm/yyyy hhmm in 24-hour time format.

.*Examples*:
* `reserve /item basketball /qty 1 /from 01/10/2019 2300 /to 03/10/2019 2300`
* `reserve /room basketball court /from 01/10/2019 2300 /to 03/10/2019 2300`

==== View deadline of item/room: `due`
View which items/rooms are due on a certain date using this command.

.*Format*:
. `due DATE`
* If the date is left blank then the UI will send a message to inform the user.
* Date must be in DD/MM/YYYY format

.*Examples*:
* `due 07/10/2019`

==== List items/rooms and their status: `list`
View all items and rooms recorded and whether they are available or not.

.*Format*:
. `list`

==== View calendar: `calendar`
View a table-format calendar which shows when items/rooms are in use.

.*Format*:
. `calendar`

=== Others

==== Exiting the program: `bye`
Terminates RIMS.

.*Format*:
. `bye`

==== Reminders
Reminds user about items or rooms due within a specific period of time, upon starting up RIMS.

==== Saving data
With the execution of any command, any changes in data on items, rooms and their statuses will be updated on external text files (`.txt`) within the hard drive, to ensure data persistence and retention even after termination of RIMS. Saving manually is not required.

== FAQ

*Q*: How do I transfer my data to another computer? +
*A*: Install the app in the other computer and overwrite the empty data file it creates with the file that contains the data of your previous RIMS folder.

== Command Summary

* *Add resource*: `resource add /item ITEM /qty QUANTITY` +
e.g. `add /item book /qty 5`
* *Delete resource*: `delete /item ITEM /qty QUANTITY` +
e.g. `delete /item book /qty 5`
* *Loan out resource*: `lend /item ITEM /qty QUANTITY /by DEADLINE` +
e.g. `lend /item frisbee /qty 5 /by 01/10/2019 2300`
* *Return resource*: `return /item ITEM /qty QUANTITY` +
e.g. `return /item frisbee /qty 3`
* *Reserve resource*: `reserve /item ITEM /qty QUANTITY /from DATE /to DEADLINE` +
e.g. `reserve /item basketball /qty 1 /from 01/10/2019 2300 /to 03/10/2019 2300`
* *View deadline of resource*: `due DATE` +
	e.g. `due 04/05/2019`
* *List resources and their status*: `list`
* *View calendar*: `calendar`
* *Exiting the program*: `bye`