= Entertainment-Pro : User Guide
:site-section: UserGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/AY1920S1-CS2113T-T09-4/main

By: `Team Entertainment-Pro`      Since: `Sep 2019`  

== Introduction

Our Javafx app is primarily targeted at people in Singapore who have huge love and interest for movies and TV shows. Our app hence aims to provide a fast and efficient way to find and/or do movies and TV shows related stuff such as getting ratings and reviews for a particular movie and/or TV shows and etc. 

Most importantly, the app is also intended for people who prefer desktop apps over other types of apps, have the ability to type fast and prefer typing over other means of input. As such, the app will have a GUI (Graphical User Interface) but most of the user interactions will happen using a CLI (Command Line Interface). 

Interested? Jump to the Section 2, “Quick Start” to get started. Enjoy!
