= Dolla - User Guide
:site-section: UserGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:repoURL: https://github.com/AY1920S1-CS2113T-F11-2/main/releases/tag/B-RecurringTasks

By: `Team AY1920S1-CS2113T-F11-2`      Since: `Sep 2019`      Licence: `MIT`

== Introduction

Dolla is a *finance management app* that is specially designed for students who stay in the campus of NUS. It uses chat box style interface to provide a
more interactive and interesting user experience. Dolla will help the user to keep track of their spendings and incomes, set reminders, give suggestions
or many more other cool features. Users can interact with Dolla with the various keywords such as `expense`, `income`, `reminder` and many more. Proceed to
<<Quick Start>> to get started!

<< insert GUI mockup here >>

== Quick Start

.  Ensure you have Java `11` or above installed in your Computer.
.  Download the latest Dolla.jar link:{repoURL}/release[here]. (change to release URL in the future)
.  Copy the file to the folder you want to use as the home folder for your Dolla.
.  Double-click the file to start the app.
.  Type the command in the command box and press kbd:[Enter] to execute it. +
e.g. type `*list*` and press kbd:[enter] with list all the income and expense.
.  Here are some example command you can try:
* *`list`* : List all the income and expense with the most recently added on the top
* **`add expense`**`$7 watch movie /on 24/09/2019` : add an expense of $7 for watching movie on 24/09/2019
* **`set limit`**`/tag food $300` : set a limit for the user on the amount of money they can spend on food
* *`bye`* : exits the app
.  Refer to <<Features>> for the details of each command.

[[Features]]
== Features

====
*Command Format*

* Uppercase word in square brackets are the parameter to be inputed by the user. +
e.g. `*add expense* [AMOUNT] [DESCRIPTION] /on[DATE]`, the `[AMOUNT]`, `[DESCRIPTION]` and `[DATE]` are parameters which the user can input as `*add expense* $5 dinner /on 11/11/2019`.
* Item in curly braces are optional. +
e.g. `*add income* [AMOUNT] [DESCRIPTION] /on [DATE] {/tag [TAG]}` can be `add income $40 TA salary for CS1010 /on 10/10/2019 /tag salary` or `*add income* $40 TA salary for CS1010 /on 10/10/2019`.
* Parameters should be in the correct order. +
e.g. `*add recurring expense* [AMOUNT] [DESCRIPTION] /every [DURATION]` should be `*add recurring expense* $45 phone bill /every month` and should not be `*add recurring expense* phone bill $45 /every month`.

*NOTE*: Words in *bold* are the keywords that define the type of command to be executed. e.g. `*remove* [NO.]` `*remove*` is the keyword that will execute the remove command.
====

=== Viewing help: `help`

Format: +
`help`

=== Adding expenses/income: `add expense`, `add income`

Format: + 
`*add expense* [AMOUNT] [DESCRIPTION] /on [DATE] {/tag [TAG]}` +
`*add income* [AMOUNT] [DESCRIPTION] /on [DATE] {/tag [TAG]}`

Examples:

* `add expense $45 MRT concession pass /on 24/09/2019 /tag transport`
* `add income $500 part time tution /on 01/09/2019`

=== list all expenses/income : `list`

Format: +
`list`

==== remove a expenses/income from the list : `remove`




== FAQ

== Command Summary