= User Guide

== 1. Introduction
Our project aims to develop a task tracking application that monitors and encourages productivity. The application will be easy to use, with intuitive ways of adding, finding and tracking tasks that have been added. This easy convenience is definitely helpful in our often busy lives, so give this app a chance to help you!

This user guide aims to help you learn your way around our app, making the learning process smooth and effortless. So what are you waiting for? Let's go!

== 2. Quick Start  

  1. Ensure you have Java `11` or above and Gradle installed in your Computer.
  2. Open up your command prompt (for Windows) or terminal (for Mac). 
  3. Clone from the main into your Computer.
  4. Run command ./gradlew run (for Windows) or gradlew run (for Mac).
  5. Some example commands you can try:

* *`/list`* : lists all tasks
* **`/add assignment /by 9/9/2019 2359`** : adds a deadline type task with description `assignment` to the task list.
* **`/delete`**`1` : deletes the 1st task in the current list
* *`/bye`* : exits the app
 
== 3A. Features 
*Command Format*

* Words in `UPPER_CASE` are the parameters to be supplied by the user e.g. in `todo DESCRIPTION`,
  `DESCRIPTION` is a parameter which can be used as `todo read book`.
* `/add` +
  A grey highlight refers to a command keyword that will be taken from the command line, at textbox at the bottom of the GUI.

* <task description> +
  Texts enclosed by angular brackets are replaced by the user input. For example, <task description> can be “read a book”, while <time> can be “1200”.
* */add <task description> /at <date> <time>* +
  Text written in bold are full command line inputs that trigger an action based on the command keyword specified.
* “GUI Reference” +
  Words enclosed by a pair of double quotes refer to words seen on the GUI.

=== 3A.1 Adding a task : `/add`
Adds a todo/deadline/event to the tasklist depending on the input format.

Format: `/add DESCRIPTION` to add a ToDo task
        `/add DESCRIPTION /by dd/mm/yyyy hhmm` to add a Deadline task  
        `/add DESCRIPTION /at dd/mm/yyyy hhmm` to add a Event task
        
  - `DESCRIPTION` is the description of the task.
  - `dd/mm/yyyy hhmm` is the day/month/year and time(24hrs) of the task e.g. `9/9/2019 1200`
  
Examples:

* `/add read book`
* `/add homework /by 8/8/2019 2359`
* `/add team meeting /at 20/8/2019 1500`

=== 3A.2 Deleting a task : `/delete`
Deletes the specified task from the task list. +
Format: `/delete INDEX`

****
* Deletes the task at the specified `INDEX`.
* The index refers to the index shown in the displayed task list.
* The index must be a positive integer 1, 2, 3, ...
****

Examples:

 * `/list` +
   `/delete 2` +
   Deletes the 2nd task in the task list.
  
=== 3A.3 Finding tasks : `/find`

Finds tasks whose description contains the given keyword. + 
Format: `/find KEYWORD`

****
* The search is case sensitive. e.g. `Book` will not match `book`
* Only the description is searched.
* Only full words will be matched e.g. `books` will not match `book`
****

Examples:

* `/find book` +  
  Returns any task with the descriptions containing the keyword.

=== 3A.4 Marking a task as done : `/done`

Marks a task in the task list as done. DoAfter tasks can only be marked as done when the task before it has been marked as done. +
Format: `/done INDEX`

****
  * Marks the task as done at the specified `INDEX`
  * The index refers to the index shown in the displayed task list.
****

Examples:

  * `/done 1` +  
  Marks the 1st task in the task list as done.

=== 3A.5 Listing all the tasks : `/list`

Shows a list of all the tasks in the task list. + 
Format: `/list`

=== 3A.6 Snoozing a task : `/snooze`

Provides a way to easily snooze/postpone/reschedule a task. +
Format: `/snooze INDEX` +
        `NUMBER minutes/hours/days/weeks/months` OR `dd/mm/yyyy hhmm`
        
****
* Snoozes the task as done at the specified `INDEX`
* The index refers to the index shown in the displayed task list.
* `NUMBER` refers to the quantity of the `minutes/hours/days/weeks/months`
* `dd/mm/yyyy hhmm` is the day/month/year and time(24hrs) of the task e.g. `9/9/2019 1200`
****

Examples:

  * `/snooze 1` +  
    `1 weeks` +
    Snoozes the 1st task in the task list by 1 week.
    
  * `/snooze 2` +
    `9/9/2019 1200` +
    Reschedules the 2nd task in the task list to the input date (9/9/2019 1200).
  
=== 3A.7 Reminders : `/remind`

Reminds the user a task is overdue or when there is only one day or 30 mins left for tasks/events. +
Format: `/remind`

=== 3A.8 Viewing my Schedule : `/show`

Prints the schedule for a user defined date. +
Format: `/show DATE`

****
* Shows the tasks in the schedule for the specified `DATE`
* The `DATE` should be in dd/MM/yyyy format.
****

Examples:

****
* `/show 30/10/2019` +
   Shows all task scheduled for 30/10/2019.
****

=== 3A.9 Exiting the program : `/bye`

Exits the program. +
Format: `/bye`

=== 3A.10 Saving the data

Save the tasks in the hard disk automatically whenever the task list changes.
There is no need to save manually.

=== 3B. Future Features to Implement +
These are the features that are discussed to bw implemented in the coming future. Note that these
are just tentative and subject to changes

=== 3B.1 Mode Select : `[directional] buttons`

Changes the mode such as 'main', 'stopwatch', 'spend points' such that each mode takes in specified
command line prompts.

=== 3B.2 Points System +
Contains functions to purchase items off the 'point shop'

****
* Every completed tasks on time or countdown timer that runs it's full course will have points added
into the user's database
* These points  can be used to purchase comestic value of the application.
****

Examples:
****
* `/buy hat 3` +
User will purchase index 3 (1 index) of the hat off the shop.
****

=== 3B.3 Hero System +
Contains functions related to the user's hero.

****
* Hero will be a personalized avatar that the user can customize based off their producitivity
* The longer they play, the more personalized and "stronger" the hero can look.
****

Examples:
****
* `/play run` +
User's hero run animation will be played on the screen.
****


=== 3B.4 Timer : `/timer` +

Starts a exitable countdown that can be paused and resumed. Upon starting a new timer, HUSTLER recommends some tasks for doing depending on the amount of time set. +
Format: `/timer HH MM SS`

****
* User earns points based off how long the countdown was given.
****

Examples:

****
* `/timer 01 30 45` +
   Start a countdown for 1 hour, 30 minutes and 45 seconds.
   
* `/pausetimer` +
   Pauses a running timer. This command is invalid and does nothing if there are no timers currently running.
   
* `/resumetimer` +
   Resumes a timer that has been paused. This command is invalid if there are no timers currently paused.
   
* `/stoptimer` +
   Prematurely stops a running timer, resetting it. This command is invalid if there are no timers currently running.

****

=== 3B.5 Sort : `/sort` +

Sorts the tasks in the tasklist according to a parameter specified by the user (either normal, datetime or priority).

Examples:

****
* `/sort normal` +
  Sorts the tasks in order of which was entered first.
  
* `/sort datetime` +
  Sorts the tasks in order of which is more urgent/ due sooner.

* `/sort priority` +
  Sorts the tasks in order of their priority, with the task assigned with higher priority showing first. Tasks can be assigned priority   levels by the user.
  
****

=== 3B.6 Achievements : `/achievement` +

Brings up the achievement page that shows the user the lists of achievements that have been unlocked and unlocked as well as the total number of points the user has accumalated.

****
* Points can be earned from completing tasks, adding tasks and logging into Hustler on consecutive days.
****

=== 3B.6 Avatar : `/avatar` +

This command shows the user all information related to his/ her avatar, from level and experience to stats. Additionally, this command also shows the weapon and armor equipped, if any.

Other avatar related commands:

****
* `/avatar` : show avatar stats
* `/setname NAME` : changes the avatar name
* `/buy INDEX` : purchase items
* `/inventory` : shows what you own
* `/equip INDEX` : equips the item in the inventory
****

== 4. FAQ

*Q*: Where do I install Java 11 from? +  
*A*: Java 11 can be downloaded from the Oracle website. https://www.oracle.com/technetwork/java/javase/downloads/index.html

== 5. Command Summary

* *Add*: `/add DESCRIPTION` `/add DESCRIPTION /by dd/mmm/yyyy hhmm` `/add DESCRIPTION /at dd/mm/yyyy hhmm` +
  e.g. `/add read book` `/add homework /by 8/8/2019 2359` `/add team meeting /at 20/8/2019 1500`
* *Delete*: `/delete INDEX`  +  
  e.g. `/delete 3`
* *Find*: `/find KEYWORD` +
  e.g. `/find book`
* *Done*: `/done INDEX` +
  e.g. `/done 2`
* *List*: `/list`
* *Snooze*: `/snooze INDEX DATE TIME` or `/snooze INDEX INTEGER UNITS`+
  e.g. `/snooze 3 22/01/2020 1900` or `/snooze 3 4 days`
* *Remind*: `/remind`
* *Show*: `/show`
* *Sort*: `/sort SORTTYPE` +
  e.g. `/sort priority` `/sort normal` `/sort datetime`
* *Achievements*: `/achievements`
* *Avatar*: `/avatar`
* *Bye*: `/bye`
