= Dolla - User Guide
:site-section: UserGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:repoURL: https://github.com/AY1920S1-CS2113T-F11-2/main/releases/tag/B-RecurringTasks

By: `Team AY1920S1-CS2113T-F11-2`      Since: `Sep 2019`      Licence: `MIT`

== Introduction

Dolla is a *finance management app* that is specially designed for students who stay in the campus of NUS. It uses chat box style interface to provide a
more interactive and interesting user experience. Dolla will help the user to keep track of their spendings and incomes, set reminders, give suggestions
or many more other cool features. Users can interact with Dolla with the various keywords such as `expense`, `income`, `reminder` and many more. Proceed to
<<Quick Start>> to get started!

<< insert GUI mockup here >>

== Quick Start

.  Ensure you have Java `11` or above installed in your Computer.
.  Download the latest Dolla.jar link:{repoURL}/release[here]. (change to release URL in the future)
.  Copy the file to the folder you want to use as the home folder for your Dolla.
.  Double-click the file to start the app.
.  Type the command in the command box and press kbd:[Enter] to execute it. +
e.g. type `*list*` and press kbd:[enter] with list all the income and expense.
.  Here are some example command you can try:
* *`list`* List all the income and expense with the most recently added on the top
* **`add expense`**`$7 watch movie /on 24/09/2019` : add an expense of $7 for watching movie on 24/09/2019
* **`set limit`**`/tag food $300` : set a limit for the user on the amount of money they can spend on food
* *`bye`* : exits the app
.  Refer to <<Features>> for the details of each command.

[[Features]]
== Features

== FAQ

== Command Summary