= MisterMusik - User Guide
:site-section: UserGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/AY1920S1-CS2113T-F11-4/main

By: `Team CS2113T-F11-4`      Since: `Aug 2019`      Licence: `MIT`

== Introduction

MisterMusik is a scheduler program created for serious music students
pursuing a professional music career as a western classical music performer.
The program is designed to automate and streamline most of the process in scheduling and organisation of materials,
allowing the students to focus more on the important aspects of their education.

== Quick Start

. Ensure you have Java `11` or above installed in your computer
. Download the latest `mistermusik.jar`
. Copy the file to the folder you want to use as the home folder for your MisterMusik
. Double-click the file to start the app. The GUI should appear in a few seconds.
. Type the command in the command box and press kbd:[Enter] to execute it. +
E.g. typing `help` and pressing kbd:[Enter] will open the help window.
+
. Please refer to <<Features>> for details of each command.

[[Features]]
== Features

=== Help list : `[coming v1.4]`

Brings up a list of available commands that the user can input.
It also displays a brief version of this user guide. +

Format: `help`

=== Reminders : `reminder`

Displays the list of tasks over the next three days. +

Format: `reminder`

=== Adding a to-do task : `todo`

Adds a task defined by the user to the to-do list with a deadline. +

Format: `todo <name of task> /dd-MM-yyyy` +
E.g. `todo complete theory homework /10-10-2019`
adds a deadline to complete the user's theory homework by 10 October 2019.

=== Adding an event task :

Adds an event defined by the user to the list of tasks.
The former and latter time inputs denote the start and end time respectively. +

For recurring events, please see <<Recurring events :, Recurring events>>.

. Practice sessions : `practice` +
Format: `practice <name of practice> /dd-MM-yyyy HHmm HHmm`
+
. Examinations: `exam` +
Format: `exam <name of exam> /dd-MM-yyyy HHmm HHmm`
+
. Recitals: `recital` +
Format: `recital <name of recital> /dd-MM-yyyy HHmm HHmm`
+
. Concerts : `concert` +
Format: `concert <name of concert> /dd-MM-yyyy HHmm HHmm`


=== Recurring events :

MisterMusik allows the user to add recurring events (e.g. weekly lessons).
The input format is as per normal with an extra recurring period input. +

Format: `<type of event> <name of event> /dd-MM-yyyy HHmm HHmm /period(days)` +

E.g. “lesson Theory class /18-09-2019 0900 1030 /7”
adds a weekly recurring event from 9:00am to 10:30am, starting on 18 September 2019.


=== Viewing schedules : `view`

Brings up a list of tasks for a particular date. +

Format: `view dd/MM/yyyy` +
E.g. “view 18/09/2019”
displays all events/todos on/by the date 18 September 2019.


=== Checking for free days : `check`

The user can check for the nearest days that are free. +

Format: `check`


=== Marking a task as done: `done`

Marks a task in the list as completed, denoted by a tick when displaying the task. +

Format: `done <task index>` +
E.g. “done 5” marks task number 5 as done.


=== Rating a practice session : `[coming v1.4]`

The user will be able to rate the efficiency of a particular practice session after completing it.
When the practice session is marked as done,
the user will be prompted to add an efficiency rating and any extra comments or feedback. +

Format: `rate <task index>`


=== Adding details to events : `[coming v1.4]`

The user will be able to add any extra details to an event when adding it to the task list.
For practice sessions or lessons,
it can be used to take feedback from instructors and lesson notes respectively. +

Format: `details <task index>` or `notes <task index>`


=== Rescheduling events : `[coming v1.4]`

The user will be able to reschedule an existing event. +

Format: `reschedule <task index>`


=== Searching for a free slot : `[coming v1.4]`

The user will be able to search for any days within the next 2 weeks
that contains a specified period of time that is free. +
For example, searching for a 4h free slot
will display all the dates within the 2 weeks with
at least 4 hours of free time in the schedule. +

Format: `searchfree 4h`


=== Exiting the program : `bye`

Exits the program. +

Format: `bye`


== Additional Features

=== Detecting Clashes : `[coming v2.0]`

When the user inputs a new event, MisterMusik will check
if it has any clashing date and time with existing events
and warns the user of the clash.

=== Sorting By Date : `[coming v1.4]`

MisterMusik will automatically sort the list by the date and time of each task
so the user will not have to manually prioritise each event and todo task.

=== Search and edit : `[coming v2.0]`

The user will be able to search for a specific task and edit its corresponding details.

=== Reminder for specific task types : `[coming v2.0]`

The user will be able to get reminders of specific task type using the reminder command
and specifying which type they would like to be displayed. +

E.g. “reminder exam”
displays a reminder of all exam events within the next 3 days.

== FAQ
*Q:* How do I transfer my data to another Computer? +
*A:* Install the app in the other computer and overwrite the empty data file
it creates with the file that contains the data of your previous MisterMusik folder.


== Glossary

. Event: an event refers to any activity with a start time.
+
. To-do: a to-do refers to any activity with a deadline.
