= User Guide

== 1. Introduction
Our project aims to develop a task tracking application that monitors and encourages productivity. The application will be easy to use, with intuitive ways of adding, finding and tracking tasks that have been added. This easy convenience is definitely helpful in our often busy lives, so give this app a chance to help you!

This user guide aims to help you learn your way around our app, making the learning process smooth and effortless. So what are you waiting for? Let's go!

== 2. Quick Start  

  1. Ensure you have Java `11` or above and Gradle installed in your Computer.
  2. Open up your command prompt (for Windows) or terminal (for Mac). 
  3. Clone from the main into your Computer.
  4. Run command ./gradlew run (for Windows) or gradlew run (for Mac).
  5. Some example commands you can try:

* *`/list`* : lists all tasks
* **`/add assignment /by 9/9/2019 2359`** : adds a deadline type task with description `assignment` to the task list.
* **`/delete`**`1` : deletes the 1st task in the current list
* *`/bye`* : exits the app
 
== 3. Features

Using Hustler, you can easily and effectively manage your tasks, deadlines and personal projections. This section aims to introduce the various important features of Hustler. However, before we do that there are some command formats that will be used from here on out. They are:


*Command Formats*

* `/add` +
  A grey highlight refers to a command keyword that will be taken from the command line, at textbox at the bottom of the GUI.

* <task description> +
  Texts enclosed by angular brackets are fields that have to be replaced with the user input. For example, <task description> can be “read a book”, while <time> can be “1200”.
  
* */add <task description> /at <date> <time>* +
  Texts written in bold are full command line inputs that trigger an action based on the command keyword specified.
  
* “GUI Reference” +
  Words enclosed by a pair of double quotes refer to words seen on the GUI.

=== 3.1 Adding a task: `/add`

Since Hustler is a productivity checker, the first thing you would want to do is to add your tasks for the next few days. In order to do so, you must issue commands in the command line at the bottom.

** Note: Though Hustler v1.4 features a GUI, most of the user input is taken from the command line at the bottom. Hence, you need to know the command syntax to provide an input.

The syntax for adding a task to the list is as follows:

---
*/add <task description>*
---

On issuing this command in the command-lie text box at the bottom, a task will be added to the list.

** Note: Hustler has several task types. It also has a difficulty level for each task. By default, if you issue the above command, Hustler sets the task to type ToDo and the difficulty to medium. 

==== 3.1.1	Adding commands of different types

Apart from have simple ToDo commands, you will most likely have time constraints. Hustler allows you to add Deadlines and Events and make them recurrent so they repeat themselves every set time periods. The difficulty of the task can also be added. All of this can be done with a simple addition to the syntax.

// tag::base-alt[]
[width="90"]
|===

| S/N | Command | Elaboration

| 1. | */add <task description>* | Todo task, with default difficulty set to medium.

| 2. | */add <task description> /by <date> <time>* | Deadline task. Date format is DD/MM/YY and time format is HHmm. Where D stands for day, M stands for month, Y stands for year, H stands for hour in 24-hour format and m stands for minutes. Uses the `/by` keyword.

| 3. | */add <task description> /at <date> <time> | Event task. The date time format is the same as the one for deadline. Uses the `/at` keyword.

| 4. | */add <task description> /by <date> <time> /every <frequency>* | Recurring Deadline where the format of <frequency> is <number> followed by minutes/hours/days/weeks/months. Uses the `/every` keyword.

| 5. | */add <task description> /at <date> <time> /every <frequency>* | Recurring Event where the formatting is the same as that of recurrent deadline. Uses the `/every` keyword.

| 6. | */add <task description> /tag <one-word tag>* | Tags the task with a one-word tag. It can be any word consisting of alphanumeric letters.

| 7. | */add <task description> /d <L/M/H>* | States the difficulty of the task where <E/M/H> can be either replaced with H which stands for high, M which stands for medium and E which stands for easy. Uses the `/d` keyword.

|===
// end::base-alt[]

----
The tagging and difficulty settings are optional and can be appended to every other types of task given. 
----

----
By making these changes to the syntax of the command additions can be made to the task type.
----

While using keywords, the order in which the keywords are issued is important. First the `/at` or `/by` keywords are to be added followed by `/every` if the task is recurring. 

Some trivial examples can be seen below:
  
Examples:

*	 */add read book* (ToDo)
*	 */add Homework /by 8/8/2019 2359* (Deadline)
*	 */add Lab report /by 13/8/2019 1700 /every 1 weeks* (Recurring Deadline)
*	 */add Team meeting /at 10/8/2019 1500* (Event)
*  */add Family dinner /at 15/8/2019 1800 /every 2 weeks* (Recurring Event)

=== 3A.2 Deleting a task : `/delete`

Sometimes you might want to delete a task because you no longer have to perform it. In order to do so, a `/delete` command can be issued in the command line. The syntax of the delete keyword is as follows.

*/delete <index>*

1.	Look at the index of the command you want to delete.
2.	Type in the above command.
3.	Press Enter.

The command will disappear from the list and the index gets readjusted. In addition, you can also mass delete tasks. Below are the two additional ways on how to mass delete tasks.

*	*/delete all* clears your task list.
*	*/delete done* deletes all tasks that have been marked as completed.


Deletes the specified task from the task list. +
Format: `/delete INDEX`

****
* Deletes the task at the specified `INDEX`.
* The index refers to the index shown in the displayed task list.
* The index must be a positive integer 1, 2, 3, ...
****

Examples:

 * `/list` +
   `/delete 2` +
   Deletes the 2nd task in the task list.
  
=== 3A.3 4.3	Marking tasks as done

If you ended up completing the task, you might want to mark the task as done. Issue the /done command to do so. The syntax of the command is as follows:

*/done <index>*
  
1.	Look at the index of the command you want to mark.
2.	Type in the above command.
3.	Press Enter.

A confirmation message pops up to confirm the change.

----
Although the task has been marked done, it is not deleted from the list. If you wish for it to disappear then delete the task using the /delete command as stated above.
----
  
=== 3A.3 Finding tasks : `/find`

When dealing with multiple tasks, it is hard to find older ones even if you sort it in a particular way. To find tasks, you can use the /find command:

*/find <keyword>*

The command takes in your input <keyword> which Is present in the task you want to find. Currently, this feature is able to find tagged words, dates, time and words in the task description.

Example:

Suppose it is the date 31/10/2019, and you remember there is an assignment due tomorrow but not sure what. Here are the steps to find out what do you have due tomorrow.

1.	Type /find <date>. For this example, we have to type /find 01/11/2019 as shown and hit the Enter button on your computer.
----
Note that the parser is only able to recognize dates in DD/MM/YYYY format, and inputting /find 1/11/2019 instead will not yield the correct result.
----
2.	The list of things that is due on 1st November 2019 will be shown on the screen.

There are couple of things to take note with the current /find function:
*	It is only able to recognize dates in DD/MM/YYYY format
*	It is only able to recognize time in 24-hour clock HHMM format
*	It will only find exact word-for-word for tags
*	It can find tasks that partly consists of the keyword of the task description (querying for “proj” will yield the same result as above.


Finds tasks whose description contains the given keyword. + 
Format: `/find KEYWORD`

****
* The search is case sensitive. e.g. `Book` will not match `book`
* Only the description is searched.
* Only full words will be matched e.g. `books` will not match `book`
****

Examples:

* `/find book` +  
  Returns any task with the descriptions containing the keyword.

=== 3A.4 Marking a task as done : `/done`

Marks a task in the task list as done. DoAfter tasks can only be marked as done when the task before it has been marked as done. +
Format: `/done INDEX`

****
  * Marks the task as done at the specified `INDEX`
  * The index refers to the index shown in the displayed task list.
****

Examples:

  * `/done 1` +  
  Marks the 1st task in the task list as done.

=== 3A.5 Listing all the tasks : `/list`

Shows a list of all the tasks in the task list. + 
Format: `/list`

=== 3A.6 Snoozing a task : `/snooze`

Provides a way to easily snooze/postpone/reschedule a task. +
Format: `/snooze INDEX` +
        `NUMBER minutes/hours/days/weeks/months` OR `dd/mm/yyyy hhmm`
        
****
* Snoozes the task as done at the specified `INDEX`
* The index refers to the index shown in the displayed task list.
* `NUMBER` refers to the quantity of the `minutes/hours/days/weeks/months`
* `dd/mm/yyyy hhmm` is the day/month/year and time(24hrs) of the task e.g. `9/9/2019 1200`
****

Examples:

  * `/snooze 1` +  
    `1 weeks` +
    Snoozes the 1st task in the task list by 1 week.
    
  * `/snooze 2` +
    `9/9/2019 1200` +
    Reschedules the 2nd task in the task list to the input date (9/9/2019 1200).
  
=== 3A.7 Reminders : `/remind`

Reminds the user a task is overdue or when there is only one day or 30 mins left for tasks/events. +
Format: `/remind`

=== 3A.8 Viewing my Schedule : `/show`

Prints the schedule for a user defined date. +
Format: `/show DATE`

****
* Shows the tasks in the schedule for the specified `DATE`
* The `DATE` should be in dd/MM/yyyy format.
****

Examples:

****
* `/show 30/10/2019` +
   Shows all task scheduled for 30/10/2019.
****

=== 3A.9 Exiting the program : `/bye`

Exits the program. +
Format: `/bye`

=== 3A.10 Saving the data

Save the tasks in the hard disk automatically whenever the task list changes.
There is no need to save manually.

=== 3B. Future Features to Implement +
These are the features that are discussed to bw implemented in the coming future. Note that these
are just tentative and subject to changes

=== 3B.1 Mode Select : `[directional] buttons`

Changes the mode such as 'main', 'stopwatch', 'spend points' such that each mode takes in specified
command line prompts.

=== 3B.2 Points System +
Contains functions to purchase items off the 'point shop'

****
* Every completed tasks on time or countdown timer that runs it's full course will have points added
into the user's database
* These points  can be used to purchase comestic value of the application.
****

Examples:
****
* `/buy hat 3` +
User will purchase index 3 (1 index) of the hat off the shop.
****

=== 3B.3 Hero System +
Contains functions related to the user's hero.

****
* Hero will be a personalized avatar that the user can customize based off their producitivity
* The longer they play, the more personalized and "stronger" the hero can look.
****

Examples:
****
* `/play run` +
User's hero run animation will be played on the screen.
****


=== 3B.4 Timer : `/timer` +

Hustlers main feature in boosting productivity is in its task completion mode which can be summarized under the /timer command.

----
Note that you can also manually complete task by typing /done <index> as shown above. However, we encourage you to use the recommended schedule with the timer integrated in order to complete the tasks.
----

====3B.4.1 Using the /timer command

After collecting all the tasks, you have added, you can use Hustler to help you finish tasks. To begin, tell Hustler the number of hours you have available to work. This can be done with the help of the /timer command. The syntax of the command is as follows:

====3B.4.2 Recommended schedule

After supplying the amount of time available to work on tasks using the /timer command, a recommended schedule pops up which is a list of incomplete tasks that Hustler recommends you work on. Hustler keeps track of the amount of time remaining for a task, the amount of time you have spent on the task and the difficulty of the task to make recommendations. You can edit this schedule to your liking before sitting down and setting yourself up for work. In order to explain the next few commands the following list of tasks in the “Tasks” section will be considered as shown.

=====3B.4.2.1 Adding tasks to the schedule using the /addFromList command

The recommended schedule that pops up after using the /timer command sometimes might not be to your liking. Sometimes you might feel like working on more tasks. As such, you can add tasks from the “Tasks” section to the schedule using the /addFromList command. The syntax of the /addFromList command is as follows:

*/addFromList <index in “Task” section>*

The task that you referred to from the “Task” section pops up in the schedule and the time allotted to each task is updated.
For example, on running the command:

*/timer 5 0 0*

Hustler is specified that you have 5 hours available for work and the following recommended schedule is shown on the list of tasks specified.

=====3B.4.2.2 Removing tasks from the schedule using the /remove command

In case you do not feel like working on a task, you can remove it from the recommended schedule. In order to do so the /remove command can be run using the following syntax:

*/remove <index>*

The task at the supplied index will be removed and the updated schedule will be shown.
For example:

If you want to remove task at index 4 from Figure 3, the following command can be run:

*/remove 4*

As a result, “create notes for 2101” will be removed from this schedule can be seen below

=====3B.4.2.3	Update the time allotted to a command using the /update command

You might be in a situation in which you need to change the amount of time that has been allotted to a task. In order to do so, the /update command is used. The syntax of the update command is as follows:

*/update <index> <duration H:M:S>*

On running this command the time allotted to task at index specified is changed to a duration in the format <hours:minutes:seconds>. 
For example:

In order to change the time allotted to 3 in Figure 4 from 1 hour 40 minutes to 1 hour the following command can be run.

*/update 3 1:0:0*



Starts a exitable countdown that can be paused and resumed. Upon starting a new timer, HUSTLER recommends some tasks for doing depending on the amount of time set. +
Format: `/timer HH MM SS`

****
* User earns points based off how long the countdown was given.
****

Examples:

****
* `/timer 01 30 45` +
   Start a countdown for 1 hour, 30 minutes and 45 seconds.
   
* `/pausetimer` +
   Pauses a running timer. This command is invalid and does nothing if there are no timers currently running.
   
* `/resumetimer` +
   Resumes a timer that has been paused. This command is invalid if there are no timers currently paused.
   
* `/stoptimer` +
   Prematurely stops a running timer, resetting it. This command is invalid if there are no timers currently running.

****

=== 3B.5 Sort : `/sort` +

There are 3 ways in which tasks can be sorted, in the normal order based on the time it was added, chronological order based on time and a prioritize order that prioritizes tasks based on the amount of time available with respect to the current time and the difficulty of the task.

*	`/normal` sorts the tasks based on when the user input the tasks.
*	`/chronological` sorts the tasks based on the date and time of the tasks.
*	`/prioritize` sorts the tasks based on amount of time available and difficulty.


Examples:

Let’s say you want to focus on the most upcoming tasks and want to know which tasks are nearest to the current date. Instead of having to scroll and view each task in the task list to determine which is the earliest task, you can easily view the tasks in chronological order by the /sort command you have entered.

To sort:
1.	Type /sort datetime into the command box and press the Enter button on your keyboard to execute it.
2.	The result box will display the message “Task list has been successfully sorted!”.
3.	The newly sorted task list will be displayed on the screen. You can now view the tasks in chronological order.

=== 3B.6 Achievements : `/achievement` +

Brings up the achievement page that shows the user the lists of achievements that have been unlocked and unlocked as well as the total number of points the user has accumalated.

****
* Points can be earned from completing tasks, adding tasks and logging into Hustler on consecutive days.
****

=== 3B.6 Avatar : `/avatar` +

This command shows the user all information related to his/ her avatar, from level and experience to stats. Additionally, this command also shows the weapon and armor equipped, if any.

Other avatar related commands:

****
* `/avatar` : show avatar stats
* `/setname NAME` : changes the avatar name
* `/buy INDEX` : purchase items
* `/inventory` : shows what you own
* `/equip INDEX` : equips the item in the inventory
****

== 4. FAQ

*Q*: Where do I install Java 11 from? +  
*A*: Java 11 can be downloaded from the Oracle website. https://www.oracle.com/technetwork/java/javase/downloads/index.html

== 5. Command Summary

* *Add*: `/add DESCRIPTION` `/add DESCRIPTION /by dd/mmm/yyyy hhmm` `/add DESCRIPTION /at dd/mm/yyyy hhmm` +
  e.g. `/add read book` `/add homework /by 8/8/2019 2359` `/add team meeting /at 20/8/2019 1500`
* *Delete*: `/delete INDEX`  +  
  e.g. `/delete 3`
* *Find*: `/find KEYWORD` +
  e.g. `/find book`
* *Done*: `/done INDEX` +
  e.g. `/done 2`
* *List*: `/list`
* *Snooze*: `/snooze INDEX DATE TIME` or `/snooze INDEX INTEGER UNITS`+
  e.g. `/snooze 3 22/01/2020 1900` or `/snooze 3 4 days`
* *Remind*: `/remind`
* *Show*: `/show`
* *Sort*: `/sort SORTTYPE` +
  e.g. `/sort priority` `/sort normal` `/sort datetime`
* *Achievements*: `/achievements`
* *Avatar*: `/avatar`
* *Bye*: `/bye`
