= ModPlan v1.1 - User Guide
:site-section: UserGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/AY1920S1-CS2113T-F10-1/main

By: `Team SE-EDU`      Since: `Jun 2016`      Licence: `MIT`

== Introduction

**ModPlan**

Your one stop solution to module planning through out your university tenure! + 
ModPlan is a module planning system that expands on NUSMODS to help NUS Computer Engineering students to plan their modules for all four years of their bachelor's degree.

== Quick Start

.  Ensure you have Java `11` or above installed in your Computer.
.  Download the latest `addressbook.jar` link:{repoURL}/releases[here]. (change this)
.  Copy the file to the folder you want to use as the home folder for your Address Book.
.  Double-click the file to start the app. The GUI should appear in a few seconds.
+
.  Type the command in the command box and press kbd:[Enter] to execute it. +
.  Some example commands you can try:

* *`list`* : lists all tasks
* **`add`**`n/John Doe p/98765432 e/johnd@example.com a/John street, block 123, #01-01` : adds a contact named `John Doe` to the Address Book.
* **`delete`**`3` : deletes the 3rd contact shown in the current list
* *`exit`* : exits the app

.  Refer to <<Features>> for details of each command.

[[Features]]
== Features

====
*Command Format*

* Words in `UPPER_CASE` are the parameters to be supplied by the user e.g. in `add n/NAME`, `NAME` is a parameter which can be used as `add n/John Doe`.
* Items in square brackets are optional e.g `n/NAME [t/TAG]` can be used as `n/John Doe t/friend` or as `n/John Doe`.
* Items with `…`​ after them can be used multiple times including zero times e.g. `[t/TAG]...` can be used as `{nbsp}` (i.e. 0 times), `t/friend`, `t/friend t/family` etc.
* Parameters can be in any order e.g. if the command specifies `n/NAME p/PHONE_NUMBER`, `p/PHONE_NUMBER n/NAME` is also acceptable.
====

=== Adding a person: `add`

Adds a person to the address book +
Format: `add n/NAME p/PHONE_NUMBER e/EMAIL a/ADDRESS [t/TAG]...`

[TIP]
A person can have any number of tags (including 0)

Examples:

* `add n/John Doe p/98765432 e/johnd@example.com a/John street, block 123, #01-01`
* `add n/Betsy Crowe t/friend e/betsycrowe@example.com a/Newgate Prison p/1234567 t/criminal`

=== Listing all persons : `list`

Shows a list of all persons in the address book. +
Format: `list`

=== Locating persons by name: `find`

Finds persons whose names contain any of the given keywords. +
Format: `find KEYWORD [MORE_KEYWORDS]`

****
* The search is case insensitive. e.g `hans` will match `Hans`
* The order of the keywords does not matter. e.g. `Hans Bo` will match `Bo Hans`
* Only the name is searched.
* Only full words will be matched e.g. `Han` will not match `Hans`
* Persons matching at least one keyword will be returned (i.e. `OR` search). e.g. `Hans Bo` will return `Hans Gruber`, `Bo Yang`
****

Examples:

* `find John` +
Returns `john` and `John Doe`
* `find Betsy Tim John` +
Returns any person having names `Betsy`, `Tim`, or `John`

// tag::delete[]
=== Deleting a person : `delete`

Deletes the specified person from the address book. +
Format: `delete INDEX`

****
* Deletes the person at the specified `INDEX`.
* The index refers to the index number shown in the displayed person list.
* The index *must be a positive integer* 1, 2, 3, ...
****

Examples:

* `list` +
`delete 2` +
Deletes the 2nd person in the address book.
* `find Betsy` +
`delete 1` +
Deletes the 1st person in the results of the `find` command.

// end::delete[]

=== Exiting the program : `exit`

Exits the program. +
Format: `exit`

=== Saving the data

Address book data are saved in the hard disk automatically after any command that changes the data. +
There is no need to save manually.

== FAQ

*Q*: How do I transfer my data to another Computer? +
*A*: Install the app in the other computer and overwrite the empty data file it creates with the file that contains the data of your previous Address Book folder.

== Command Summary

* *Add* `add n/NAME p/PHONE_NUMBER e/EMAIL a/ADDRESS [t/TAG]...` +
e.g. `add n/James Ho p/22224444 e/jamesho@example.com a/123, Clementi Rd, 1234665 t/friend t/colleague`
* *Delete* : `delete INDEX` +
e.g. `delete 3`
* *Find* : `find KEYWORD [MORE_KEYWORDS]` +
e.g. `find James Jake`
* *List* : `list`
