= AlphaNUS - User Guide
:site-section: UserGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/AY1920S1-CS2113T-F10-3/main

By: `Team F10-3`      Since: `Aug 2019`

== Introduction

AlphaNUS is a personal assistant for NUS club treasurers to easily manage their payment forms to be submitted.

== Quick Start
.  Some example commands you can try:

* *`list`* : lists all submission deadlines
* **`delete`**`3` : deletes the 3rd task shown in the current list
* *`bye`* : exits the app

.  Refer to <<Features>> for details of each command.

[[Features]]
== Features

====
*Command Format*

* Words in `UPPER_CASE` are the parameters to be supplied by the user e.g. in `add TASK_CONTENT`, `TASK_CONTENT` is a parameter which can be used as `add submission`.

* Items in `square brackets` are optional e.g `d/DESCRIPTION [p/PAYMENT_DETAIL]` can be used as `d/welcome tea p/food 12` or as `d/welcome tea`

* Items with `…`​ after them can be used multiple times including zero times e.g. `[p/PAYMENT_DETAIL]…`​ can be used as `` ``(i.e. 0 times), `p/food 12`, `p/food 12 p/drinks 7` etc
====

=== Adding a new payee: `add payee`

Adds a new payee named `PAYEE` to project with details of `PAYEE` such as their email address `EMAIL`, matriculation number `MATRICNUM` and phone number `PHONENUM`. +
Format: `add payee p/PAYEE e/EMAIL m/MATRICNUM ph/PHONENUM`

[TIP]
You may use more than one word for all fields.

[TIP]
You may not add a new `PAYEE` if a payee named `PAYEE` already exists.

Examples:

* GOOD: `payments p/John Doe i/Welcome Tea c/12.00 v/INV-001`
* BAD: `payments p/John Doe i/Welcome Tea c/*$*12.00 v/INV-001`

=== Adding a new payment: `add payment`

Adds a new payment under a specified `PAYEE` with payment name `ITEM` that incurs cost `COST` and have an invoice number `INVOICE`. +
Format: `add payment p/PAYEE i/ITEM c/COST v/INVOICE`

[TIP]
You may use more than one word for all fields except `COST`.
[TIP]
`COST` must be a number, omit any other characters. Decimals are allowed.

Examples:

* GOOD: `payments p/John Doe i/Welcome Tea c/12.00 v/INV-001`
* BAD: `payments p/John Doe i/Welcome Tea c/*$*12.00 v/INV-001`


=== Edit the payment details: `edit`

Edits any field `FIELD` of payee named `PAYEE`, replacing the existing data in that field with `REPLACEMENT`+
If only the payee fields are being modified, `INVOICE` should be blank. +
The following payee fields are acceptable: `PAYEE`, `EMAIL`, `MATRIC`, `PHONE` +
The following payment fields are acceptable: `ITEM`, `COST`, `INV`, `DEADLINE`, `STATUS` +

Format: `edit p/PAYEE v/INVOICE f/FIELD r/REPLACEMENT`

[TIP]
Ensure `FIELD` supplied matches one of the acceptable fields above!
[TIP]
`DEADLINE` should be specified in `dd/mm/yyyy` format

Examples:

* `redetail 2 d/drinks 8 d/snacks 20`
* `redetail 2`(i.e. this operation removes all previous details)

=== Find a payment or deadline based on its description: `find`

Find a payment or deadline based on its description +
Format: `find d/DESCRIPTION`

[TIP]
there can have spaces in the description

Examples:

* `find d/welcome tea`

=== Delete a deadline/payment form: `delete`

Delete a deadline/payment from the task list +
Format: `delete ID`

[TIP]
the index of the task should not be out of range

Examples:

* `delete 3`

=== Delete a payee: `delete payee`

Delete a payee and their details +
Format: `delete payee p/payee`

Examples:

* `delete payee p/John`

=== Approve a payment form: `approve`

Approve a payment form with a message +
Format: `approve ID [m/MESSAGE]`

[TIP]
the index of the task should not be out of range

Examples:

* `approve 3 m/approved by xxx on Monday`
* `approve 3`

=== List out all current submission deadlines: `list`

List out all payments, sorted into overdue, pending and approved statuses, in order of ascending deadlines+
Format: `list`

=== Adding a deadline: `deadline`

Adds a new deadline with description +
Format: `deadline d/DESCRIPTION`

[TIP]
there can have spaces in the deadline description +

Examples:

* `deadline d/submit venue payment`

=== Adding an invoice to a deadline: `deadline`

Adds a invoice to a deadline with invoice number +
Format: `invoice ID i/INVOICE_NUMBER`

[TIP]
the date of the deadline will be automatically set to one month after the date that an invoice is assigned to it +
[TIP]
the ID should not be out of range

Examples:
* `invoice i i/123456`

=== See the nearest deadline: `reminder`

Show the deadline task with the nearest deadline. +
Format: `reminder`

[TIP]
the result deadline usually has a higher priority than the other deadlines

=== Edit the deadline/payment form's description: `edit`

Edit a previously added task's description and details +
Format: `edit ID d/NEW_DESCRIPTION`

[TIP]
there can have spaces in the description
[TIP]
the id should not e out of range

Examples:

* `edit 2 d/welcome tea for freshmen`

=== snooze the deadline: `snooze`

snooze the deadline time by 1 hour +
Format: `snooze ID`

[TIP]
the id input should not be out of range


Examples:

* `snooze 5`

=== View deadline by schedule: `view`
View current deadlines in a specific date +
Format: `view t/DATE`

[TIP]
the results will be sorted based on their deadlines (i.e. the one with the earliest deadline will show on the top)
[TIP]
the format of the date should be DD/MM/YYYY

Examples:

* `view t/05/10/2019`

=== View previous input commands: `history`

view input commands entered by the user from the start till the present +
Format: `history`

=== Exit command: `bye`

exit from Duke +
Format: `bye`

=== Saving the data

Task List data are saved in the hard disk automatically after any command that changes the data. +
There is no need to save manually.


== Command Summary

* *list*: `list`
* *deadline*: `deadline d/DESCRIPTION`
* *invoice*: `invoice ID i/INVOICE_number`
* *reminder*: `reminder`
* *edit* : `edit ID d/NEW_DESCRIPTION`
* *snooze*: `snooze ID`
* *payments* : `payments d/DESCRIPTION [p/PAYMENT_DETAIL]...`
* *redetail*: `redetail ID [d/PAYMENT_DETAIL]...`
* *find* : `find d/DESCRIPTION`
* *view* : `view t/DATE`
* *delete* : `delete ID`
* *approve*: `approve ID [m/MESSAGE]`
* *exit*: `bye`
