= AlphaNUS - User Guide
:site-section: UserGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/AY1920S1-CS2113T-F10-3/main

By: `Team F10-3`      Since: `Aug 2019`

== Introduction

AlphaNUS is a personal assistant for NUS club treasurers to easily manage their payment forms to be submitted.

== Quick Start
.  Some example commands you can try:

* *`list`* : lists all tasks
* **`delete`**`3` : deletes the 3rd task shown in the current list
* *`bye`* : exits the app

.  Refer to <<Features>> for details of each command.

[[Features]]
== Features

====
*Command Format*

* Words in `UPPER_CASE` are the parameters to be supplied by the user e.g. in `add TASK_CONTENT`, `TASK_CONTENT` is a parameter which can be used as `add submission`.

* Items in `square brackets` are optional e.g `d/DESCRIPTION [p/PAYMENT_DETAIL]` can be used as `d/welcome tea p/food 12` or as `d/welcome tea`

* Items with `…`​ after them can be used multiple times including zero times e.g. `[p/PAYMENT_DETAIL]…`​ can be used as `` ``(i.e. 0 times), `p/food 12`, `p/food 12 p/drinks 7` etc
====

=== List out all current deadlines/payment forms: `list`

List out all current items with their index number+
Format: `list`

=== Adding a deadline: `deadline`

Adds a new deadline +
Format: `deadline d/DESCRIPTION t/TIME`

[TIP]
there can have spaces in the deadline description +
[TIP]
the format of time should be DD/MM/YYYY HHMM

Examples:

* `deadline d/submit venue payment t/05/10/2019 1159`

=== Adding a new payment: `payments`

Adds a new payment form with details +
Format: `payments d/DESCRIPTION [p/PAYMENT_DETAIL]...`

[TIP]
there can have spaces in the description and payment detail
[TIP]
there can be any number of payment details added

Examples:

* `payments d/welcome tea p/food 12`
* `payments d/maintenance fee`

=== Edit the deadline/payment form's description: `edit`

Edit a previously added task's description and details +
Format: `edit ID d/NEW_DESCRIPTION`

[TIP]
there can have spaces in the description
[TIP]
the id should not e out of range

Examples:

* `edit 2 d/welcome tea for freshmen`


=== Edit the deadline time: `reschedule`

Edit a previously added deadline's time +
Format: `reschedule ID t/NEW_TIME`

[TIP]
the id input should not be out of range
[TIP]
the format of time should be DD/MM/YYYY HHMM
[TIP]
to postpone the deadline for a short time, use `snooze` could be easier(see 3.7)

Examples:

* `reschedule 2 07/10/2019 2359`

=== snooze the deadline: `snooze`

snooze the deadline time by 1 hour +
Format: `snooze ID`

[TIP]
the id input should not be out of range


Examples:

* `snooze 5`

=== Edit the payment details: `redetail`

Edit a previously added payment's details +
Format: `redetail ID [d/PAYMENT_DETAIL]...`

[TIP]
the id input should not be out of range
[TIP]
there can be any number of details

Examples:

* `redetail 2 d/drinks 8 d/snacks 20`
* `redetail 2`(i.e. this operation removes all previous details)

=== Find a payment or deadline based on its description: `find`

Find a payment or deadline based on its description +
Format: `find d/DESCRIPTION`

[TIP]
there can have spaces in the description

Examples:

* `find d/welcome tea`

=== View deadline by schedule: `view`
View current deadlines in a specific date +
Format: `view t/DATE`

[TIP]
the results will be sorted based on their deadlines (i.e. the one with the earliest deadline will show on the top)
[TIP]
the format of the date should be DD/MM/YYYY

Examples:

* `view t/05/10/2019`

=== Delete a deadline/payment form: `delete`

Delete a deadline/payment from the task list +
Format: `delete ID`

[TIP]
the index of the task should not be out of range

Examples:

* `delete 3`

=== Delete a payee: `delete payee`

Delete a payee and their details +
Format: `delete payee p/payee`

Examples:

* `delete payee p/John`

=== Approve a payment form: `approve`

Approve a payment form with a message +
Format: `approve ID [m/MESSAGE]`

[TIP]
the index of the task should not be out of range

Examples:

* `approve 3 m/approved by xxx on Monday`
* `approve 3`

=== Mark a deadline as done: `done`

mark a deadline task as done +
Format: `done ID`

[TIP]
the index of the task should not be out of range

Examples:

* `done 5`

=== View previous input commands: `history`

view input commands entered by the user from the start till the present +
Format: `history`

=== Exit command: `bye`

exit from Duke +
Format: `bye`

=== Saving the data

Task List data are saved in the hard disk automatically after any command that changes the data. +
There is no need to save manually.


== Command Summary

* *list*: `list`
* *deadline*: `deadline d/DESCRIPTION t/TIME`
* *payments* : `payments d/DESCRIPTION [p/PAYMENT_DETAIL]...`
* *edit* : `edit ID d/NEW_DESCRIPTION`
* *reschedule* : `reschedule ID t/NEW_TIME`
* *snooze*: `snooze ID`
* *redetail*: `redetail ID [d/PAYMENT_DETAIL]...`
* *find* : `find d/DESCRIPTION`
* *view* : `view t/DATE`
* *delete* : `delete ID`
* *approve*: `approve ID [m/MESSAGE]`
* *done*: `done ID`
* *exit*: `bye`
