= Dolla - User Guide
:site-section: UserGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:


By: `Team [no name]`      Since: `Sep 2019`      Licence: `MIT`

== Introduction

Dolla is for those who *prefer to use a desktop app for keeping track of expenses*. Dolla is also optimized for users who prefer to use *Command Line Interface (CLI)* along with the benefits of a Graphical User Interface (GUI). 

<< insert GUI mockup here >>

== Quick Start

== Features

=== Set target saving `set saving`

Set target saving for a particular duration.

Format:

`*set saving* [AMOUNT] /for [DURATION]`

*NOTE*: `*[DURATION]*` can be daily, weekly, monthly or yearly.

Example:

* `set saving $300 /for every month`

=== Reminders `reminder`

Reminders for upcoming payments.

Format:

`*reminder*`

*NOTE*: Reminders will auto pop up with the greeting message.

Example:

* `reminder`

=== Set expense limit `set limit`

Set expense limit on particular types of spending.

Format:

`*set limit* /tag [TAG] [AMOUNT]`

Example:

* `set limit /tag bubble tea $20`


=== Add loans an debts `owe` `borrow`

Add loans and debts that are one off kind.

Format:

`*owe* [FRIEND] [AMOUNT] [DESCRIPTION]`

`*borrow* [FRIEND] [AMOUNT] [DESCRIPTION]`

Example:

* `owe xx $4 bubble tea`

* `borrow xx $10 lunch`

=== View statistics `stats`

View spending statistics using histograms

Format:

`*stats*`

Example:

* `stats`

=== Add to favourite `add favourite`

Add a favourite product 

Format:

`*add favourite* [LIST NO.]`

Example:

* `add favourite 3`

== FAQ

Q: 

== Command Summary

* `*set saving*` `set saving [AMOUNT] /for [DURATION]`

e.g. `set saving $300 /for every month`

* `*reminder*` `reminder`

e.g. `reminder`

* `*set limit*` `set limit /tag [TAG] [AMOUNT]`

e.g. `set limit /tag bubble tea $20`

* `*owe*` `owe [FRIEND] [AMOUNT] [DESCRIPTION]`

e.g. `owe xx $4 bubble tea`

* `*borrow*` `borrow [FRIEND] [AMOUNT] [DESCRIPTION]`

e.g. `borrow xx $10 lunch`

* `*stats*` `stats`

e.g. `stats`

* `*add favourite*` `add favourite [LIST NO.]`

e.g. `add favourite 3`
