= MisterMusik - User Guide
:site-section: UserGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/AY1920S1-CS2113T-F11-4/main

By: `Team CS2113T-F11-4`      Since: `Aug 2019`      Licence: `MIT`

== Introduction

MisterMusik is a scheduler program created for serious music students pursuing a professional music career as a western classical music performer.
The program is designed to automate and streamline most of the process in scheduling and organisation of materials, allowing the students to focus more on the important aspects of their education.

== Quick Start

. Ensure you have Java `11` or above installed in your computer
. Download the latest `MisterMusik.jar`
. Copy the file to the folder you want to use as the home folder for your MisterMusik
. Double-click the file to start the app. The GUI should appear in a few seconds.
. Type the command in the command box and press kbd:[Enter] to execute it. +
e.g. typing `help` and pressing kbd:[Enter] will open the help window.
+
. Refer to <<Features>> for details of each command.

[[Features]]
== Features

=== Help list : `help`

Brings up a list of available commands that the user can input.
It also displays a brief version of this user guide. +

Format: `help`

=== Reminders : `reminder`

Automatically displays the list of tasks over the next three days immediately after the program launches. +

Format: `reminder`

=== Adding a to-do task : `todo`

Adds a task defined by the user to the to-do list. +

Format: `todo <name of task>`

=== Adding an event task : `exam/recital/concert`

Adds an event defined by the user to the list of tasks.
The former and latter time inputs denote the start and end time respectively. +

. Examinations: `exam` +
Format: `exam <name of task> /dd-MM-yyyy HHmm HHmm`
+
. Recitals: `recital` +
Format: `recital <name of task> /dd-MM-yyyy HHmm HHmm`

For recurring events, please see <<Recurring events>>.

=== Recurring events : `lesson/practice`

MisterMusik allows the user to add recurring events e.g. weekly lessons.
The input format is as per normal with an extra recurring period input. +

Format: `<type of event> <name of event> /dd-MM-yyyy HHmm HHmm /period(days)` +

. Lessons : `lesson` +
Format: `lesson <name of task> /dd-MM-yyyy HHmm HHmm /period(days)`
+
. Practice sessions : `practice` +
Format: `practice <name of task> /dd-MM-yyyy HHmm HHmm /period(days)` +
e.g. “lesson Theory class /18-09-2019 0900 1030 /7”
adds a weekly recurring event starting on 18 September 2019.


=== Detecting clashes : `[coming in v2.0]`

MisterMusik automatically checks if an input event has a clashing date and time
with existing events in the list and informs the user of the clash.


=== Viewing schedules : `view`

Brings up a list of tasks for a particular date. +

Format: `view dd/MM/yyyy` +
e.g. “view 18/09/2019” displays all events/deadlines on/by the date 18 September 2019.


=== Checking for free days : `check`

The user can check for the nearest days that are free. +

Format: `check`

=== Marking a task as done: `done`

Marks a task in the list as completed, denoted by a tick when displaying the task. +

Format: `done <task index>` +
e.g. “done 5” marks task number 5 as done.


=== Rating a practice session

The user can rate the efficiency of a particular practice session after completing it.
When the practice session is marked as done,
the user will be prompted to add an efficiency rating and any extra comments or feedback.

=== Adding details to events

The user can add any extra details to an event when adding it to the task list.
For practice sessions or lessons, it can be used to take feedback from instructors and lesson notes respectively. +

Format: `details <task index> <detail text>` +
e.g. "details 5 Theory lesson on complex rhythm"
adds the description of the lesson.

=== Saving the task list

Each time the task list has been modified,
it will be automatically saved as a text file to the hard drive
thus preventing loss of data from crashes.

=== Exiting the program : `bye`

Exits the program. +

Format: `bye`

== FAQ
*Q:* How do I transfer my data to another Computer? +
*A:* Install the app in the other computer and overwrite the empty data file
it creates with the file that contains the data of your previous folder.

== Glossary

. Event: an event refers to any activity with a start time


== Command Summary

* *Bye :* `bye`
+
* *Check :* `check`
+
* *Delete :* `delete` +
e.g. `delete 2`
+
* *Details :* `details <task index> <detail text>` +
e.g. `details 5 Theory lesson on complex rhythm`
+
* *Done :* `done <task index>` +
e.g. `done 1`
+
* *Exam :* `exam <name of task> /dd-MM-yyyy HHmm HHmm` +
e.g. `exam CG2271 midterm /08-10-2019 1400 1600`
+
* *Find :* `find KEYWORD [MORE_KEYWORDS]` +
e.g. `find CS Project`
+
* *Help :* `help`
+
* *Lesson :* `lesson <name of lesson> /dd-MM-yyyy HHmm HHmm` +
e.g. `lesson Theory class /18-09-2019 0900 1030 /7`
+
* *List :* `list`
+
* *Practice :* `practice <name of task> /dd-MM-yyyy HHmm HHmm` +
e.g. `practice Bach Chaconne /25-10-2019 1300 1400`
+
* *Recital :* `recital <name of task> /dd-MM-yyyy HHmm HHmm` +
e.g. `recital violin /27-11-2019 2000 2100`
+
* *Reminder :* `reminder`
+
* *Todo :* `todo <name of task>` +
e.g. `todo CG homework`
+
* *View :* `view dd/MM/yyyy` +
e.g. `view 25/09/2019`
