= User Guide

== 1. Introduction
Our project aims to develop a task tracking application that monitors and encourages productivity. The application will be easy to use, with intuitive ways of adding, finding and tracking tasks that have been added. This easy convenience is definitely helpful in our often busy lives, so give this app a chance to help you!

This user guide aims to help you learn your way around our app, making the learning process smooth and effortless. So what are you waiting for? Let's go!

== 2. Quick Start  

  1. Ensure you have Java `11` or above and Gradle installed in your Computer.
  2. Open up your command prompt (for Windows) or terminal (for Mac). 
  3. Clone from the main into your Computer.
  4. Run command ./gradlew run (for Windows) or gradlew run (for Mac).
  5. Some example commands you can try:

* *`list`* : lists all tasks
* **`deadline assignment /by 9/9/2019`** : adds a deadline type task with description `assignment` to the task list.
* **`delete`**`1` : deletes the 1st task in the current list
* *`bye`* : exits the app
 
== 3A. Features 
*Command Format*

* Words in `UPPER_CASE` are the parameters to be supplied by the user e.g. in `todo DESCRIPTION`,
  `DESCRIPTION` is a parameter which can be used as `todo read book`.

=== 3A.1 Adding a task : `todo/deadline/event/doafter/range`
Adds a todo/deadline/event/doafter/range to the tasklist.

Format: `todo DESCRIPTION`  
        `deadline DESCRIPTION /by dd/mm/yyyy hhmm`  
        `event DESCRIPTION /at dd/mm/yyyy hhmm`  
        `doafter DESCRIPTION /after TASK`
        `range DESCRIPTION /in d/M/uuuu HHmm and d/M/uuuu HHmm`
        
  - `DESCRIPTION` is the description of the task.
  - `dd/mm/yyyy hhmm` is the day/month/year and time(24hrs) of the task e.g. `9/9/2019 1200`
  - `TASK` is a task that has been previously added, seeing that a DoAfter task can only be added after an existing task before it has been defined.
  - `d/M/uuuu HHmm` indicates the dates and times that a range task has to be done within.
  
Examples:

* `todo read book`
* `deadline homework /by 8/8/2019 2359`
* `event team meeting /at 20/8/2019 1500`
* `doafter return book /after read book`
* `range attend workshop /in 21/09/2019 1600 and 21/09/2019 1800`

=== 3A.2 Deleting a task : `delete`
Deletes the specified task from the task list. +
Format: `delete INDEX`

****
* Deletes the task at the specified `INDEX`.
* The index refers to the index shown in the displayed task list.
* The index must be a positive integer 1, 2, 3, ...
****

Examples:

 * `list` +
   `delete 2` +
   Deletes the 2nd task in the task list.
  
=== 3A.3 Finding tasks : `find`

Finds tasks whose description contains the given keyword. + 
Format: `find KEYWORD`

****
* The search is case sensitive. e.g. `Book` will not match `book`
* Only the description is searched.
* Only full words will be matched e.g. `books` will not match `book`
****

Examples:

* `find book` +  
  Returns any task with the descriptions containing the keyword.

=== 3A.4 Marking a task as done : `done`

Marks a task in the task list as done. DoAfter tasks can only be marked as done when the task before it has been marked as done. +
Format: `done INDEX`

****
  * Marks the task as done at the specified `INDEX`
  * The index refers to the index shown in the displayed task list.
****

Examples:

  * `done 1` +  
  Marks the 1st task in the task list as done.

=== 3A.5 Listing all the tasks : `list`

Shows a list of all the tasks in the task list. + 
Format: `list`

=== 3A.6 Snoozing a task : `snooze`

Provides a way to easily snooze/postpone/reschedule a task. +
Format: `snooze INDEX` +
        `NUMBER min/hour/day/week/month` OR `dd/mm/yyyy hhmm`
        
****
* Snoozes the task as done at the specified `INDEX`
* The index refers to the index shown in the displayed task list.
* `NUMBER` refers to the quantity of the `min/hour/day/week/month`
* `dd/mm/yyyy hhmm` is the day/month/year and time(24hrs) of the task e.g. `9/9/2019 1200`
****

Examples:

  * `snooze 1` +  
    `1 week` +
    Snoozes the 1st task in the task list by 1 week.
    
  * `snooze 2` +
    `9/9/2019 1200` +
    Reschedules the 2nd task in the task list to the input date (9/9/2019 1200).
  
=== 3A.7 Reminders : `remind`

Reminds the user when there is only one day left for tasks/events. Reminders also show up at the start of the program without any need to input command if there is only one day left for tasks/events. +
Format: `remind`

=== 3A.8 Viewing my Schedule : `show`

Prints the schedule for a user defined date. +
Format: `show DATE`

****
* Shows the tasks in the schedule for the specified `DATE`
* The `DATE` should be in dd/MM/yyyy format.
****

Examples:

****
* `show 30/10/2019` +
   Shows all task scheduled for 30/10/2019.
****

=== 3A.9 Exiting the program : `bye`

Exits the program. +
Format: `bye`

=== 3A.10 Saving the data

Save the tasks in the hard disk automatically whenever the task list changes.
There is no need to save manually.

=== 3B. Future Features to Implement +
These are the features that are discussed to bw implemented in the coming future. Note that these
are just tentative and subject to changes

=== 3B.1 Mode Select : `[directional] buttons`

Changes the mode such as 'main', 'stopwatch', 'spend points' such that each mode takes in specified
command line prompts.

=== 3B.2 Points System +
Contains functions to purchase items off the 'point shop'

****
* Every completed tasks on time or countdown timer that runs it's full course will have points added
into the user's database
* These points  can be used to purchase comestic value of the application.
****

Examples:
****
* `buy hat 3` +
User will purchase index 3 (1 index) of the hat off the shop.
****

=== 3B.3 Hero System +
Contains functions related to the user's hero.

****
* Hero will be a personalized avatar that the user can customize based off their producitivity
* The longer they play, the more personalized and "stronger" the hero can look.
****

Examples:
****
* `play run` +
User's hero run animation will be played on the screen.
****


=== 3B.4 Stopwatch : `countdown` +

Starts a exitable countdown. +
Format: `countdown TIMEINMINUTES`

****
* User earns points based off how long the countdown was given.
****

Examples:

****
* `countdown 60` +
   Start a countdown for 60 minutes.
****

== 4. FAQ

*Q*: Where do I install Java 11 from? +  
*A*: Java 11 can be downloaded from the Oracle website. https://www.oracle.com/technetwork/java/javase/downloads/index.html

== 5. Command Summary

* *Add*: `todo DESCRIPTION` `deadline DESCRIPTION /by dd/mmm/yyyy hhmm` `event DESCRIPTION /at dd/mm/yyyy hhmm` `doafter DESCRIPTION /after TASK`  `range DESCRIPTION /at d/M/uuuu HHmm and d/M/uuuu HHmm` +
  e.g. `todo read book` `deadline homework /by 8/8/2019 2359` `event team meeting /at 20/8/2019 1500` `doafter return book /after read book` `range workshop /in 22/09/2019 1900 and 22/09/2019 2100`
* *Delete*: `delete INDEX`  +  
  e.g. `delete 3`
* *Find*: `find KEYWORD` +
  e.g. `find book`
* *Done*: `done INDEX` +
  e.g. `done 2`
* *List*: `list`
* *Snooze*: `snooze`
* *Remind*: `remind`
* *Show*: `show`
* *Bye*: `bye`
