= Dr Duke User Guide

# Usage

Since there is a lot of fairly complex data to manage, I think the input system will have to be stateful - different commands mean different things based on the current context. This would require some tracking and interfacing between the UI and the Logic (e.g. the internal logic needs to know which patient is being displayed as patient #1). If user input is ambiguous, we can show a window of possible options to disambiguate between. The disambiguation window and code can be reused - create an abstract DukeObject class for our data items.

Specification syntax:

* `[]` -> optional element of a command
* `<>` -> variable input, specified within bracket
* `(a|b|c)` -> input that can be one of several possible options, in this case `a`, `b` or `c`
* `"<>"` -> string, must be surrounded by quotes if it contains a space, and cannot start with a -
* `[]*` -> 0 or more of the contents of [], separated by spaces

Reused patterns:

* _patient_id_: `(<patient index>|"part of name>"|-b <bed number>)`
* _string_or_idx_: `(<index>|"<search string>")`
** `<index>` refers to the index assigned to the object in the display. `<search string>` will be searched for in the names of all relevant objects.

Parsing rules:

* Switches can be in any order
* Switches with optional parts of their names can be recognised with any portion of the optional part. E.g. `-crit` matches `-c[ritical]`

## Contexts

Commands that are present in multiple contexts will be mentioned in just one context, and all contexts in which they are available will be listed.

### Home 

Show several (10?) numbered panels displaying a summary of the critical details of some Patients: name, bed number, primary diagnosis, and number of critical issues.

#### `help` - Display a context-specific list of commands and options [[home-help]]

Format: `help`

_Available in:_ <<Home>>, <<Patient>>, <<Impression>>, <<Result>>, <<Observation>>, <<Investigation>>, <<Medicine>>, <<Plan>>

This will be available in every context, and will function essentially the same way, just with different commands.

#### `next` - Display next page of Patients [[home-next]]

_Remove if we can have a scrolling display of Patients instead_

Format: `next` 

_Available in:_ <<Home>>, <<Patient>>, <<Impression>> 

#### `prev` - Display next page of Patients [[home-prev]]

_Remove if we can have a scrolling display of Patients instead_

For different contexts, scrolls forward in all lists that can be scrolled.

Format: `prev`

_Available in:_ <<Home>>, <<Patient>>, <<Impression>>

For different contexts, scrolls backward in all lists that can be scrolled.

#### `critical` - Display all critical observations and plans of all Patients [v2.0?]

Format: `critical`

We can probably cheat and use the disambiguation engine to pull up a window of all critical dukeobjects, giving the user the choice to navigate to any particular one, or to close the window

#### `discharge` - Generate a discharge report for the Patient and delete him from the system [[home-discharge]] 

Format: `discharge _patient_id_ [-s[ummary] <discharge summary>]`

The discharge report will contain all information being tracked regarding the Patient, and an optional discharge summary that can be specified in the command. In v1.4, Patients will simply be deleted after the report is generated. In v2.0, they will be archived.

#### `archive` - Display discharged Patients  [v2.0]

Format: `archive`

#### `open` - Go to a more detailed view of a particular Patient

Format: `open _patient_id_ [-i[mpression] [<impression index>]]`

If a string is supplied, search for the name and present a list of results (either through the cli or just a pop-up search window). If the `-b` switch is used, look up the bed number. If the `-i` switch is used, go to the impression specified by the index, or go to the primary impression for that particular Patient if no index is specified. 

#### `new` - Add a new Patient to the system

Format: `new -n[ame] "<name>" -b[ed] <bed number> -a[llergies] "<allergies>" [<optional switches>]`

Optional switches:

* `-g[o]`
* `-h[eight] <height>` 
* `-w[eight] <weight>` 
* `-ag[e] <age>`
* `-num[ber] <number>`
* `-ad[dress] "<address>"`
* `-hi[story] "<history>"`

The Patient's name, bed number and allergies must be specified. The other fields are assigned to `null` by default but can be edited later on. The `-g[o]` switch goes to the Patient's page after it is created.

### Patient 

Show a detailed view of a Patient, displaying in separate panels:

* All personal details
* A list of critical Observations and Plan items
* A list of Investigations to follow up on
* Each Impression, with its name and an excerpt of its description

Inherits: <<home-help,`help`>>, <<home-next,`next`>>, <<home-prev,`prev`>>

#### `back` - Go back to previous context [[patient-back]]

Format: `back`

_Available in:_ <<Patient>>, <<Impression>>, <<Result>>, <<Observation>>, <<Investigation>>, <<Medicine>>, <<Plan>>

This will go back to the context that the user came from. A context stack will be maintained.


#### `up` - Go up to next-higher context [[patient-up]]

Format: `up`

_Available in:_ <<Patient>>, <<Impression>>, <<Result>>, <<Observation>>, <<Investigation>>, <<Medicine>>, <<Plan>>

This will go to the context hierarchically above the user's context. In this case, it will go back to <<Home>>. For an <<Impression>>, it would go back to the <<Patient>> associated with it.

#### `new` - Add a new Impression to this Patient

Format: `new -n[ame] "<name>" -d[escription] "<description>"`

#### `open` - Open a critical or investigation item listed on the page, or an Impression

Format: `open ("<search string>"|-c[ritical] _string_or_idx_|-in[v(x|estigation)] _string_or_idx_|-i[mpression] _string_or_idx_)`

#### `edit` - Edit one of the details of the Patient

Format: `edit [-a[ppend]] <switch> [<new value>] [<switch> [<new value>]]`

If `<new value>` is not supplied, open a text box with the current value loaded inside, for the user to edit. `-a` will append `<new value>` to the current value for string-valued fields. 

Switches and corresponding new value format:

* `-n[ame] "<name>"`
* `-b[ed] <bed number>`
* `-a[llergies] "<allergies>"`
* `-h[eight] <height>` 
* `-w[eight] <weight>` 
* `-ag[e] <age>`
* `-num[ber] <number>`
* `-ad[dress] "<address>"`
* `-hi[story] "<history>"`

#### `discharge` - Generate a discharge report for the Patient and delete him from the system

Format: `discharge [-s[ummary] <discharge summary>]`

Functionally the same as <<home-discharge,`discharge` in the Home context>>.

### Impression

Show a detailed view of an Impression, displaying in separate panels:

* The name and full description of the Impression
* A list of Evidence for the Impression, sorted by default with critical items first
* A list of Treatments for the Impression, sorted by default with critical items first, followed by investigations that require follow-up
* The patient's allergies

Inherits: <<home-help,`help`>>, <<home-next,`next`>>, <<home-prev,`prev`>>, <<patient-back,`back`>>, <<patient-up,`up`>>
