= ModPlan v1.1 - User Guide
:site-section: UserGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/AY1920S1-CS2113T-F10-1/main

By: `Team SE-EDU`      Since: `Jun 2016`      Licence: `MIT`

== Introduction

**ModPlan**

Your one stop solution to module planning through out your university tenure! + 
ModPlan is a module planning system that expands on NUSMODS to help NUS Computer Engineering students to plan their modules for all four years of their bachelor's degree.

== Quick Start

.  Ensure you have Java `11` or above installed in your Computer.
.  Download the latest `addressbook.jar` link:{repoURL}/releases[here]. (change this)
.  Copy the file to the folder you want to use as the home folder for your Address Book.
.  Double-click the file to start the app. The GUI should appear in a few seconds.
+
.  Type the command in the command box and press kbd:[Enter] to execute it. +
.  Some example commands you can try:

* *`list`* : lists all tasks
* **`add`**`n/John Doe p/98765432 e/johnd@example.com a/John street, block 123, #01-01` : adds a contact named `John Doe` to the Address Book.
* **`delete`**`3` : deletes the 3rd contact shown in the current list
* *`exit`* : exits the app

.  Refer to <<Features>> for details of each command.

[[Features]]
== Features

====
*Command Format*

* Words in `UPPER_CASE` are the parameters to be supplied by the user e.g. in `add n/NAME`, `NAME` is a parameter which can be used as `add n/John Doe`.
* Items in square brackets are optional e.g `n/NAME [t/TAG]` can be used as `n/John Doe t/friend` or as `n/John Doe`.
* Items with `…`​ after them can be used multiple times including zero times e.g. `[t/TAG]...` can be used as `{nbsp}` (i.e. 0 times), `t/friend`, `t/friend t/family` etc.
* Parameters can be in any order e.g. if the command specifies `n/NAME p/PHONE_NUMBER`, `p/PHONE_NUMBER n/NAME` is also acceptable.
====

=== Adding a person: `add`

Adds a person to the address book +
Format: `add n/NAME p/PHONE_NUMBER e/EMAIL a/ADDRESS [t/TAG]...`

[TIP]
A person can have any number of tags (including 0)

Examples:

* `add n/John Doe p/98765432 e/johnd@example.com a/John street, block 123, #01-01`
* `add n/Betsy Crowe t/friend e/betsycrowe@example.com a/Newgate Prison p/1234567 t/criminal`

// tag::delete[]
=== Deleting a person : `delete`

Deletes the specified person from the address book. +
Format: `delete INDEX`

****
* Deletes the person at the specified `INDEX`.
* The index refers to the index number shown in the displayed person list.
* The index *must be a positive integer* 1, 2, 3, ...
****

Examples:

* `list` +
`delete 2` +
Deletes the 2nd person in the address book.
* `find Betsy` +
`delete 1` +
Deletes the 1st person in the results of the `find` command.

// end::delete[]


=== Listing all persons : `list`

Shows a list of all persons in the address book. +
Format: `list`

=== Locating tasks in the list by name: `find`

Finds tasks from the task list whose description or date/time contain any of the given keywords. +
Format: `find KEYWORD`

****
* The search is case insensitive. e.g `event` will match `Event`
* Part of the description will also be searched. e.g 'as' will match 'has', 'class' etc.
* Searching for the full date/time must be done in the dd-mm-yyyy format to match the task list.
****

Examples:

* `find event` +
Returns `event` and `this event`

=== Rescheduling tasks: `reschedule`

Reschedules a certain task to a different date and time. + 
Format: `reschedule INDEX DATE TIME`

****
* The index of the task must be valid (i.e the task's index must be in the task list).
* A valid date and time must be inputted in the format that the program understands.
* The date and time inputted must be an open timing, if there are clashes the program will warn the user about the clashing timing.
****

=== Schedule of the day: `schedule`

Lists the schedule one has for a specific date. +
Format: `schedule DATE`

****
* A valid date must be inputted in the format that the program understands.
* The list will be sorted from earliest to latest.
****

=== Reminders: `reminder`

Reminds the user upon startup of the program of any upcoming tasks.

****
* Notifies for any task due within the next 6 hours.
* Rechecks every hour for new upcoming tasks.
****

=== Exiting the program : `bye`

****
*Typing `bye` into the command line shows a goodbye message, saves the task list, and closes the program.
****

Exits the program. +
Format: `bye`

=== Saving the data

Task list data are saved in the hard disk automatically after any command that changes the data. +
There is no need to save manually.

== FAQ

*Q*: How do I transfer my data to another Computer? +
*A*: Install the app in the other computer and overwrite the empty data file it creates with the file that contains the data of your previous Address Book folder.

== Command Summary

* *Add* `add n/NAME p/PHONE_NUMBER e/EMAIL a/ADDRESS [t/TAG]...` +
e.g. `add n/James Ho p/22224444 e/jamesho@example.com a/123, Clementi Rd, 1234665 t/friend t/colleague`
* *Delete* : `delete INDEX` +
e.g. `delete 3`
* *Find* : `find KEYWORD [MORE_KEYWORDS]` +
e.g. `find James Jake`
* *List* : `list`
