= MisterMusik - User Guide
:site-section: UserGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/AY1920S1-CS2113T-F11-4/main

By: `Team CS2113T-F11-4`      Since: `Aug 2019`      Licence: `MIT`

== Introduction

MisterMusik is a scheduler program created for serious music students
pursuing a professional music career as a western classical music performer.
The program is designed to automate and streamline most of the process in scheduling and organisation of materials,
allowing the students to focus more on the important aspects of their education.

== Quick Start

. Ensure you have Java `11` or above installed in your computer
. Download the latest `mistermusik.jar`
. Copy the file to the folder you want to use as the home folder for your MisterMusik
. Double-click the file to start the app. The GUI should appear in a few seconds.
. Type the command in the command box and press kbd:[Enter] to execute it. +
E.g. typing `help` and pressing kbd:[Enter] will open the help window.
+
. Please refer to <<Features>> for details of each command.

[[Features]]
== Features

=== Help list :

Brings up a list of available commands that the user can input.
It also displays a brief version of this user guide. +

Format: `help`

=== Reminders : `reminder`

Displays the list of tasks over the next three days. +

Format: `reminder`

=== Adding a to-do task : `todo`

Adds a task defined by the user to the to-do list with a deadline. +

Format: `todo <name of task> /dd-MM-yyyy` +
E.g. `todo complete theory homework /10-10-2019`
adds a deadline to complete the user's theory homework by 10 October 2019.

=== Adding an event task :

Adds an event defined by the user to the list of tasks.
The former and latter time inputs denote the start and end time respectively. +

For recurring events, please see <<Recurring events :, Recurring events>>.

. Practice sessions : `practice` +
Format: `practice <name of practice> /dd-MM-yyyy HHmm HHmm`
+
. Examinations: `exam` +
Format: `exam <name of exam> /dd-MM-yyyy HHmm HHmm`
+
. Recitals: `recital` +
Format: `recital <name of recital> /dd-MM-yyyy HHmm HHmm`
+
. Concerts : `concert` +
Format: `concert <concert name> /dd-MM-yyyy HHmm HHmm/<cost of concert>` +
Note: Cost of concert must be an integer (for simplicity regarding budgeting).


=== Recurring events :

MisterMusik allows the user to add recurring events (e.g. weekly lessons).
The input format is as per normal with an extra recurring period input.
This only works with lesson and practice type events. Concerts, exams and
recitals cannot be entered as recurring events.

Format: `<type of event> <name of event> /dd-MM-yyyy HHmm HHmm /period(days)`

E.g. “lesson Theory class /18-09-2019 0900 1030 /7”
adds a weekly recurring event from 9:00am to 10:30am, starting on 18 September 2019.

=== Calendar Table
The calendar table is generated from the `EventList`. It prints on the screen a table of calendar of 7 days
starting from a specified day, including the events within this time period. +

==== Commands for CalendarView
- `calendar` This prints the calendar table of this 7 days.
- `calendar next` This prints the calendar table of the next 7 days.
- `calendar last` This prints the calendar table of the last 7 days.


=== Viewing schedules : `view`

Brings up a list of tasks for a particular date. +

Format: `view dd-MM-yyyy` +
E.g. “view 18-09-2019”
displays all events/todos on/by the date 18 September 2019.


=== Checking for free days : `check`

The user can check for the nearest days that are free.
This will list the next 3 free days on the users' schedule. A
day is considered free if there are no events scheduled. ToDos are not counted
as events.

Format: `check`


=== Marking a task as done: `done`

Marks a ToDo in the list as completed, denoted by a tick when displaying the task.
This functionality does not work for events that are not ToDos. +

Format: `done <task index>` +
E.g. “done 5” marks task number 5 as done.


=== Rating a practice session : `[coming v1.4]`

The user will be able to rate the efficiency of a particular practice session after completing it.
When the practice session is marked as done,
the user will be prompted to add an efficiency rating and any extra comments or feedback. +

Format: `rate <task index>`


=== Adding details to events : `[coming v1.4]`

The user will be able to add any extra details to an event when adding it to the task list.
For practice sessions or lessons,
it can be used to take feedback from instructors and lesson notes respectively. +

Format: `details <task index>` or `notes <task index>`


=== Rescheduling events :

The user will be able to reschedule an existing event. +

Format: `reschedule <task index> dd-MM-yyyy HHmm HHmm`


=== Searching for a free slot : `[coming v1.4]`

The user will be able to search for any days within the next 2 weeks
that contains a specified period of time that is free. +
For example, searching for a 4h free slot
will display all the dates within the 2 weeks with
at least 4 hours of free time in the schedule. +

Format: `searchfree 4h`

=== Search

The user is able to search for a specific event/task using keywords.

Format: `find <keyword>` will display all events/tasks previously entered
containing the desired keyword.

=== Edit an event/ToDo
The user is able to edit the name of the event/ToDo he entered in case he entered it wrongly.

Format: `edit <index for edition>/<new description>`


=== Contact management : `contact`
The user is able to add, delete, view, and edit contacts information of an event.
A contact includes name, email address, and phone number.

==== Add contact item
Format: `contact add <event index> /<name>, <email>, <phone number>`

==== Delete contact item
Format: `contact delete <event index> <contact index> /`

==== View contact
Format: `contact view <event index> /`

==== Edit contact item
Format: `contact edit <event index> <contact index> <edit type> /<new contact information>` +
The edit types are name, email, and phone.

=== Checklists
Checklist of each event can be used to remind users of certain items (e.g. bring glasses to concert).
This is implemented by storing an array list of strings in `Event` objects.

Checklist implementation contains 4 operations:

==== add checklist item
`checklist add <event index>/<checklist item>`
This adds an item into a specific event's checklist.

==== view checklist
`checklist view <event index>`
This prints on the screen the checklist of an event.

==== edit checklist item
`checklist edit <event index> <item index>/<new item>`
This edits a specific item in the checklist of an event.

==== delete checklist item
`checklist delete <event index> <item index>`
This deletes an item from the checklist of an event.

=== Goals list
Goals list of each event helps the user keep track of the outcome that they wishes to achieve by the end of the event.
The user is able to add, edit, delete or set a goal as achieved.

==== Adding a goal
`goal add <event index>/<input goal>`
This adds a goal to a specific event.

==== Editing a goal
`goal edit <event index> <goal index>/<new input goal>`
This edits an existing goal.

==== Deleting a goal
`goal delete <event index> <goal index>`
This deletes a specified goal.

==== Setting a goal as achieved
`goal achieved <event index> <goal index>`
This sets the specified goal as achieved.

==== Viewing the goal list
`goal view <event index>`
This displays the goals list of a specified event along with their status - whether a goal is achieved or not.

=== viewing monthly costs of concerts
The total cost of concerts each month can be viewed by the user using the
`budget` command.

Format: `budget MM-yyyy` symbolising the month and year the user wishes to take a look at. +
Note: MM must be a two digit value. For example, the month of may, 2019 must be entered as
`05-2019` instead of `5-2019`.

=== Exiting the program : `bye`

Exits the program. +

Format: `bye`


== Additional Features

=== Detecting Clashes :

When the user inputs a new event, MisterMusik will check
if it has any clashing date and time with existing events
and warns the user of the clash. This also detects clashes
when recurring events are entered, so there is no need
to manually check for schedule clashes.

=== Sorting By Date :

MisterMusik will automatically sort the list by the date and time of each task
so the user will not have to manually prioritise each event and todo task. ToDos
are listed at the front of each day as they do not have an included time.

=== Reminder for specific task types : `[coming v2.0]`

The user will be able to get reminders of specific task type using the reminder command
and specifying which type they would like to be displayed. +

E.g. “reminder exam”
displays a reminder of all exam events within the next 3 days.

=== Budget handling system

The system allows for the user to handle their own monthly budget. There is a set budget
for each month (fixed at $50 initially) that stops users from entering new concerts into
the schedule if that new concert would cause the costs of concerts for the month to exceed
the stipulated budget.

For example, if the list contains a concert on the 4th of July, 2019 that costs $49,
entering a new concert that costs more than a dollar would causes the system to cancel the
operation as it would lead to monthly costs of $51 that exceeds the monthly budget of $50.

The user also has the ability to change the stipulated budget for each month or universally if
he/she wishes to (Coming in v1.4).

== FAQ
*Q:* How do I transfer my data to another Computer? +
*A:* Install the app in the other computer and overwrite the empty data file
it creates with the file that contains the data of your previous MisterMusik folder.


== Glossary

. Event: an event refers to any activity with a start and end time, includes
concerts, practices, exams, and recitals.
+
. Todo: a todo refers to a task with a deadline specified by the user.
