= OPTIX - User Guide

== Introduction

Optix is a command line interface for theatre managers. It allows users to add theatre bookings by performance groups to the selection. It also allows users to allocate seats to audience members. Finally, the finances can be tracked and tabulated for accounting.

== Quick Start

  1. Ensure that Java 11 or above is installed on your computer.
  2. Download the latest optix.jar here.
  3. Copy the file to the folder you want to use as the home folder for your theatre bookings.
  4. Double-click the file to start the application. The GUI should appear in a few seconds.
  5. Type the command in the command box and press Enter to execute it (e.g. type help and press enter to open the help window.)
  6. Some example commands you can try:
    a. *`add`* `Phantom of the Opera|5/5/2020|2000` : adds a show called `Phantom of the Opera` to be scheduled on the `5th of May 2020`, with a payment of `$2000` for the booking.
    b. *`list`*: `list` all shows currently added.
    c. *`delete-one`* `Phantom of the Opera|5/5/2020` : finds a show called `Phantom of the Opera` scheduled on the `5th of May 2020` within the current list of shows, and deletes it.
    d. *`bye`*: exits the application


