= Entertainment-Pro : User Guide
:site-section: UserGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/AY1920S1-CS2113T-T09-4/main

By: `CS2113T-T09-4`      Since: `Sep 2019`

== Introduction

Our Javafx app is primarily targeted at people in Singapore who have huge love and interest for movies and TV shows. Our app hence aims to provide a fast and efficient way to find and/or do movies and TV shows related stuff such as getting ratings and reviews for a particular movie and/or TV shows and etc. 

Most importantly, the app is also intended for people who prefer desktop apps over other types of apps, have the ability to type fast and prefer typing over other means of input. As such, the app will have a GUI (Graphical User Interface) but most of the user interactions will happen using a CLI (Command Line Interface). 

Interested? Jump to the Section 2, “Quick Start” to get started. Enjoy!

== Quick Start

.  Ensure you have Java `11` (revision `11` or later) installed in your Computer.
+
[NOTE]
Only Java 11+ is supported. +
This app may not work with older major Java releases such as Java 10, 9, 8 etc.
+
. Download the latest entertainmentpro.jar here.
. Copy the file to the folder you want to use as the home folder for your Address Book.
. Double-click the file to start the app. The GUI should appear in a few seconds.
. Type the command in the command box and press Enter to execute it.
     e.g. typing help and pressing Enter will open the help window.
. Some example entertainment.pro.logic.parsers.commands you can try:
* *`search new movie:`* displays all the current movies that are showing on cinemas 
* *`search upcoming movie:`* displays all the upcoming movies
* *`display cinema:`* displays the location of all the nearby cinemas
* *`exit the apprch new movie:`* displays all the current movies that are showing on cinemas 
. Refer to Section 4, “Features” for details of each command.

[[Features]]
== Features

*Command Format*

* Every command used in EntertainmentPro strictly follows a default command structure: `<root command>` `<sub-root>` `<payload>` `<flags>`.

* The structure for `[flags]` can be `-<key>` `<flag title>` or simply `-<key>`.

* Both the root command and the sub-root are one worded each, while payload and flag title can multi-worded.

* Payload and flags may not needed depending on the particular command.

* Words in `UPPER_CASE` are the parameters (i.e. payload) to be supplied by the user e.g. in `search movies QUERY_KEYWORDS`, `QUERY_KEYWORDS` is a parameter which can be used as `search movies harry potter`.

* Items in square brackets are optional (i.e. flags) e.g. `QUERY_KEYWORD [-g/GENRE_NAME]` can be used as `harry potter -g fantasy` or as `harry potter`.

* Square brackets with `...` inside them can have multiple flag titles (but at least 1), with each flag title separated by a `,` e.g. `-g GENRE_NAME ...` can be used as `-g fantasy`, `-g fantasy, animation` etc.

* Some commands provide the option of multiple flagging at once but the each flags can still be used individually with the command.

=== Viewing help: `help`

Retrieves help information about each root command.
Format: `help ROOT_COMMAND`

[TIP]
Keying in `help me` displays the list of all possible root commands

Examples:

* `help search`
* `help preference`

=== User Personalisation

==== Setting user profile: `set`

Sets values to the individual components of the user profile. +
*_All existing values will be overwritten by the new value._*

* *name* +
Sets name to user profile. +
Format: `set name USER_NAME` +
Examples: `set name Duke` +

* *age* +
Sets age to user profile. +
Format: `set age USER_AGE` +
Examples: `set age 20` +
** `USER_AGE` *must be a positive integer*.


* *preferences and/or adult filter* +
Sets adult filter preference and genre preferences. +
Format: `set preference [-a YES_NO] [-g GENRE_NAME ...]` +
Examples: +
`set preference -a yes` +
`set preference -a yes -g fantasy , comedy` +
** `YES_NO` must be either "yes" or "no".
*** "yes" indicates to allow adult content.
*** "no" indicates to restrict adult content.
** `[-a YES_NO]` will only be set if user's age is over 21.
** At lest *one* of the optional fields must be provided.
** `GENRE_NAME` cannot already belong to restrictions. +
** `GENRE_NAME` must be a valid genre name.

* *restrictions* +
Sets genre restrictions. +
Format: `set restrictions [-g GENRE_NAME ...]` +
Examples: `set restrictions -g horror , history` +
** `GENRE_NAME` cannot already belong to preferences. +
** `GENRE_NAME` must be a valid genre name.

* *sorting method* +
Sets sorting method of displaying search results.
Format: `set sort SORT_INDEX`
Examples: +
`set sort 1` -> to sort by alphabetical order +
** `SORT_INDEX` must be an integer ranging from 1 to 3.
*** "1" indicates to sort by alphabetical order.
*** "2" indicates to sort by latest release date first.
*** "3" indicates to sort by highest rating first.

==== User preferences: `preference`

Edits the user's preferences by *add*, *remove*, or *clear*. +

* *add* +
Adds on genres to genre preferences. +
*_Valid inout values will not overwrite existing values, but will be appended on to existing values._* +
Format: `preference add [-g GENRE_NAME ...]` +
Examples: `preference add -g action` +
** `GENRE_NAME` cannot already belong to preferences or restrictions. +
** `GENRE_NAME` must be a valid genre name.

* *remove* +
Remove genres from genre preferences. +
*_Valid inout values will not overwrite existing values, but will remove equivalent existing values._* +
Format: `preference remove [-g GENRE_NAME ...]` +
Examples: `preference remove -g comedy` +
** `GENRE_NAME` must already belong to preferences. +
** `GENRE_NAME` must be a valid genre name.

* *clear* +
Clears all genre preferences. +
*_All existing values will be removed._* +
Format: `preference clear`

==== User Restrictions: `restriction`

Edits the user's restrictions by *add*, *remove*, or *clear*.

* *add* +
Adds on genres to genre restrictions. +
*_Valid inout values will not overwrite existing values, but will be appended on to existing values._* +
Format: `restriction add [-g GENRE_NAME ...]` +
Examples: `restriction add -g action` +
** `GENRE_NAME` cannot already belong to preferences or restrictions. +
** `GENRE_NAME` must be a valid genre name.

* *remove* +
Remove genres from genre restrictions. +
*_Valid inout values will not overwrite existing values, but will remove equivalent existing values._* +
Format: `restriction remove [-g GENRE_NAME ...]` +
Examples: `restriction remove -g comedy` +
** `GENRE_NAME` must already belong to restrictions. +
** `GENRE_NAME` must be a valid genre name.

* *clear* +
Clears all genre restrictions. +
*_All existing values will be removed._* +
Format: `restriction clear`

=== Search for movies and TV shows: `search`

Searches for movies or TV shows using keywords and optionally, results can be filtered using specific genres and user profile.

==== *Searching for movies*: `movies` +

* *Searching within _standard lists_* +
Search within the standard provided lists of movies given. +
Format: `search movies [/LIST_TYPE]` +
Examples: +
`search movies /current` +
`search movies /upcoming` +
** `LIST_TYPE` must be one of the following valid inputs: +
*** `current` indicates to search within the list of movies that are currently showing in cinemas. +
*** `upcoming` indicates to search within the list of upcoming movies. +
*** `trend` indicates to search within the list of trending movies. +
*** `rated` indicates to search within the list of top-rated movies.+

* *Searching within standard lists _without filtering_* +
Format: `search movies [/LIST_TYPE` +
Examples: `search movies /current`

* *Searching within standard lists _using pre-set user profile_* +
Format: `search movies [/LIST_TYPE] -p` +
Examples: `search movies /rated -p`

* *Searching within standard lists _using new unsaved set of filter flags_* +
Format: `search movies [/LIST_TYPE] [-g PREFERENCE_GENRE_NAME ...] [-r RESTRICT_GENRE_NAME ...] [-a ADULT_FILER]` +
Examples: +
`search movies \current -g comedy -r horror , fantasy , -a yes` +
`search movies \current -r romance , -a no` +
** `PREFERENCE_GENRE_NAME` and `RESTRICTION_GENRE_NAME` cannot have any overlaps.
** `PREFERENCE_GENRE_NAME` and `RESTRICTION_GENRE_NAME` must be valid genre names.
** `[-a ADULT_FILTER]` will only be applied if user's age is > 21.

* *Searching using _keywords_* +
Search for movies using keywords and returns movies with titles that contains the keywords. +
Format: `search movies KEYWORDS` +
Examples: +
`search movies harry potter` +
`search movies joker`

* *Searching using keywords _with no preferences_* +
Format: `search movies KEYWORDS` +
Examples: `search movies harry potter`

* *Searching using keywords _using pre-set user profile_* +
Format: `search movies KEYWORDS -p` +
Examples: `searhc movies harry potter -p`

* *Searching using keywords _using new unsaved set of filter flags_* +
Format: `search movies KEYWORDS [-g PREFERENCE_GENRE_NAME ...] [-r RESTRICT_GENRE_NAME ...] [-a ADULT_FILER]` +
Examples: +
`search movies harry potter -g comedy -r horror , fantasy , -a yes` +
`search movies harry potter -r romance , -a no` +
** `PREFERENCE_GENRE_NAME` and `RESTRICTION_GENRE_NAME` cannot have any overlaps.
** `PREFERENCE_GENRE_NAME` and `RESTRICTION_GENRE_NAME` must be valid genre names.
** `[-a ADULT_FILTER]` will only be applied if user's age is > 21.

==== *Searching for TV shows*: `tvshows` +
* *current*: +
Search within movies currently showing in cinemas.
** *Without filtering* +
Format: `search shows /current`
** *Filtering according to pre-set user profile* +
Format: `search shows /current -p`
** *Filtering using new unsaved set of filter flags* +
Format: `search shows /current [-g PREFERENCE_GENRE_NAME ...] [-r RESTRICT_GENRE_NAME ...] [-a ADULT_FILER]` +
Examples: +
`search shows \current -g comedy -r horror , fantasy , -a yes` +
`search shows \current -r romance , -a no` +
*** `PREFERENCE_GENRE_NAME` and `RESTRICTION_GENRE_NAME` cannot have any overlaps.
*** `PREFERENCE_GENRE_NAME` and `RESTRICTION_GENRE_NAME` must be valid genre names.
*** `[-a ADULT_FILTER]` will only be applied if user's age is > 21.

=== View more information about particular movie/TV show: `view`




=== View information on movies and TV shows

EntertainmentPro allows you to get full details on specific details and TV shows. +
The details include:

. title:            the title of the movie or show
. summary:          a short description of the movie or show
. release date:     the date of release for the movie or show
. ratings:          the average given rating of the movie or show (max: 10.0)
. genres:           the genres of the movie or show
. cert:

== Overview of the interface
. Command Box: This is where users type entertainment.pro.logic.parsers.commands.
. Command Feedback: This shows the result of command execution in addition to useful tips and error messages.
. Preferences List: This shows the list of preferences users have set in the app.
. Movies List: This displays either the set of movies or information related to a particular movie with respect to users’ command.

