= PrivateHomeChefManager - User Guide
:site-section: UserGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/AY1920S1-CS2113T-T12-4/main

By: `AY1920S1-CS2113T-T12-4`      Since: `Aug 2019`

== Introduction

PrivateHomeChefManager is aimed at private home chefs who are familiar with and prefer using the command line for managing the administrative tasks of their business.
Main features of PrivateHomeChefManager include help user to keep track of customer’s bookings e.g. customer info, pax, booking dates, orders, etc.
Also, it helps users to store current recipes, which includes ingredients needed, preparation steps and rating.
Lastly, it helps users to keep track of ingredients in storage and able to check for stock availability.

== Quick Start

. Ensure you have Java 11 or above installed in your Computer.
. Download the latest `ChefDuke.jar` https://github.com/AY1920S1-CS2113T-T12-4/main/releases[here].
. Copy the file to the folder you want to use as the home folder for your PrivateHomeChefManager.
. Open a command window. Run the java -version command to ensure that you are using Java 11.
. Launch the Jar file by keying in java ‘-jar c:\path\to\jar\file.jar’ in the command window and press kbd:[Enter]. Replace c:\path\to\jar\file.jar with the actual path and file title of the downloaded Jar to run.
. Alternatively, you can navigate to the folder that includes the Jar in the command prompt first by entering ‘cd /’ followed by the directory. Then, you can input ‘java -jar filetitle.jar’ without the folder path.
. The GUI should appear in a few seconds.
. Type the command in the command box and press kbd:[Enter] to execute it.
. Some example commands you can try:
* *`addbooking`*: Adds a new booking to booking list
* *`listallbookings`*: List all existing bookings in the list
* *`findbooking`*: Filter booking by customer name
* *`viewbookingschedule`*: Shows booking on specific date
* *`deleterecipe`*: Deletes a current recipe from the recipe list
* *`editreqingredient`*: Edits the details and information of a recipe
* *`viewrecipe`*: Shows the additional information for that recipe
* *`editrating`*: Edits the rating of a recipe
* *`viewreqingredient`*: Shows a lists of required ingredients of the different recipes and a combined list of ingredients with its respective amount
* *`help`*: Opens the help window
* *`bye`*: Exits the app
.  Refer to <<Features>> for details of each command.

[[Features]]
== Features

*Command Format with examples.*

* Information with corresponding description are surrounded by <>, they are parameters input by the user.
E.g. `findbooking <customer_name>` can be in the format: `findbooking John`.
* Words found outside <> are keywords that need to be followed strictly.
* Parameters with `...` attached behind can have multiple entries with at least one entry
e.g. `orders/ <order_name_1>...` can be in `orders/ Chicken rice, Seafood pasta, Ribeye Steak` etc.



=== Managing Bookings

Managing booking is a feature that allows the user to do operations such as adding & deleting a booking to booking list, filter out booking based on search date or customer name, and extract the orders for a specific booking.

====  Adding a new booking: `addbooking`

Adds a new booking with all relevant customer details into the booking list. +

Format: `addbooking <customer_name> <customer_contact> <number_of_pax> <booking_date_dd/MM/yyyy> orders/ <order_name_1>, <order_name_2>...`

Examples:

* `addbooking Adam 81234567 4 12/12/2019 orders/ garlic prawn, ribeye steak`

====  Deleting a booking: `deletebooking`

Deletes a customer booking in the booking list +

Format: `deletebooking <booking_list_index*>` +

* booking list index can be found by using the command `listallbookings`.

Examples:

* `deletebooking 1`

====  View all current bookings: `listallbookings`

Shows all current bookings in the booking list. All details including customer name, contact number, number of pax, booking date and orders will be displayed.

Format: `listallbooking`

Output Result: +
 Here are all the current bookings in your list:

. [Customer name: zihan] [Contact No.: 91520567] [No. of pax: 2] [Booking on: 10 October 2019] [Orders: steak and fish]
. [Customer name: John] [Contact No.: 8473739] [No. of pax: 2] [Booking on: 1 January 2019] [Orders: pasta, garlic prawn]
. [Customer name: Alex] [Contact No.: 91837462] [No. of pax: 2] [Booking on: 30 December 2019] [Orders: beef bolognese]

====  Find a specific booking: `findbooking`

Shows the booking containing a specific keyword of the customer name in the booking list. +

Format: `findbooking <customer_name>`

Examples:

* `findbooking john`

Output Result: +
Here are the matching bookings in your list:

. [Customer name: John] [Contact No.: 8473739] [No. of pax: 2] [Booking on: 1 January 2019] [Orders: pasta, garlic prawn]

==== View bookings on specific date: `viewbookingschedule`

Shows the bookings on specific date in the booking list.

Format: `viewbookingschedule <booking_date_ddMMyyy>`

Examples:

* `viewbookingschedule 12/12/2019`

Output Result: +
Here are your bookings for 12 December 2019

. [Customer name: James] [Contact No.: 8371638] [No. of pax: 3] [Booking on: 12 December 2019] [Orders: fish & chip, pasta]

==== View orders for a specific booking: `vieworders`

Shows the orders made by a customer on a specific booking.

Format: `vieworders <customer_name>`

Examples:

* `vieworders john`

Output Result: +
 Here are your orders for: john

* Pasta
* Garlic prawn


=== Managing Recipes

====  Adding a new recipe: `addrecipe`

Adds a new recipe into the recipe list. Duplicate recipes are not allowed. +

Format:

* `addrecipe <recipe_name>`
** Use the `editreqrating` / `editprepstep` / `editreqingredient` / `editreqfeedback` command to add additional information such as rating, cooking steps, ingredients required and feedback for that recipe.

Examples: `addrecipe garlic prawn`

====  Deleting a recipe: `deleterecipe`

Deletes a new recipe in the recipe list +

Format:

* `deleterecipe <recipe_name>`

Examples:

* `deleterecipe garlic prawn`

====  Editing required recipe ingredient:  `editreqingredient`

===== Edits the details and information of a recipe. Users can input which information they would like to edit such as rating, ingredients required, cooking steps, and feedback for that recipe. +

* `ins/` : insert at a certain position in the recipe ingredient list
* `<positon>` : the position of which the recipe ingredient will be inserted
* `q/` : input the quantity of the recipe ingredient after this label
* `<quantity>` : quantity of the recipe ingredient
* `u/` : input the unit of the quantity of the recipe ingredient such as kg, g, ml, l after this label
* `a/` : input any additional information for recipe ingredient after this label
* `<additional_info>` : additional information of the recipe ingredient


Format:

* `editreqingredient <recipe_name> ins/ <position> n/ <ingredient_name> q/ <quantity> u/ <unit> a/ <additional_info>`
* `editreqingredient <recipe_name> del/ <position>`
* `editreqingredient <recipe_name> app/ n/ <ingredient_name> q/ <quantity> u/ <unit> a/ <additional_info>`
* `editreqingredient <recipe_name> clr/`

Examples:

* `editreqingredient fried rice ins/ 1 n/ jasmine rice q/10 u/kg a/mixed with brown rice`
* `editreqingredient fried rice del/ 1`
* `editreqingredient fried rice app/ n/ oil q/1 u/kg`
* `editreqingredient fried clr/`

===== Individual parts can be left empty when editing existing recipe ingredient

Format:

* `editreqingredient <recipe_name> ins/ <position> n/ <ingredient_name> q/u/a/ <additional_info>`
* `editreqingredient <recipe_name> app/n/ <ingredient_name> q/u/ <unit> a/`

Example:

* `editreqingredient fried rice ins/ 1 n/ rice q/u/a/ fried with garlic`
* `editreqingredient fried rice app/n/ rice q/u/kg a/`

==== Editing a recipe rating: `editrating`

Edits the rating of a recipe +

Format: `editrating [recipe name] r/ [rating]`

Example: `editrating chicken rice r/ GOOD`

Output Result:

* `The rating of 'chicken rice' has been edited to: GOOD`

==== Editing a recipe feedback: `editfeedback`

Edits the feedback of a recipe +

Format: `editfeedback [recipe name] f/ [feedback]`

Example: `editfeedback chicken rice f/ too salty`

Output Result:

* `The feedback of 'chicken rice' has been edited to: too salty`

==== Editing a recipe preparation steps: `editprepstep`

Format:

* `editprepstep [recipe name] ins/ [position] p/ [prep step]`
* `editprepstep [recipe name] del/ [position]`
* `editprepstep [recipe_name] app/ p/ prep step]`
* `editprepstep [recipe name] clr/`

Example:

* `editprepstep chicken rice ins/ 1 p/ cooked the rice with pandan leaf`
* `editprepstep chicken rice del/ 1`
* `editprepstep chicken rice app/ p/ cooked the rice with pandan leaf`
* `editprepstep [recipe name] clr/`

====  Listing all recipes: `listallrecipes`

Shows all current recipes in the recipe list. Only the <recipe_number>, <recipe_name> will be displayed. +

Format: `listallrecipes`

Output Result:

* `1. garlic prawn`
* `2. tomato egg`

====  Viewing a specific recipe: `viewrecipe`

Shows the additional information such as rating, ingredients required, cooking steps, and feedback for that recipe. +

Format: `viewrecipe <recipe_name>`

Examples: `viewrecipe garlic prawn`

Output Result:

* `Title: garlic prawn`
* `Rating: Unrated`
* `Preparation Steps:`
* `No preparation steps provided yet.`
* `Required Ingredients:`
* `1. garlic [1.0 | G | No additional information.]`

==== Viewing required recipe ingredient: `viewreqingredient`

Shows a lists of required ingredients of the different recipes and a combined list of ingredients with its respective amount. +

Format: `viewreqingredient <recipe_name>, ………, <recipe_name>`

Example: `viewreqingredient chicken rice, duck rice`

Output Result:

* `Recipe Title: chicken rice`
* `Required Ingredients:`
* `1. rice [1.0 | G | 50% brown rice]`
* `2. brown rice [1.0 | G | No additional information.]`
* `3. jasmine rice [11.0 | G | fried with garlic]`
* `Recipe Title: duck rice`
* `Required Ingredients:`
* `1. jasmine rice [10.0 | G | No additional information.]`
* `2. brown rice [1.0 | G | No additional information.]`
* `Combined list of ingredients with the respective amount:`
* `1. jasmine rice | 21.0`
* `2. rice | 1.0`
* `3. brown rice | 2.0`

=== Managing Inventory

====  Adding ingredients to the inventory: `addtoinventory`

Field inside curly braces is optional. If no additional information is provided, it will be set to default “No additional information”.
If a current ingredient already exists in the inventory, the quantity of the newly added ingredient will add on to the current quantity of that ingredient.

Format: `addtoinventory <ingredient_name> q/ <quantity> u/ <unit> { a/ <additional information> }`

Examples:

* `addtoinventory fish q/ 2 u/ kg a/ store in fridge`
* `addtoinventory prawn q/ 10 u/ g`

==== Deleting ingredients from the inventory: `deletefrominventory`

Deletes an ingredient from list +

Format: `deletefrominventory <ingredient_name>`

Examples:

* `deletefrominventory fish`

====  Updating inventory after using a recipe: `userecipe`

Indicates that a certain recipe is used and to update the inventory list respectively. +
Format: `userecipe <recipe_name>`

Examples:

* `userecipe garlic prawn`

=== Opening the help window: `help`

Opens the help window. +

Format: `help`

===  Exiting the program: `bye`

Exits the program. +

Format: `bye`

===  Saving the data

Booking/recipe/inventory data are saved in the hard disk automatically after any command that changes the data.

There is no need to save manually.

===  Generating recipe based on ingredients [coming in v2.0]

_{Making use of AI and big data to generate suitable recipes for customers.}_

== Command Summary

* Add a new booking: `addbooking <customer_name> <customer_contact> <number_of_pax> <booking_date_dd/MM/yyyy> orders/ <order_name_1>, <order_name_2>...`
* Delete a booking: `deletebooking <booking_list_index>`
* View all current bookings: `listallbooking`
* Find a specific booking:  `findbooking <customer_name>`
* View bookings on specific date: `viewbookingschedule <booking_date_ddMMyyy>`
* View orders for a specific booking: `vieworders <customer_name>`
* Add a recipe : `addrecipe <recipe_name>`
* Delete a specific recipe : `deleterecipe <recipe_number>`
* Edit required ingredient :
** `editreqingredient <recipe_name> ins/ <position> n/ <ingredient_name> q/ <quantity> u/ <unit> a/ <additional_info>`
** `editreqingredient <recipe_name> del/ <position>`
** `editreqingredient <recipe_name> app/ n/ <ingredient_name> q/ <quantity> u/ <unit> a/ <additional_info>`
** `editreqingredient <recipe_name> clr/`
* View all current recipes : `listallrecipes`
* View a specific recipe : `viewrecipe`
* View required ingredient : `viewreqingredient <recipe_name>,..., <recipe_name>`
* Add an ingredient: `addtoinventory`
* Delete an ingredient: `deletefrominventory`
* List all the current ingredients: `listinventory`
* Userecipe : `userecipe <recipe_name>`
* Help: `help`
* Exit : `bye`